import { createClient } from "npm:@supabase/supabase-js@2";
const VERSION='20.14.0';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-powder-load-evidence-token','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'X-Powder-Load-Soak-Version':VERSION}});
function allowed(req:Request){const expected=Deno.env.get('POWDER_LOAD_EVIDENCE_TOKEN')||'';const got=req.headers.get('x-powder-load-evidence-token')||'';return expected.length>=24&&got.length===expected.length&&got===expected}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!['GET','POST'].includes(req.method))return out({error:'Method not allowed'},405);if(!allowed(req))return out({error:'Load/soak metrics token invalid or not configured.'},401);const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});try{
 const body=req.method==='POST'?await req.json().catch(()=>({})):{};const channel=body?.channel==='staging'?'staging':'production',buildId=String(body?.buildId||'powder-20.14.0-production-load-soak-testing').slice(0,180),action=String(body?.action||'snapshot');
 if(action==='sandbox_increment'){const {data,error}=await db.rpc('powder_load_soak_sandbox_increment_v20140',{p_run_id:String(body.runId||''),p_slot:Number(body.slot||0)});if(error)throw error;return out({ok:true,version:VERSION,sandbox:data});}
 if(action==='sandbox_state'){const {data,error}=await db.rpc('powder_load_soak_sandbox_state_v20140',{p_run_id:String(body.runId||''),p_cleanup:body.cleanup===true});if(error)throw error;return out({ok:true,version:VERSION,sandbox:data});}
 if(action==='watchdog'){if(body.confirmOverloadDrill!==true)return out({error:'confirmOverloadDrill=true required.'},400);const {data,error}=await db.rpc('powder_reliability_watchdog_v2080',{p_channel:channel,p_build:buildId,p_actor:'load-soak-runner-v20140'});if(error)throw error;return out({ok:true,version:VERSION,watchdog:data});}
 const [{data:dbm,error:dbe},{data:rel,error:re},{data:recon,error:rce},{data:tx,error:te},{data:obs,error:oe}]=await Promise.all([db.rpc('powder_load_soak_db_metrics_v20140'),db.rpc('powder_reliability_snapshot_v2080',{p_channel:channel,p_build:buildId}),db.rpc('powder_reconciliation_posture_v20120'),db.rpc('powder_transaction_posture_v2090'),db.rpc('powder_observability_health_v2020',{p_channel:channel,p_build:buildId,p_minutes:30})]);
 if(dbe)throw dbe;const mem=Deno.memoryUsage();return out({ok:true,version:VERSION,source:'powder-load-soak-metrics-v20140',sourceRevision:Deno.env.get('DENO_DEPLOYMENT_ID')||'local-unpinned',channel,buildId,db:dbm,memory:{rssMb:Number((mem.rss/1048576).toFixed(2)),heapUsedMb:Number((mem.heapUsed/1048576).toFixed(2)),heapTotalMb:Number((mem.heapTotal/1048576).toFixed(2)),externalMb:Number((mem.external/1048576).toFixed(2))},reliability:re||{healthy:false,error:re?.message},reconciliation:recon||{ready:false,error:rce?.message},transactions:tx||{ready:false,error:te?.message},observability:obs||{healthy:false,error:oe?.message},at:new Date().toISOString()});
}catch(e:any){console.error('[powder-load-soak-metrics 20.14]',e);return out({error:String(e?.message||e)},500)}});
