(()=>{'use strict';
const A=window.POWDER_ADVENTURE_DATA,D=window.POWDER_DATA;if(!A||!D)return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let selectedIsland=1,selectedStageId=null,quiz=null;
const app=()=>window.POWDER_APP;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const progress=()=>app()?.getAdventure?.()||{currentIsland:1,currentStage:1,islandsUnlocked:1,stageStars:{},stagePrep:{},stageWins:{},totalStars:0};
const saveProgress=p=>app()?.updateAdventure?.(p);
const pow=id=>D.pows.find(x=>x.id===id);
const element=id=>D.elements?.[id]||{name:id,icon:'◈',color:'#9dd'};
const combatAsset=id=>`assets/pow-combat-512/${id}.webp?build=13500`;
const kindLabel=k=>k==='boss'?'BOSS':k==='elite'?'TINH ANH':'THƯỜNG';
const kindIcon=k=>k==='boss'?'👑':k==='elite'?'◆':'●';
function islandUnlocked(i,p=progress()){return Number(i.id)<=Number(p.islandsUnlocked||1);}
function stageUnlocked(stage,p=progress()){
 if(!islandUnlocked(A.islandById(stage.islandId),p))return false;
 if(stage.number===1)return true;
 return !!p.stageWins?.[`${stage.islandId}-${stage.number-1}`];
}
function prepPassed(stage,p=progress()){return !!p.stagePrep?.[stage.id]?.passed;}
function stageDone(stage,p=progress()){return !!p.stageWins?.[stage.id];}
function learningGate(stage){return app()?.getDungeonLearningGate?.(stage)||{ready:true,requirement:{RequiredLessonIDs:[],RequiredConceptIDs:[],RequiredMastery:0,Rank:0,Curriculum:{}},masteries:[],missingLessons:[],weak:[],rankOk:true}}
function teamAverageLevel(){const s=app()?.getSave?.()||{},ids=(s.team||[]).filter(id=>s.owned?.[id]);if(!ids.length&&s.starterId)ids.push(s.starterId);return Math.max(1,Math.round(ids.reduce((a,id)=>a+Number(s.owned?.[id]?.level||1),0)/Math.max(1,ids.length)));}
function teamAverageStars(){const s=app()?.getSave?.()||{},ids=(s.team||[]).filter(id=>s.owned?.[id]);if(!ids.length&&s.starterId)ids.push(s.starterId);return Math.max(0,Math.round(ids.reduce((a,id)=>a+Number(s.owned?.[id]?.stars||0),0)/Math.max(1,ids.length)));}
function enemyLevel(stage){return Math.min(100,Math.max(stage.recommendedLevel,Math.round(teamAverageLevel()*(stage.adaptive||1))));}
function enemyStars(stage,powObj){return Math.min(Number(powObj?.maxStars)||7,Math.max(Number(stage?.recommendedStars)||0,teamAverageStars()+(stage?.kind==='boss'?1:stage?.kind==='elite'?1:0)));}
function pressureBars(stage){const n=Math.max(1,Math.min(5,Number(stage?.pressure)||1));return `${'◆'.repeat(n)}${'◇'.repeat(5-n)}`;}
function totalStageCount(){return A.islands.reduce((n,i)=>n+i.stages.length,0);}
function nextStage(stage){const island=A.islandById(stage.islandId),next=island?.stages.find(x=>x.number===stage.number+1);if(next)return next;return A.islandById(stage.islandId+1)?.stages?.[0]||null;}
function currentSuggested(p=progress()){
 const ci=Math.min(12,Math.max(1,Number(p.currentIsland)||1)),island=A.islandById(ci)||A.islands[0];
 return island.stages.find(s=>stageUnlocked(s,p)&&!stageDone(s,p))||island.stages[island.stages.length-1];
}
function storyLine(island,stage){
 if(stage.kind==='boss')return `Ngữ Ấn của ${island.name} nằm ngay phía trước. Muốn khôi phục nó, bạn phải đánh bại ${pow(stage.enemyIds[0])?.name||'Boss'} sau khi chứng minh mình thực sự nhớ kiến thức của đảo.`;
 if(stage.kind==='elite')return `Một Pow Tinh Anh đã hấp thụ Màn Sương Vô Ngôn. Đây là điểm kiểm tra lớn: kiến thức của các chặng trước sẽ được gọi lại trước trận.`;
 const lines=[`Dấu vết Màn Sương dẫn sâu hơn vào ${island.theme}.`,`Một nhóm Pow mất liên kết ngôn ngữ đang chắn con đường tới Ngữ Ấn.`,`Các ký tự vỡ vụn xuất hiện quanh khu vực. Khôi phục từ khóa trước khi chiến đấu.`,`Mỗi câu trả lời đúng làm Mạch Ngôn Ngữ của đội Pow ổn định hơn.`];
 return lines[(stage.number-1)%lines.length];
}
function stageStars(stage,p=progress()){const n=Math.max(0,Math.min(3,Number(p.stageStars?.[stage.id])||0));return `${'★'.repeat(n)}${'☆'.repeat(3-n)}`;}
function renderIslandRail(p){return `<div class="adv-island-rail">${A.islands.map(i=>{const unlocked=islandUnlocked(i,p),active=i.id===selectedIsland,done=i.stages.every(s=>stageDone(s,p));return `<button class="adv-island-tab ${active?'active':''} ${unlocked?'':'locked'} ${done?'done':''}" data-adv-island="${i.id}" ${unlocked?'':'disabled'} style="--island:${i.accent}"><span>${i.icon}</span><div><small>ĐẢO ${String(i.id).padStart(2,'0')}</small><b>${esc(i.name)}</b><em>${unlocked?(done?'ĐÃ KHÔI PHỤC':`${i.stages.filter(s=>stageDone(s,p)).length}/${i.stages.length} màn`):'CHƯA MỞ'}</em></div></button>`}).join('')}</div>`;}
function renderStageMap(island,p){return `<div class="adv-stage-map" style="--island:${island.accent}"><div class="adv-route-line"></div>${island.stages.map((s,idx)=>{const unlocked=stageUnlocked(s,p),done=stageDone(s,p),gate=learningGate(s),prep=gate.ready,selected=s.id===selectedStageId,stars=Number(p.stageStars?.[s.id])||0;return `<button class="adv-stage-node ${s.kind} ${unlocked?'':'locked'} ${done?'done':''} ${gate.ready?'studied':'curriculum-locked'} ${selected?'selected':''}" data-adv-stage="${s.id}" ${unlocked?'':'disabled'} style="--n:${idx}"><span class="adv-node-icon">${done?'✓':kindIcon(s.kind)}</span><b>${s.number}</b><small>${stars?'★'.repeat(stars):(prep?'HỌC ✓':kindLabel(s.kind))}</small></button>`}).join('')}</div>`;}
function enemyCards(stage){return stage.enemyIds.slice(0,stage.enemyCount).map(id=>{const p=pow(id);if(!p)return'';const e=element(p.element),stars=enemyStars(stage,p);return `<div class="adv-enemy"><img src="${combatAsset(id)}" alt="${esc(p.name)}"><span><b>${esc(p.name)}</b><small>${e.icon} ${esc(e.name)} · Lv.${enemyLevel(stage)} · ${stars}★</small><em>x${Number(stage.scale||1).toFixed(2)} chỉ số</em></span></div>`}).join('');}
function detail(stage,island,p){const unlocked=stageUnlocked(stage,p),gate=learningGate(stage),req=gate.requirement||{},done=stageDone(stage,p),stars=Number(p.stageStars?.[stage.id])||0,lessonRows=(req.RequiredLessonIDs||[]).map(id=>{const l=D.lessons.find(x=>x.id===id),m=gate.masteries?.find(x=>x.id===id)?.mastery||0,ok=m>=Number(req.RequiredMastery||0);return `<div class="adv-curriculum-unit ${ok?'ok':'missing'}"><span>${ok?'✓':'○'}</span><div><b>${esc(l?.title||id)}</b><small>${l?.language==='ZH'?'中文':'EN'} · Mastery ${m}% / ${req.RequiredMastery||0}%</small></div></div>`}).join('');return `<aside class="adv-detail ${stage.kind}" style="--island:${island.accent}">
<header><div><small>${kindIcon(stage.kind)} ${kindLabel(stage.kind)} · MÀN ${stage.number}/${island.stages.length}</small><h2>${esc(stage.name)}</h2><div class="adv-pressure p${stage.pressure||1}"><b>${esc(stage.difficultyLabel||'TIÊU CHUẨN')}</b><span>${pressureBars(stage)}</span></div><p>${esc(storyLine(island,stage))}</p></div><strong>${stageStars(stage,p)}</strong></header>
<div class="adv-detail-grid"><div><small>ĐỘI ĐỊCH</small><b>${stage.kind==='boss'?'1 BOSS':`${stage.enemyCount} POW`}</b></div><div><small>CẤP ĐỀ XUẤT</small><b>Lv.${stage.recommendedLevel}</b></div><div><small>RANK HỌC THUẬT</small><b>${esc(req.Curriculum?.name||'Nhập môn')}</b></div><div><small>MASTERY YÊU CẦU</small><b>${req.RequiredMastery||0}%</b></div><div><small>CHỈ SỐ ĐỊCH</small><b>x${Number(stage.scale||1).toFixed(2)}</b></div><div><small>ÁP LỰC MỞ LƯỢT</small><b>+${Number(stage.initiative)||0}</b></div></div>
<div class="adv-enemies">${enemyCards(stage)}</div>
<section class="adv-study-gate ${gate.ready?'passed':''}"><div class="adv-study-icon">${gate.ready?'✓':'📚'}</div><div><small>ĐIỀU KIỆN CURRICULUM</small><b>${gate.ready?'Đã đủ điều kiện vào phó bản':'Học và đạt Mastery trước khi chiến đấu'}</b><span>${esc(req.Curriculum?.chinese||'')} · ${esc(req.Curriculum?.english||'')}</span><em>Combat chỉ lấy câu từ các Learning Unit đã hoàn thành, concept đã mở và SRS đến hạn.</em></div></section>
<div class="adv-curriculum-list">${lessonRows||'<div class="adv-curriculum-unit ok"><span>✓</span><div><b>Không có Learning Unit bắt buộc</b></div></div>'}</div>
<div class="adv-star-objectives"><span class="${stars>=1?'on':''}">★ Chiến thắng</span><span class="${stars>=2?'on':''}">★ Mastery ≥ 90%</span><span class="${stars>=3?'on':''}">★ Kiến thức Combat ≥ 95%</span></div>
<div class="adv-reward"><span><img class="currency-inline-icon" src="assets/items/ui-compact/military-coin.webp" alt=""> <b>${stage.rewards.coins}</b> Coin</span><span>✦ <b>${stage.rewards.exp}</b> EXP gameplay</span><span>📚 Câu sai → SRS</span></div>
<footer>${!unlocked?`<button disabled>🔒 HOÀN THÀNH MÀN TRƯỚC</button>`:!gate.ready?`<button class="study" data-adv-go-learn="${stage.id}">📖 ĐẾN KHU HỌC TẬP</button>`:`<button class="battle" data-adv-battle="${stage.id}">${done?'⚔ ĐÁNH LẠI':'⚔ VÀO TRẬN'}</button>`}</footer>
</aside>`;}function render(){const root=$('#adventureView');if(!root)return;const p=progress(),save=app()?.getSave?.()||{};if(!selectedIsland||!islandUnlocked(A.islandById(selectedIsland),p))selectedIsland=Number(p.currentIsland)||1;const island=A.islandById(selectedIsland)||A.islands[0];let stage=A.stageById(selectedStageId);if(!stage||stage.islandId!==island.id||!stageUnlocked(stage,p))stage=island.stages.find(s=>stageUnlocked(s,p)&&!stageDone(s,p))||island.stages.filter(s=>stageUnlocked(s,p)).at(-1)||island.stages[0];selectedStageId=stage.id;const completed=Object.keys(p.stageWins||{}).filter(k=>p.stageWins[k]).length;
 root.innerHTML=`<div class="section-title world-section-title"><div><p class="eyebrow">POWDER WORLD</p><h1>Phiêu lưu & Chiến tuyến</h1></div><p>Chiến đấu chỉ bắt đầu từ màn Map, Boss hoặc Sự kiện và luôn gắn với tiến trình người chơi.</p></div><div class="world-view-switch"><button class="world-view-btn is-active" data-world-view="adventure">🗺️ Cốt truyện</button><button class="world-view-btn" data-world-view="boss">👑 Boss ngày · tuần · sự kiện</button></div><div class="adv-shell" style="--island:${island.accent}"><header class="adv-world-head"><div><p class="eyebrow">POWDER WORLD · STORY PVE</p><h1>${esc(A.title)}</h1><p>Khôi phục 12 Ngữ Ấn theo vòng <b>Learning → Mastery → Dungeon → Review</b>. Mỗi màn kiểm tra Learning Unit, concept, Rank và Mastery trước khi mở Combat.</p></div><div class="adv-world-stats"><span><small>ĐẢO</small><b>${p.islandsUnlocked||1}/12</b></span><span><small>MÀN ĐÃ QUA</small><b>${completed}/${totalStageCount()}</b></span><span class="adv-boss-point-stat"><img src="assets/items/ui-compact/boss-point.webp" alt="Boss Point"><small>BOSS POINT</small><b>${Number(save.bossPoints||0).toLocaleString('vi-VN')}</b></span></div></header><div class="adv-mode-cards"><button class="adv-mode-card boss" data-world-view="boss"><small>ĐIỆN BOSS</small><b>Boss ngày · Boss tuần · Boss thăng rank</b><span>Vào khu Boss mà không rời cụm Phiêu lưu.</span></button></div>
<section class="adv-world-grid">${renderIslandRail(p)}<main class="adv-map-panel"><header class="adv-island-head"><div class="adv-island-emblem">${island.icon}</div><div><small>ĐẢO ${String(island.id).padStart(2,'0')} · ${esc(island.en)}</small><h2>${esc(island.name)}</h2><p>${esc(island.story)}</p><span>📚 ${esc(island.lesson)}</span></div></header>${renderStageMap(island,p)}<div class="adv-map-legend"><span>● Thường</span><span>◆ Tinh Anh</span><span>👑 Boss</span><span>✓ Đã hoàn thành</span></div></main>${detail(stage,island,p)}</section></div>`;
 bind();}
function bind(){const root=$('#adventureView');if(!root)return;$$('[data-world-view]',root).forEach(b=>b.onclick=()=>window.POWDER_APP?.showView?.(b.dataset.worldView));$$('[data-adv-island]',root).forEach(b=>b.onclick=()=>{selectedIsland=Number(b.dataset.advIsland);selectedStageId=null;saveProgress({currentIsland:selectedIsland});render();});$$('[data-adv-stage]',root).forEach(b=>b.onclick=()=>{selectedStageId=b.dataset.advStage;render();});$$('[data-adv-study]',root).forEach(b=>b.onclick=()=>startStudy(A.stageById(b.dataset.advStudy)));$$('[data-adv-go-learn]',root).forEach(b=>b.onclick=()=>{const stage=A.stageById(b.dataset.advGoLearn),gate=learningGate(stage),id=gate.requirement?.RequiredLessonIDs?.find(x=>gate.missingLessons?.includes(x)||gate.weak?.some(w=>w.id===x))||gate.requirement?.RequiredLessonIDs?.[0];if(id)app()?.openLessonFromDungeon?.(id);else app()?.showView?.('learn')});$$('[data-adv-battle]',root).forEach(b=>b.onclick=()=>startBattle(A.stageById(b.dataset.advBattle)));}
function optionsFor(island,term,key){const vals=[term[key],...island.words.filter(x=>x!==term).map(x=>x[key])];const uniq=[...new Set(vals)].slice(0,4);while(uniq.length<4)uniq.push('—');for(let i=uniq.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[uniq[i],uniq[j]]=[uniq[j],uniq[i]];}return uniq;}
function questionFor(island,term,index){const mode=index%5;if(mode===0)return{prompt:`“${term.zh}” (${term.py}) nghĩa là gì?`,answer:term.vi,options:optionsFor(island,term,'vi'),tag:'中文 → Việt'};if(mode===1)return{prompt:`Tiếng Trung của “${term.vi}” là gì?`,answer:term.zh,options:optionsFor(island,term,'zh'),tag:'Việt → 中文'};if(mode===2)return{prompt:`“${term.en}” nghĩa tiếng Việt là gì?`,answer:term.vi,options:optionsFor(island,term,'vi'),tag:'English → Việt'};if(mode===3)return{prompt:`Tiếng Anh của “${term.vi}” là gì?`,answer:term.en,options:optionsFor(island,term,'en'),tag:'Việt → English'};return{prompt:`Pinyin đúng của “${term.zh}” là gì?`,answer:term.py,options:optionsFor(island,term,'py'),tag:'中文 → Pinyin'};}
function startStudy(stage){if(!stage)return;const gate=learningGate(stage),id=gate.requirement?.RequiredLessonIDs?.find(x=>gate.missingLessons?.includes(x)||gate.weak?.some(w=>w.id===x))||gate.requirement?.RequiredLessonIDs?.[0];if(id)app()?.openLessonFromDungeon?.(id);else app()?.showView?.('learn');}
function ensureQuizModal(){let m=$('#adventureQuiz');if(m)return m;m=document.createElement('section');m.id='adventureQuiz';m.className='adv-quiz-overlay';m.hidden=true;document.body.appendChild(m);return m;}
function renderQuiz(){const m=ensureQuizModal();if(!quiz){m.hidden=true;return;}const q=quiz.questions[quiz.index];m.hidden=false;m.innerHTML=`<div class="adv-quiz-card" style="--island:${quiz.island.accent}"><header><div><small>NGỮ ẤN · ${esc(quiz.island.name)}</small><h2>${quiz.stage.kind==='boss'?'THỬ THÁCH TRƯỚC BOSS':'BÀI HỌC TRƯỚC TRẬN'}</h2></div><button data-adv-quiz-close>×</button></header><div class="adv-quiz-progress"><span style="width:${(quiz.index/quiz.questions.length)*100}%"></span></div><div class="adv-quiz-meta"><span>${esc(q.tag)}</span><b>CÂU ${quiz.index+1}/${quiz.questions.length}</b><span>Đúng ${quiz.correct}</span></div><p class="adv-quiz-question">${esc(q.prompt)}</p><div class="adv-quiz-options">${q.options.map((o,i)=>`<button data-adv-answer="${i}" ${quiz.answered?'disabled':''}>${esc(o)}</button>`).join('')}</div><div class="adv-quiz-feedback" data-feedback></div><footer><span>Cần <b>${quiz.stage.prepNeed}/${quiz.stage.prepCount}</b> để mở Combat.</span><button data-adv-next disabled>${quiz.index===quiz.questions.length-1?'KẾT QUẢ':'CÂU TIẾP'}</button></footer></div>`;
 $('[data-adv-quiz-close]',m).onclick=()=>{quiz=null;m.hidden=true;};$$('[data-adv-answer]',m).forEach(b=>b.onclick=()=>answerQuiz(Number(b.dataset.advAnswer)));$('[data-adv-next]',m).onclick=nextQuiz;}
function answerQuiz(i){if(!quiz||quiz.answered)return;const q=quiz.questions[quiz.index],chosen=q.options[i],ok=chosen===q.answer;quiz.answered=true;if(ok){quiz.correct++;app()?.grantLearningProgress?.({correct:true,source:'lesson'});}const m=$('#adventureQuiz');$$('[data-adv-answer]',m).forEach((b,idx)=>{const val=q.options[idx];b.classList.toggle('correct',val===q.answer);b.classList.toggle('wrong',idx===i&&!ok);b.disabled=true;});const f=$('[data-feedback]',m);f.className=`adv-quiz-feedback ${ok?'ok':'bad'}`;f.innerHTML=ok?`<b>✓ CHÍNH XÁC</b><span>${esc(q.answer)}</span>`:`<b>✕ CHƯA ĐÚNG</b><span>Đáp án: ${esc(q.answer)}</span>`;$('[data-adv-next]',m).disabled=false;}
function nextQuiz(){if(!quiz||!quiz.answered)return;if(quiz.index<quiz.questions.length-1){quiz.index++;quiz.answered=false;renderQuiz();return;}finishQuiz();}
function finishQuiz(){const {stage,correct,questions}=quiz,total=questions.length,pass=correct>=stage.prepNeed,pct=Math.round(correct/total*100),p=progress(),prev=p.stagePrep?.[stage.id]||{},record={passed:pass||prev.passed,bestCorrect:Math.max(Number(prev.bestCorrect)||0,correct),bestPct:Math.max(Number(prev.bestPct)||0,pct),total,attempts:(Number(prev.attempts)||0)+1,lastCorrect:correct};const nextPrep={...(p.stagePrep||{}),[stage.id]:record};saveProgress({stagePrep:nextPrep,currentIsland:stage.islandId,currentStage:stage.number,lastStage:stage.id});const m=$('#adventureQuiz');m.innerHTML=`<div class="adv-quiz-card result ${pass?'pass':'fail'}"><div class="adv-quiz-result-icon">${pass?'✓':'↻'}</div><small>${pass?'NGỮ ẤN ĐÃ ỔN ĐỊNH':'CẦN ÔN LẠI'}</small><h2>${correct}/${total} · ${pct}%</h2><p>${pass?'Bạn đã mở quyền chiến đấu ở màn này. Các câu hỏi trong Combat tiếp tục quyết định sức mạnh kỹ năng.':`Màn này cần đúng ít nhất ${stage.prepNeed}/${total}. Học lại ngay, không mất tài nguyên.`}</p><div class="adv-quiz-result-actions">${pass?`<button data-adv-result-battle>⚔ VÀO TRẬN</button>`:`<button data-adv-result-retry>📖 HỌC LẠI</button>`}<button data-adv-result-map>VỀ BẢN ĐỒ</button></div></div>`;if(pass)$('[data-adv-result-battle]',m).onclick=()=>{quiz=null;m.hidden=true;render();startBattle(stage);};else $('[data-adv-result-retry]',m).onclick=()=>startStudy(stage);$('[data-adv-result-map]',m).onclick=()=>{quiz=null;m.hidden=true;render();};}
function startBattle(stage){if(!stage)return;const p=progress();if(!stageUnlocked(stage,p))return;const gate=learningGate(stage);if(!gate.ready){startStudy(stage);return;}const combat=window.POWDER_COMBAT_ENTRY_V177;if(!combat?.startMap){window.alert('Combat Map chưa sẵn sàng.');return;}selectedIsland=stage.islandId;selectedStageId=stage.id;saveProgress({currentIsland:stage.islandId,currentStage:stage.number,lastStage:stage.id});combat.startMap(stage);}
function onBattleFinished({stage,win,summary}){if(!stage)return;const p=progress();if(!win){saveProgress({lastStage:stage.id});return;}const gate=learningGate(stage),actions=(summary?.players||[]).reduce((a,x)=>a+(Number(x.knowledgeActions)||0),0),knowledge=actions?(summary.players||[]).reduce((a,x)=>a+(Number(x.knowledgeSum)||0),0)/actions:0,gateMastery=gate.masteries?.length?Math.round(gate.masteries.reduce((a,x)=>a+Number(x.mastery||0),0)/gate.masteries.length):100;let stars=1;if(gateMastery>=90)stars++;if(knowledge>=.95)stars++;const stageStars={...(p.stageStars||{}),[stage.id]:Math.max(Number(p.stageStars?.[stage.id])||0,stars)},stageWins={...(p.stageWins||{}),[stage.id]:true};const next=nextStage(stage);let islandsUnlocked=Number(p.islandsUnlocked)||1,currentIsland=stage.islandId,currentStage=stage.number;if(next){currentIsland=next.islandId;currentStage=next.number;if(next.islandId>stage.islandId)islandsUnlocked=Math.max(islandsUnlocked,next.islandId);}saveProgress({stageStars,stageWins,islandsUnlocked,currentIsland,currentStage,lastStage:stage.id,lastBattleKnowledge:knowledge});}
function restoreCombatContext(context={}){const stage=A.stageById(context.stageId);if(stage){selectedIsland=stage.islandId;selectedStageId=stage.id;saveProgress({currentIsland:stage.islandId,currentStage:stage.number,lastStage:stage.id});}render();}
function openNextStage(id){const current=A.stageById(id),n=current&&nextStage(current);if(!n)return;selectedIsland=n.islandId;selectedStageId=n.id;saveProgress({currentIsland:n.islandId,currentStage:n.number});setTimeout(render,0);}
function install(){selectedIsland=Number(progress().currentIsland)||1;const suggested=currentSuggested();selectedStageId=suggested?.id||'1-1';render();window.POWDER_ADVENTURE={render,startStudy,startBattle,onBattleFinished,restoreCombatContext,openNextStage,getProgress:progress,stageUnlocked,prepPassed,learningGate};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,100),{once:true});else setTimeout(install,100);
})();
