(()=>{'use strict';
const WORLD=window.POWDER_WORLD_DATA_V9;if(!WORLD)return;const DATA={version:'13.4-artifact-progression-safe-batch',artifacts:WORLD.artifacts||[],summon:WORLD.economy?.artifactSummon||{},rarityLabel:{common:'Thường',rare:'Hiếm',super_rare:'Siêu hiếm',epic:'Sử thi',legendary:'Huyền thoại',mythic:'Thần thoại',ancient:'Thượng cổ'},rarityOrder:{common:0,rare:1,super_rare:2,epic:3,legendary:4,mythic:5,ancient:6}};
const KEY='powder_artifact_module_9520';
const R=DATA.rarityOrder,L=DATA.rarityLabel,MAX_STAR={common:1,rare:2,super_rare:3,epic:4,legendary:5,mythic:6,ancient:7};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const itemThumb=asset=>window.POWDER_ITEM_THUMBNAILS?.[asset]||asset;
const clone=v=>JSON.parse(JSON.stringify(v));
const upgradeCfg=WORLD.economy?.artifactUpgrade||{},upgradeRates=upgradeCfg.rarityRates||{common:.01,rare:.02,super_rare:.05,epic:.08,legendary:.10,mythic:.20,ancient:.30};
const artifactOf=ref=>{if(typeof A!=='undefined'&&A?.getArtifact){const x=A.getArtifact(ref);if(x)return x}const raw=DATA.artifacts.find(x=>x.id===ref)||null;if(!raw)return null;return{...raw,artifactId:raw.id,instanceId:null,upgradeLevel:0,upgradeRate:Number(raw.upgradeRate??upgradeRates[raw.rarity]??0),maxUpgrade:Number(raw.maxUpgrade||10),baseStats:{...(raw.baseStats||raw.statBonusPct||{})},statBonusPct:{...(raw.baseStats||raw.statBonusPct||{})},effect:raw.effect?{...raw.effect}:raw.effect}};
const fallback={owned:{},equipped:{},summon:{history:[],since:{super_rare:0,epic:0,legendary:0,mythic:0,ancient:0}},settings:{sound:true,vibration:true}};
function load(){try{return{...clone(fallback),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})}}catch(_){return clone(fallback)}}
let local=load();
let A={
 getRank:()=>Number(window.POWDER_APP?.getSave?.()?.rank||0),
 getSettings:()=>window.POWDER_APP?.getSave?.()?.settings||local.settings||{},
 getTickets:()=>0,
 spendTickets:()=>false,
 refundTickets:()=>false,
 getOwned:()=>local.owned,
 setOwned:v=>{local.owned=v;persist()},
 getInstances:()=>({}),
 setInstances:()=>{},
 addInstance:null,
 getArtifact:null,
 getUpgradePreview:null,
 upgradeInstance:null,
 setProtection:null,
 getEquipped:()=>local.equipped,
 setEquipped:v=>{local.equipped=v;persist()},
 getSummon:()=>local.summon,
 setSummon:v=>{local.summon=v;persist()},
 onChange:()=>{},
 onSummon:()=>{}
};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(local))}catch(_){}}
function configure(x={}){A={...A,...x};return API}
function allInstances(){return Object.values(A.getInstances?.()||{})}
function qty(id){const arr=allInstances();if(arr.length)return arr.filter(x=>x.artifactId===id).length;return Number(A.getOwned?.()?.[id]||0)}
function getInstance(instanceId){return A.getInstances?.()?.[instanceId]||null}
function addInstance(artifactId){if(A.addInstance)return A.addInstance(artifactId);const o={...(A.getOwned?.()||{})};o[artifactId]=Math.max(0,Number(o[artifactId]||0))+1;A.setOwned?.(o);A.onChange?.();return{instanceId:null,artifactId,upgradeLevel:0}}
function getEquipped(powId){return A.getEquipped?.()?.[powId]||null}
function equip(powId,ref){const it=artifactOf(ref);if(!powId||!it)return false;const eq={...(A.getEquipped?.()||{})};eq[powId]=it.instanceId||ref;A.setEquipped?.(eq);A.onChange?.();return true}
function unequip(powId){const eq={...(A.getEquipped?.()||{})};delete eq[powId];A.setEquipped?.(eq);A.onChange?.();return true}
function statProfile(id){return artifactOf(id)?.statBonusPct||null}
function applyStats(stats,id){const out={...stats},p=statProfile(id);if(!p)return out;for(const k of ['hp','atk','def','ap','speed'])if(out[k]!=null&&Number(p[k]||0))out[k]=Math.max(1,Math.round(Number(out[k])*(1+Number(p[k]))));return out}
function ratesForRank(rank=A.getRank?.()||0){const by=DATA.summon.ratesByTamerRank||{};return{...(by[String(Math.max(0,Math.min(6,Number(rank)||0)))]||DATA.summon.rates)}}
function pityUnlocked(r,rank=A.getRank?.()||0){return Number(rank)>=Number(DATA.summon.pityUnlockRank?.[r]??99)}
function pityMin(rank=A.getRank?.()||0){const s=A.getSummon?.()||clone(fallback.summon);for(const r of ['ancient','mythic','legendary','epic','super_rare']){if(!pityUnlocked(r,rank))continue;const max=Number(DATA.summon.pity?.[r]||0),n=Number(s.since?.[r]||0);if(max&&n>=max-1)return r}return null}
function random01(){try{if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}}catch(_){}return Math.random()}
function pickRarity(minRarity=null,rank=A.getRank?.()||0){const rates=ratesForRank(rank),min=minRarity==null?0:R[minRarity],tiers=Object.keys(rates).filter(r=>Number(rates[r])>0&&R[r]>=min),total=tiers.reduce((s,r)=>s+Number(rates[r]),0);let roll=random01()*total;for(const r of tiers){roll-=Number(rates[r]);if(roll<=0)return r}return tiers.at(-1)||'common'}
function summonOne(){const rank=A.getRank?.()||0,forced=pityMin(rank),rarity=pickRarity(forced,rank),pool=DATA.artifacts.filter(x=>x.rarity===rarity),it=pool[Math.min(pool.length-1,Math.floor(random01()*pool.length))];const s=clone(A.getSummon?.()||fallback.summon);s.since=s.since||{};for(const r of ['super_rare','epic','legendary','mythic','ancient']){if(!pityUnlocked(r,rank))continue;if(R[rarity]>=R[r])s.since[r]=0;else s.since[r]=Number(s.since[r]||0)+1}s.history=[it.id,...(s.history||[])].slice(0,30);A.setSummon?.(s);const before=qty(it.id),inst=addInstance(it.id),after=qty(it.id);return{...it,instanceId:inst?.instanceId||null,upgradeLevel:0,isNew:before===0,copy:after}}
let summonBusy=false;function summon(count=1,{reveal=true}={}){if(summonBusy)return[];count=count===10?10:1;const tickets=Math.max(0,Math.floor(Number(A.getTickets?.())||0));if(tickets<count)return[];summonBusy=true;const snapshot={owned:clone(A.getOwned?.()||{}),instances:clone(A.getInstances?.()||{}),summon:clone(A.getSummon?.()||fallback.summon)};let reserved=false;try{if(!A.spendTickets?.(count))return[];reserved=true;const out=Array.from({length:count},summonOne),committed=A.onSummon?.(out);if(committed===false)throw new Error('Không thể xác nhận lượt triệu hồi');if(reveal)showReveal(out);return out}catch(err){console.error('[Artifact summon rollback]',err);try{A.setOwned?.(snapshot.owned);A.setInstances?.(snapshot.instances);A.setSummon?.(snapshot.summon);if(reserved)A.refundTickets?.(count)}catch(rollbackErr){console.error('[Artifact summon rollback failed]',rollbackErr)}return[]}finally{setTimeout(()=>{summonBusy=false},120)}}
function rarityChip(r){return `<span class="w8-rarity r-${esc(r)}">${esc(L[r]||r)}</span>`}
function formatPct(v){return Number(v||0).toLocaleString('vi-VN',{maximumFractionDigits:2})+'%'}
function artifactStatText(it){const x=artifactOf(it?.instanceId||it?.id||it),p=x?.statBonusPct,b=x?.baseStats;if(!p||!b)return'Không cộng % chỉ số';const fmt=v=>(Number(v||0)*100).toLocaleString('vi-VN',{maximumFractionDigits:2})+'%',base=fmt(b.hp||b.atk||b.def||b.ap||0),now=fmt(p.hp||p.atk||p.def||p.ap||0);return `+${Number(x.upgradeLevel||0)} · ${base} → ${now} HP/ATK/DEF/AP${Number(p.speed||0)?` · SPEED ${fmt(p.speed)}`:''}`}
let audioCtx=null;
function tone(freq=440,dur=.22,gain=.035,type='sine',delay=0){const settings=A.getSettings?.()||{};if(settings.sound===false)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioCtx=audioCtx||new AC();const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.03)}catch(_){}}
function vibrate(p){const s=A.getSettings?.()||{};if(s.vibration&&navigator?.vibrate)navigator.vibrate(p)}
function journey(i){tone(300+i*58,.24,.024+i*.003,i>=4?'triangle':'sine');if(i===2)vibrate(22)}
function apex(){[523.25,659.25,783.99].forEach((f,i)=>tone(f,.5,.035,'triangle',i*.06));vibrate([28,20,45])}
function burst(r){const top=R[r]||0,base=[247,277,294,330,392,466,554][top]||330;[1,1.25,1.5,2].forEach((m,i)=>tone(base*m,.72,top>=4?.055:.04,top>=5?'triangle':'sine',i*.08));vibrate(top>=5?[35,20,55]:22)}
function resultChord(r){const top=R[r]||0,base=top>=6?659:top>=5?587:523;[1,1.25,1.5].forEach((m,i)=>tone(base*m,.38,.028,'sine',i*.05))}
function showReveal(results){document.querySelector('.pa-summon-modal')?.remove();if(!results?.length)return;const top=results.reduce((a,b)=>R[b.rarity]>R[a.rarity]?b:a,results[0]),bestIndex=results.findIndex(x=>x===top),settings=A.getSettings?.()||{},perfTier=window.POWDER_PERFORMANCE_V1757?.tier?.()||'full',reduced=!!(settings.reducedMotion||settings.skipSummon||perfTier==='low'),balanced=perfTier==='balanced',modal=document.createElement('div');modal.className=`pa-summon-modal w93-summon-modal w960-ticket-modal rarity-${esc(top.rarity)}${reduced?' no-motion':''}${balanced?' perf-balanced':''}`;
const cards=results.map((it,i)=>`<article class="w93-reveal-card r-${esc(it.rarity)} ${i===bestIndex?'w94-best-pull':''}" style="--i:${i}" title="${esc(it.effectText||'')}"><div><img src="${esc(it.asset)}">${it.isNew?'<span class="w94-new-badge">MỚI</span>':''}${i===bestIndex&&results.length>1?'<span class="w94-best-badge">BEST</span>':''}</div>${rarityChip(it.rarity)}<b>${esc(it.name)}</b><small>${it.copy?`Bản thứ ×${it.copy} · +0`:`Đã sở hữu ×${qty(it.id)}`}</small>${results.length===1?`<p class="w94-single-effect">${esc(artifactStatText(it))}</p><p class="w94-single-effect">${esc(it.effectText||'')}</p>`:''}</article>`).join('');
modal.innerHTML=`<div class="w93-summon-shell w960-ticket-shell"><button class="w93-summon-close" data-close aria-label="Đóng">×</button><button class="w931-skip" data-skip>Bỏ qua</button><section class="w960-stage" data-stage="ticket"><small>NGHI THỨC CỔ ẤN · FANTASY RELIC GATE</small><h2>${results.length===10?'Dâng 10 Vé Cổ Ấn':'Dâng Vé Cổ Ấn'}</h2><p>Vé phải đi đúng trục, đầu vé lọt chính xác vào khe Cổ Môn rồi mới được Cổ Ấn hấp thụ.</p><div class="w960-ticket-machine" data-machine><div class="w960-machine-backdrop"></div><div class="w961-gate"><div class="w961-gate-ring"></div><div class="w960-ticket-slot"><span>KHE CỔ ẤN</span></div><div class="w961-slot-mouth"></div><div class="w961-slot-indicator"><i></i><b>CỔ MÔN ĐANG CHỜ ẤN VÉ</b></div></div><div class="w960-slot-beam"></div><div class="w961-ticket-focus"></div><div class="w961-ticket-rail"></div><div class="w960-ticket" data-ticket><em>ARCANE RELIC PASS</em><i>✦</i><b>VÉ CỔ ẤN</b><span>${results.length===10?'×10':'×1'}</span></div><div class="w960-insert-trail"></div><div class="w961-guide-arrow"><i></i><span>ĐÚNG TRỤC · ĐÚT ĐẦU VÉ VÀO KHE</span></div></div><div class="w960-ticket-hint" data-hint>Căn đầu vé đúng với khe tiếp nhận...</div></section><section class="w960-stage w960-burst-stage" data-stage="burst" hidden><div class="w961-burst-aura"></div><div class="w960-burst-rays"></div><div class="w961-burst-ring ring-a"></div><div class="w961-burst-ring ring-b"></div><div class="w960-burst-core"></div><div class="w961-burst-flash"></div><small>CỔ MÔN CỘNG HƯỞNG</small><h2>${esc(L[top.rarity])}</h2><p>Ánh sáng cộng hưởng đang lan đều từ tâm Cổ Môn...</p></section><section class="w960-stage w960-result-stage" data-stage="result" hidden><small>KẾT QUẢ TRIỆU HỒI</small><h2>${results.length===10?'10 Cổ vật đã thức tỉnh':'Cổ vật đã thức tỉnh'}</h2><div class="w93-reveal-grid w931-result-grid ${results.length===1?'single':'ten'}" data-grid></div><button class="pa-btn primary w93-reveal-done" data-done>Nhận Cổ vật</button></section></div>`;
document.body.appendChild(modal);const stage=n=>modal.querySelector(`[data-stage="${n}"]`),ticketStage=stage('ticket'),burstStage=stage('burst'),resultStage=stage('result'),machine=modal.querySelector('[data-machine]'),ticket=modal.querySelector('[data-ticket]'),hint=modal.querySelector('[data-hint]'),skip=modal.querySelector('[data-skip]');let phase='ticket',timers=[];const later=(fn,ms)=>timers.push(setTimeout(fn,ms)),clear=()=>timers.splice(0).forEach(clearTimeout);const showResult=()=>{if(phase==='result')return;phase='result';clear();ticketStage.hidden=true;burstStage.hidden=true;const grid=modal.querySelector('[data-grid]');grid.innerHTML=cards;resultStage.hidden=false;skip.textContent='Đóng';resultChord(top.rarity)};const showBurst=()=>{if(phase!=='ticket')return;phase='burst';ticketStage.hidden=true;burstStage.hidden=false;apex();later(()=>burst(top.rarity),140);later(showResult,2600)};const close=()=>phase==='result'?modal.remove():showResult();modal.querySelector('[data-close]').onclick=close;skip.onclick=()=>phase==='result'?modal.remove():showResult();modal.querySelector('[data-done]').onclick=()=>modal.remove();if(reduced){showResult();return}if(balanced){ticketStage.hidden=true;burstStage.hidden=false;phase='burst';later(()=>burst(top.rarity),60);later(showResult,520);return}later(()=>{machine.classList.add('active');hint.textContent='Vé Cổ Ấn xuất hiện ngay dưới khe · đang căn đúng trục hấp thụ...';journey(0)},220);later(()=>{machine.classList.add('engaging');hint.textContent='Đầu vé đã chạm đúng miệng khe · đang tiến thẳng vào trung tâm Cổ Môn...';journey(1)},1080);later(()=>{machine.classList.add('seated');hint.textContent='Vé đã nằm đúng khe · Cổ Môn đang kéo sâu vào và khóa đường dẫn...';journey(1)},1940);later(()=>{machine.classList.add('charged');hint.textContent='Vé đã được hấp thụ hoàn toàn · ma lực đang nén để khai mở kết quả...';journey(2)},2940);later(showBurst,3940)}
function formatStatName(k){return({hp:'HP',atk:'ATK',def:'DEF',ap:'AP',speed:'SPEED',critRate:'CRIT',critDamage:'CRIT DMG',healing:'HỒI PHỤC',elementDamage:'ELEMENT DMG'}[k]||String(k).toUpperCase())}
function formatStatValue(v){return (Number(v||0)*100).toLocaleString('vi-VN',{maximumFractionDigits:2})+'%'}
function upgradeModalMarkup(instanceId){const it=artifactOf(instanceId),pv=A.getUpgradePreview?.(instanceId);if(!it||!pv)return'';const inst=getInstance(instanceId)||{},missing=Math.max(0,Number(pv.need||0)-Number(pv.available||0)),rows=(pv.statRows||[]).map(r=>`<div class="pa126-stat-row"><b>${esc(formatStatName(r.stat))}</b><span><small>${formatStatValue(r.base)} Base</small><strong>${formatStatValue(r.current)} → ${formatStatValue(r.next)}</strong><em>+${formatStatValue(r.bonusNext)}</em></span></div>`).join(''),materials=(pv.materials||[]).map((m,i)=>`<li><b>#${i+1}</b><span>${esc(m.instanceId)}</span><small>+0 · ${new Date(Number(m.acquiredAt)||Date.now()).toLocaleString('vi-VN')}</small></li>`).join('');return `<div class="pa126-upgrade-shell r-${esc(it.rarity)}"><button class="pa126-close" data-upgrade-close>×</button><header><img src="${esc(it.asset)}"><div>${rarityChip(it.rarity)}<h2>${esc(it.name)} +${it.upgradeLevel}</h2><p>${esc(it.effectText||'')}</p><small>Hiệu ứng đặc biệt và Set Bonus không tăng theo +.</small></div></header><section class="pa126-upgrade-level"><div><small>HIỆN TẠI</small><b>+${pv.current}</b></div><i>→</i><div><small>SAU NÂNG CẤP</small><b>+${pv.next}</b></div><span>Mỗi +1 của ${esc(L[it.rarity])}: <strong>+${Math.round(Number(pv.rate||0)*100)}%</strong> chỉ số gốc · tính tuyến tính</span></section><section class="pa126-stat-list">${rows||'<p>Cổ vật này không có stat số học để tăng.</p>'}</section><section class="pa126-materials"><div><h3>NGUYÊN LIỆU CÙNG ARTIFACT ID</h3><b>${Math.min(pv.available,pv.need)} / ${pv.need}</b></div><p>Chỉ dùng bản <b>+0</b>, không khóa, không yêu thích và không trang bị.</p><ul>${materials||'<li class="empty">Chưa có bản +0 đủ điều kiện.</li>'}</ul>${missing?`<strong class="pa126-missing">🔒 Thiếu ${missing} bản</strong>`:'<strong class="pa126-ready">✓ Đủ nguyên liệu</strong>'}</section><section class="pa126-protect"><button data-upgrade-protect="isLocked" class="${inst.isLocked?'on':''}">${inst.isLocked?'🔒 Đã khóa':'🔓 Khóa bản này'}</button><button data-upgrade-protect="isFavorite" class="${inst.isFavorite?'on':''}">${inst.isFavorite?'★ Đã yêu thích':'☆ Yêu thích'}</button><small>${inst.equippedBy?'Đang trang bị cho Pow · vẫn có thể nâng bản chính, nhưng không bao giờ bị dùng làm nguyên liệu.':'Bản chính được giữ lại sau nâng cấp.'}</small></section><button class="pa-btn primary pa126-confirm" data-upgrade-confirm ${!pv.canUpgrade?'disabled':''}>${pv.current>=pv.max?'ĐÃ ĐẠT +'+pv.max:`NÂNG CẤP +${pv.current} → +${pv.next}`}</button></div>`}
function showUpgrade(instanceId,onDone=null){document.querySelector('.pa126-upgrade-modal')?.remove();if(!getInstance(instanceId)||!A.getUpgradePreview?.(instanceId))return false;const modal=document.createElement('div');modal.className='pa126-upgrade-modal';modal.dataset.instanceId=instanceId;const render=()=>{modal.innerHTML=upgradeModalMarkup(instanceId);modal.querySelector('[data-upgrade-close]')?.addEventListener('click',()=>modal.remove());modal.querySelectorAll('[data-upgrade-protect]').forEach(b=>b.onclick=()=>{A.setProtection?.(instanceId,b.dataset.upgradeProtect);render();onDone?.()});modal.querySelector('[data-upgrade-confirm]')?.addEventListener('click',()=>{const pv=A.getUpgradePreview?.(instanceId);if(!pv?.canUpgrade)return;if(!confirm(`Nâng ${pv.name} +${pv.current} → +${pv.next}?\nSẽ tiêu hao ${pv.need} bản +0 cùng ArtifactID.`))return;const ok=A.upgradeInstance?.(instanceId);if(ok){resultChord(pv.rarity);modal.classList.remove('pa132-upgraded');void modal.offsetWidth;modal.classList.add('pa132-upgraded');render();setTimeout(()=>modal.classList.remove('pa132-upgraded'),850);onDone?.()}})};document.body.appendChild(modal);render();return true}
function collectionMarkup(){const instances=allInstances(),byId=new Map();for(const inst of instances){const list=byId.get(inst.artifactId)||[];list.push(inst);byId.set(inst.artifactId,list)}return DATA.artifacts.filter(raw=>qty(raw.id)>0).map(raw=>{const list=byId.get(raw.id)||[],count=Math.max(list.length,qty(raw.id)),best=[...list].sort((a,b)=>Number(b.upgradeLevel||0)-Number(a.upgradeLevel||0)||Number(a.acquiredAt||0)-Number(b.acquiredAt||0))[0],it=best?artifactOf(best.instanceId):raw,pv=best?A.getUpgradePreview?.(best.instanceId):null,maxed=!!pv&&pv.current>=pv.max,ready=!!pv?.canUpgrade,materialText=maxed?`MAX +${pv.max}`:pv?`${Math.min(pv.available,pv.need)}/${pv.need} bản +0`:'Đã khám phá';return `<article class="pa-art-card owned ${ready?'pa133-ready':''}"><div><img src="${esc(itemThumb(raw.asset))}" loading="lazy" decoding="async" alt="${esc(raw.name)}"></div>${rarityChip(raw.rarity)}<b>${esc(raw.name)} +${it?.upgradeLevel||0}</b><small>×${count} · ${materialText}</small>${pv&&!maxed?`<div class="pa133-upgrade-meter" title="Nguyên liệu +0 cho cấp kế tiếp"><i style="width:${Math.min(100,pv.need?pv.available/pv.need*100:100)}%"></i></div>`:''}${ready?'<em class="pa133-ready-badge">CÓ THỂ NÂNG</em>':''}${best?`<button class="pa126-card-upgrade" data-artifact-detail="${esc(best.instanceId)}">${maxed?'Xem':'Nâng cấp'}</button>`:''}</article>`}).join('')}
function mount(root){root=typeof root==='string'?document.querySelector(root):root;if(!root)return false;const rank=A.getRank?.()||0,rates=ratesForRank(rank),s=A.getSummon?.()||fallback.summon,tickets=Math.max(0,Math.floor(Number(A.getTickets?.())||0)),discovered=DATA.artifacts.filter(raw=>qty(raw.id)>0).length;root.classList.add('pa-artifact-module');root.innerHTML=`<section class="pa-hero"><div><small>CỔ VẬT · ${discovered} ĐÃ KHÁM PHÁ</small><h2>Triệu Hồi Cổ Vật</h2><p>Bản trùng cùng ArtifactID dùng để nâng cấp +X. Cổ vật +0 vẫn đầy đủ chức năng.</p></div><div class="pa-hero-count artifact-ticket-balance"><b>🎟️ ${tickets}</b><span>Vé Cổ Ấn</span></div></section><section class="pa-controls"><button class="pa-btn" data-summon="1" ${tickets<1?'disabled':''}>Dùng vé ×1</button><button class="pa-btn primary" data-summon="10" ${tickets<10?'disabled':''}>Dùng vé ×10</button></section><section class="pa126-upgrade-rules"><span>Thường <b>+1%</b></span><span>Hiếm <b>+2%</b></span><span>Siêu hiếm <b>+5%</b></span><span>Sử thi <b>+8%</b></span><span>Huyền thoại <b>+10%</b></span><span>Thần thoại <b>+20%</b></span><span>Thượng cổ <b>+30%</b></span></section><section class="pa-rates">${Object.entries(rates).map(([r,v])=>`<div>${rarityChip(r)}<b>${formatPct(v)}</b></div>`).join('')}</section><section class="pa-pity">${['super_rare','epic','legendary','mythic','ancient'].map(r=>{const unlocked=pityUnlocked(r,rank),max=Number(DATA.summon.pity?.[r]||0),now=Number(s.since?.[r]||0);return `<div class="${unlocked?'':'locked'}"><small>PITY ${esc(L[r])}</small><b>${unlocked?`${Math.max(1,max-now)} lượt`:'Đang khóa'}</b></div>`}).join('')}</section><section class="pa-collection">${collectionMarkup()}</section>`;root.querySelectorAll('[data-summon]').forEach(b=>b.onclick=()=>{summon(Number(b.dataset.summon));setTimeout(()=>mount(root),20)});root.querySelectorAll('[data-artifact-detail]').forEach(b=>b.onclick=()=>showUpgrade(b.dataset.artifactDetail,()=>mount(root)));return true}
const API={version:'13.4-artifact-progression-safe-batch',data:DATA,configure,artifactOf,getRates:ratesForRank,pityUnlocked,summon,showReveal,showUpgrade,mount,collectionMarkup,qty,equip,unequip,getEquipped,statProfile,applyStats,getState:()=>({owned:clone(A.getOwned?.()||{}),instances:clone(A.getInstances?.()||{}),equipped:clone(A.getEquipped?.()||{}),summon:clone(A.getSummon?.()||{})})};
window.POWDER_ARTIFACT_MODULE=API;
})();
