(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const online=()=>window.POWDER_ONLINE_V150,econ=()=>window.POWDER_SECURE_ECONOMY_V152,txsafe=()=>window.POWDER_TX_SAFETY_V2090,gateway=()=>window.POWDER_SERVER_MUTATION_V20110,rel=()=>window.POWDER_RELIABILITY_V2080;
const READ=new Set(['state','read_mail','read_announcement']);
const st={data:null,busy:false,tab:'mail',timer:0};
const cats={news:'Tin mới',event:'Sự kiện',maintenance:'Bảo trì',gift:'Quà tặng',update:'Cập nhật'};
function num(v){return new Intl.NumberFormat('vi-VN').format(Number(v)||0)}
function fmtTime(v){if(!v)return'';const d=new Date(v);return isNaN(d)?'':d.toLocaleString('vi-VN',{dateStyle:'short',timeStyle:'short'})}
function rewardText(r={}){const a=[];if(r.coins)a.push(`Coin ${num(r.coins)}`);if(r.knowledge)a.push(`Knowledge ${num(r.knowledge)}`);const cc=Number((r.powCandyCommon??r.powCandy)||0),cr=Number(r.powCandyRare||0),cl=Number(r.powCandyLegendary||0);if(cc)a.push(`Kẹo Thường ×${num(cc)}`);if(cr)a.push(`Kẹo Hiếm ×${num(cr)}`);if(cl)a.push(`Kẹo Huyền thoại ×${num(cl)}`);if(r.artifactTickets)a.push(`Vé Cổ Ấn ${num(r.artifactTickets)}`);if(r.elementCoin)a.push(`Tinh Tệ ${num(r.elementCoin)}`);const names={common:'Thường',rare:'Hiếm',super_rare:'Siêu hiếm',epic:'Sử thi',legendary:'Huyền thoại',mythic:'Thần thoại',ancient:'Thượng cổ'};for(const [k,v] of Object.entries(r.powballs||{}))if(Number(v)>0)a.push(`🔮 ${names[k]||k} ×${v}`);return a.join(' · ')||'Không có vật phẩm'}
async function raw(action,payload={}){if(!online()?.hasSession?.())throw new Error('Hãy đăng nhập Powder Online trước.');if(!READ.has(action)&&rel()?.canEconomyWrite?.()===false)throw new Error('Nhận quà đang tạm khóa để bảo vệ dữ liệu.');return online().request('/functions/v1/powder-liveops',{method:'POST',body:JSON.stringify({action,...payload,clientVersion:'20.15.0'})})}
async function mutate(action,payload={},dedupeKey='',stable=false){const canonicalAction=action==='claim_daily'?'claim_daily_login':action,scope=action==='claim_mail'?'mail':'reward';const send=txKey=>{const g=gateway();if(!g?.mutate)throw new Error('Canonical Mutation Gateway 20.14 chưa sẵn sàng.');return g.mutate({scope,action:canonicalAction,payload,txKey})};const T=txsafe();return T?.mutate?T.mutate({scope,operation:canonicalAction,payload,dedupeKey:dedupeKey||`${action}:${JSON.stringify(payload)}`,stable,send}):send('tx2090-liveops-'+Date.now().toString(36))}
function toast(t){let e=$('#liveopsToast156');if(!e){e=document.createElement('div');e.id='liveopsToast156';e.className='liveops-toast-156';document.body.appendChild(e)}e.textContent=t;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,2800)}
function ensureShell(){
 let btn=$('#liveopsBell156');if(!btn){btn=document.createElement('button');btn.id='liveopsBell156';btn.className='topbar-liveops-156';btn.type='button';btn.title='Hộp thư & sự kiện';btn.innerHTML='<span>✉️</span><i id="liveopsBadge156" hidden>0</i>';$('.topbar-gear')?.before(btn);btn.onclick=open}
 let modal=$('#liveopsModal156');if(!modal){modal=document.createElement('section');modal.id='liveopsModal156';modal.className='liveops-modal-156';modal.hidden=true;modal.innerHTML='<div class="liveops-backdrop-156" data-liveops-close></div><article class="liveops-card-156"><header><div><p class="eyebrow">POWDER ONLINE</p><h2>Trung tâm Online</h2></div><button data-liveops-close>×</button></header><nav id="liveopsTabs156"><button data-tab="mail">Hộp thư</button><button data-tab="daily">Đăng nhập</button><button data-tab="events">Sự kiện</button><button data-tab="news">Tin máy chủ</button></nav><div class="liveops-body-156" id="liveopsBody156"></div></article>';document.body.appendChild(modal);modal.querySelectorAll('[data-liveops-close]').forEach(b=>b.onclick=()=>modal.hidden=true);modal.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{st.tab=b.dataset.tab;renderModal()})}
 let home=$('#liveopsHome156');if(!home&&$('#playerJourneyHubV147')){home=document.createElement('section');home.id='liveopsHome156';home.className='liveops-home-156';$('#playerJourneyHubV147').after(home)}
}
function renderBadge(){ensureShell();const n=Number(st.data?.unread?.total||0);const b=$('#liveopsBadge156');if(b){b.textContent=n>99?'99+':String(n);b.hidden=!n}}
function renderNotice(){let bar=$('#liveopsNotice156');const s=st.data?.settings||{};if(!s.maintenance_notice&&!s.motd){bar?.remove();return}if(!bar){bar=document.createElement('div');bar.id='liveopsNotice156';bar.className='liveops-notice-156';$('.topbar')?.after(bar)}bar.innerHTML=`<b>${s.maintenance_notice?'🛠 Thông báo máy chủ':'📢 Tin nhanh'}</b><span>${esc(s.maintenance_notice?s.maintenance_message:s.motd)}</span>${s.maintenance_until?`<small>Đến ${esc(fmtTime(s.maintenance_until))}</small>`:''}`}
function renderHome(){ensureShell();const root=$('#liveopsHome156');if(!root)return;if(!online()?.hasSession?.()){root.innerHTML='';root.hidden=true;return}root.hidden=false;if(!st.data){root.innerHTML='<article><b>🌐 Powder Online</b><span>Đang tải dịch vụ máy chủ...</span></article>';return}const d=st.data,daily=d.daily||{},event=(d.events||[])[0],unread=d.unread?.mail||0;root.innerHTML=`<article class="liveops-home-card-156"><div><small>ĐĂNG NHẬP HẰNG NGÀY</small><b>${daily.claimedToday?'✅ Đã nhận quà hôm nay':`🎁 Quà ngày ${daily.nextDay}/7 đang chờ`}</b><span>Chuỗi hiện tại: ${num(daily.streak||0)} ngày</span></div><button data-liveops-home="daily">${daily.claimedToday?'Xem lịch quà':'Nhận quà'}</button></article><article class="liveops-home-card-156"><div><small>HỘP THƯ</small><b>✉️ ${unread?`${unread} thư chưa đọc`:'Không có thư mới'}</b><span>Quà và thông báo được đồng bộ giữa các thiết bị.</span></div><button data-liveops-home="mail">Mở thư</button></article>${event?`<article class="liveops-home-card-156 event"><div><small>${esc(event.payload?.badge||'LIVE EVENT')}</small><b>✨ ${esc(event.title)}</b><span>${esc(event.description||'')}</span></div><button data-liveops-home="events">Chi tiết</button></article>`:''}`;root.querySelectorAll('[data-liveops-home]').forEach(b=>b.onclick=()=>{st.tab=b.dataset.liveopsHome;open()})}
function renderMail(){const mails=st.data?.mail||[];return `<div class="liveops-title-156"><div><small>SERVER MAIL</small><h3>Hộp thư Tamer</h3></div><span>${mails.filter(x=>!x.read).length} chưa đọc</span></div><div class="liveops-list-156">${mails.length?mails.map(m=>`<article class="liveops-mail-156 ${m.read?'':'unread'}"><div class="liveops-mail-icon-156">${m.claimed?'✅':m.audience==='all'?'📨':'✉️'}</div><div><small>${m.audience==='all'?'Thư toàn máy chủ':'Thư riêng'} · ${esc(fmtTime(m.created_at))}</small><h3>${esc(m.title)}</h3><p>${esc(m.body)}</p><div class="liveops-reward-156">${esc(rewardText(m.rewards))}</div>${m.expires_at?`<em>Hết hạn: ${esc(fmtTime(m.expires_at))}</em>`:''}</div><div class="liveops-actions-156"><button data-mail-read="${esc(m.id)}">${m.read?'Đã đọc':'Đọc'}</button>${Object.keys(m.rewards||{}).length?`<button class="primary" data-mail-claim="${esc(m.id)}" ${m.claimed?'disabled':''}>${m.claimed?'Đã nhận':'Nhận quà'}</button>`:''}</div></article>`).join(''):'<div class="liveops-empty-156">Hộp thư đang trống.</div>'}</div>`}
function renderDaily(){const d=st.data?.daily||{},items=d.rewards||[];return `<div class="liveops-title-156"><div><small>DAILY LOGIN</small><h3>Chuỗi đăng nhập 7 ngày</h3></div><span>${num(d.streak||0)} ngày liên tiếp</span></div><div class="liveops-daily-grid-156">${items.map(x=>`<article class="${x.day===d.nextDay&&!d.claimedToday?'next':''}"><small>NGÀY ${x.day}</small><b>${esc(rewardText(x.rewards))}</b>${x.day===d.nextDay&&!d.claimedToday?'<span>Sẵn sàng nhận</span>':''}</article>`).join('')}</div><div class="liveops-daily-claim-156"><div><b>${d.claimedToday?'Hôm nay đã nhận quà':'Quà hôm nay đang chờ bạn'}</b><p>Phần Coin và một số mốc thưởng tăng theo Rank Tamer. Mất chuỗi sẽ quay lại ngày 1.</p></div><button class="btn primary" id="liveopsClaimDaily156" ${d.claimedToday?'disabled':''}>${d.claimedToday?'Đã nhận':'Nhận quà hôm nay'}</button></div>`}
function renderEvents(){const es=st.data?.events||[];return `<div class="liveops-title-156"><div><small>LIVE EVENTS</small><h3>Sự kiện đang diễn ra</h3></div><span>${es.length} sự kiện</span></div><div class="liveops-event-grid-156">${es.length?es.map(e=>`<article><span>${esc(e.payload?.badge||'LIVE')}</span><h3>${esc(e.title)}</h3><p>${esc(e.description||'')}</p><small>${esc(fmtTime(e.starts_at))} → ${esc(fmtTime(e.ends_at))}</small></article>`).join(''):'<div class="liveops-empty-156">Hiện chưa có sự kiện đang diễn ra.</div>'}</div>`}
function renderNews(){const ns=st.data?.announcements||[];return `<div class="liveops-title-156"><div><small>SERVER NEWS</small><h3>Thông báo máy chủ</h3></div><span>${ns.filter(x=>!x.read).length} mới</span></div><div class="liveops-list-156">${ns.length?ns.map(n=>`<article class="liveops-news-156 ${n.read?'':'unread'}" data-ann-read="${n.id}"><div><span>${esc(cats[n.category]||n.category)}</span><small>${esc(fmtTime(n.created_at))}</small></div><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></article>`).join(''):'<div class="liveops-empty-156">Chưa có thông báo mới.</div>'}</div>`}
function renderModal(){ensureShell();const body=$('#liveopsBody156');if(!body)return;$('#liveopsTabs156').querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===st.tab));if(!online()?.hasSession?.()){body.innerHTML='<div class="liveops-empty-156"><h3>Chưa đăng nhập Powder Online</h3><p>Đăng nhập để nhận thư, quà hằng ngày và sự kiện máy chủ.</p><button class="btn primary" id="liveopsLogin156">Đăng nhập</button></div>';$('#liveopsLogin156')?.addEventListener('click',()=>online()?.open?.());return}if(!st.data){body.innerHTML='<div class="liveops-empty-156">Đang tải dữ liệu máy chủ...</div>';return}body.innerHTML=st.tab==='daily'?renderDaily():st.tab==='events'?renderEvents():st.tab==='news'?renderNews():renderMail();bindBody()}
function bindBody(){document.querySelectorAll('[data-mail-read]').forEach(b=>b.onclick=async()=>{try{await raw('read_mail',{campaignId:b.dataset.mailRead});const m=st.data.mail.find(x=>x.id===b.dataset.mailRead);if(m)m.read=true;renderAll()}catch(e){toast(e.message)}});document.querySelectorAll('[data-mail-claim]').forEach(b=>b.onclick=()=>claimMail(b.dataset.mailClaim));document.querySelectorAll('[data-ann-read]').forEach(b=>b.onclick=async()=>{try{await raw('read_announcement',{announcementId:Number(b.dataset.annRead)});const n=st.data.announcements.find(x=>String(x.id)===String(b.dataset.annRead));if(n)n.read=true;renderAll()}catch{}});$('#liveopsClaimDaily156')?.addEventListener('click',claimDaily)}
async function claimMail(id){try{const d=await mutate('claim_mail',{campaignId:id},`mail:${id}`,true);st.data=d.state;await econ()?.syncState?.({save:true});toast('Đã nhận quà trong thư.');renderAll()}catch(e){toast(e.message)}}
async function claimDaily(){try{const day=new Date().toISOString().slice(0,10),d=await mutate('claim_daily',{},`daily-login:${day}`,true);st.data=d.state;await econ()?.syncState?.({save:true});toast(`Đã nhận quà đăng nhập ngày ${d.result?.cycleDay||''}.`);renderAll()}catch(e){toast(e.message)}}
function renderAll(){renderBadge();renderNotice();renderHome();if(!$('#liveopsModal156')?.hidden)renderModal()}
async function load(force=false){ensureShell();if(!online()?.hasSession?.()){st.data=null;renderAll();return}if(st.busy&&!force)return;st.busy=true;try{const d=await raw('state');st.data=d.state;renderAll()}catch(e){console.warn('[Powder LiveOps]',e);renderAll()}finally{st.busy=false}}
function open(){ensureShell();$('#liveopsModal156').hidden=false;renderModal();load(true)}
function canRefresh(){const v=document.body?.dataset?.activeView||'';return !document.hidden&&navigator.onLine!==false&&online()?.hasSession?.()&&v!=='battle'&&v!=='chests'&&v!=='settings'}
function scheduleRefresh(delay=180000){clearTimeout(st.timer);st.timer=0;if(!canRefresh())return;st.timer=setTimeout(async()=>{st.timer=0;if(canRefresh())await load();scheduleRefresh()},Math.max(30000,delay))}
function boot(){ensureShell();load();window.addEventListener('powder:online-login',()=>{setTimeout(()=>load(true),400);scheduleRefresh(15000)});window.addEventListener('online',()=>{load(true);scheduleRefresh(15000)});window.addEventListener('offline',()=>{clearTimeout(st.timer);st.timer=0},{passive:true});window.addEventListener('powder:view-changed',()=>scheduleRefresh(),{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&document.body?.dataset?.activeView!=='settings'){load();scheduleRefresh()}else{clearTimeout(st.timer);st.timer=0}},{passive:true});scheduleRefresh()}
window.POWDER_LIVEOPS_V156={version:'15.6',load,open,state:()=>st.data};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
