(()=>{'use strict';
const EDGE_VERSION='20.2.0',VERSION=String(window.POWDER_CONFIG?.appVersion||window.POWDER_ENV_V162?.version||'20.4.0'),BUILD=String(window.POWDER_ENV_V162?.buildId||'powder-20.4.0-disaster-recovery-backup-integrity'),MAX=120,FLUSH_MS=300000,MARK='powder_obs2020_session';
let active=false,origFetch=null,timer=0,heartbeat=0,samples=[],runtimeErrors=0,suspectedCrashes=0,reconnects=0,saveConflicts=0,lastFlush=0;
const release=()=>window.POWDER_RELEASE_V162?.manifest?.()||null,online=()=>window.POWDER_ONLINE_V150,combat=()=>!!window.POWDER_COMBAT_ENTRY_V177?.isActive?.();
function device(){try{return localStorage.getItem('powder_device_v150')||online()?.state?.().device||''}catch{return''}}
function bucket(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)%10000}
function session(){try{return online()?.session?.()||null}catch{return null}}
function config(){const m=release(),o=m?.observability||{};return{enabled:o.enabled===true,rate:Math.max(0,Math.min(1,Number(o.sampleRate||0))),salt:String(o.sampleSalt||'powder-observability-v2020'),rollout:Number(m?.rolloutPercent??100),channel:window.POWDER_RELEASE_V162?.channel||'production'}}
function eligible(){const c=config(),d=device();return c.enabled&&!!d&&bucket(`${d}|${c.salt}`)<Math.floor(c.rate*10000)}
function endpoint(u){try{const m=new URL(u,location.href).pathname.match(/\/functions\/v1\/(powder-[a-z0-9-]+)/i);return m?.[1]?.toLowerCase()||''}catch{return''}}
function network(){return String(navigator.connection?.effectiveType||'').slice(0,24)}
function push(x){if(samples.length>=MAX)samples.splice(0,samples.length-MAX+1);samples.push(x)}
function mark(clean=false){try{localStorage.setItem(MARK,JSON.stringify({version:VERSION,clean,at:Date.now()}))}catch{}}
function initCrashMarker(){try{const p=JSON.parse(localStorage.getItem(MARK)||'null');if(p&&!p.clean&&Date.now()-Number(p.at||0)<10*60*1000)suspectedCrashes++}catch{}mark(false);heartbeat=setInterval(()=>mark(false),60000);window.addEventListener('pagehide',()=>mark(true),{capture:false});window.addEventListener('beforeunload',()=>mark(true),{capture:false})}
async function flush(force=false){if(!active||combat()||document.hidden&&!force)return false;const s=session();if(!s?.access_token)return false;if(!samples.length&&!runtimeErrors&&!suspectedCrashes&&!reconnects&&!saveConflicts)return true;const c=config(),batch=samples.splice(0,80),payload={channel:c.channel,buildId:BUILD,appVersion:VERSION,deviceId:device(),rolloutPercent:c.rollout,networkType:network(),samples:batch,health:{runtimeErrors,suspectedCrashes,reconnects,saveConflicts}};try{const cfg=JSON.parse(localStorage.getItem('powder_online_server_v150')||'null')||{},url=String(cfg.url||'https://pxejydhqfzidnheudgnn.supabase.co').replace(/\/$/,''),key=String(cfg.key||'sb_publishable_EeppsefEV5sMaTcHrKWNCA_-dzAEA_H');const r=await origFetch(url+'/functions/v1/powder-observability',{method:'POST',headers:{apikey:key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json','x-powder-device':device(),'x-powder-version':VERSION},body:JSON.stringify(payload),cache:'no-store'});if(!r.ok){samples.unshift(...batch);if(samples.length>MAX)samples=samples.slice(-MAX);return false}runtimeErrors=0;suspectedCrashes=0;reconnects=0;saveConflicts=0;lastFlush=Date.now();return true}catch{samples.unshift(...batch);if(samples.length>MAX)samples=samples.slice(-MAX);return false}}
function install(){if(active||!eligible()||!session()?.access_token)return false;active=true;origFetch=window.fetch.bind(window);window.fetch=async function(input,init){let u='';try{u=typeof input==='string'?input:input.url}catch{}const ep=endpoint(u);if(!ep||ep==='powder-observability')return origFetch(input,init);const t=performance.now();try{const r=await origFetch(input,init),ms=Math.max(0,Math.min(120000,Math.round(performance.now()-t)));push({endpoint:ep,status:r.status,latencyMs:ms,ok:r.ok});if(ep==='powder-cloud'&&r.status===409)saveConflicts++;return r}catch(e){push({endpoint:ep,status:0,latencyMs:Math.max(0,Math.min(120000,Math.round(performance.now()-t))),ok:false});throw e}};window.addEventListener('error',()=>runtimeErrors++);window.addEventListener('unhandledrejection',()=>runtimeErrors++);window.addEventListener('powder:app-boot-error',()=>runtimeErrors++);window.addEventListener('powder:network-reconnected',()=>reconnects++);initCrashMarker();timer=setInterval(()=>flush(false),FLUSH_MS);return true}
function maybe(){if(active)return;install()}
function startFromManifest(){const c=config();if(!c.enabled)return false;if(session()?.access_token)maybe();else window.addEventListener('powder:online-login',()=>setTimeout(maybe,300),{once:true});return true}
function boot(){if(release()){startFromManifest();return}const onManifest=()=>{clearTimeout(wait);startFromManifest()};window.addEventListener('powder:release-manifest',onManifest,{once:true});const wait=setTimeout(()=>{window.removeEventListener('powder:release-manifest',onManifest)},8000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.POWDER_OBSERVABILITY_V2020={version:VERSION,active:()=>active,eligible,flush:()=>flush(true),state:()=>({active,queued:samples.length,runtimeErrors,suspectedCrashes,reconnects,saveConflicts,lastFlush,config:config()})};
})();
