(()=>{
  'use strict';
  const KEY='powder_onboarding_v146',VERSION='21.1.1';
  const MIN_READ_MS=1000,FIRST_READ_MS=1300,TRANSITION_MS=260,TARGET_WAIT_TRIES=10,TARGET_WAIT_MS=80;
  const $=s=>document.querySelector(s);
  const state=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return{}}};
  const save=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(_){}};

  let index=0,layer=null,focus=null,card=null,masks=[],currentTarget=null;
  let running=false,autoTimer=0,renderToken=0,resizeRaf=0,unlockTimer=0,transitionTimer=0,nextLocked=false;

  const steps=[
    {icon:'✨',title:'Chào mừng đến Powder',body:'Powder kết hợp học ngôn ngữ với nuôi Pow. Học tốt giúp đội hình mạnh lên, còn Pow biến việc học thành một hành trình có mục tiêu.',note:'Vòng lặp đầu tiên: học bài đầu → làm kiểm tra → xem Pow nhận EXP.',view:'home',read:1300},
    {icon:'🧭',title:'Căn cứ dẫn đường cho bạn',body:'Hành trình hôm nay tự xem tiến độ và gợi ý việc nên làm tiếp: học Trung, học Anh, ôn SRS, đi Boss hoặc Phiêu lưu.',note:'“Tiếp tục hành trình” chỉ là gợi ý. Bạn luôn có thể chọn hoạt động khác.',view:'home',target:'#powderJourney2110, #playerJourneyHubV147'},
    {icon:'🔥',title:'Pow chính của bạn',body:'Đây là Pow đang đồng hành. Pow lên Level bằng Pow EXP từ học bài, ôn tập, chiến đấu hoặc PowCandy.',note:'Level Pow và Rank Tamer là hai tiến trình riêng.',view:'home',target:'.active-pow-panel'},
    {icon:'📚',title:'Học viện là con đường chính',body:'Vào Học để học HSK và English. Bài mới cho phần thưởng chính; câu kiểm tra luôn có đáp án đúng và giải thích sau khi trả lời.',note:'Người mới nên bắt đầu HSK1 rồi học phần English nền của Rank hiện tại.',view:'learn',target:'#learnView .learning-hub-v149, #learnView .section-title, #learnView .lesson-grid'},
    {icon:'🧠',title:'SRS và Adaptive giúp nhớ lâu',body:'Những câu bạn yếu sẽ quay lại đúng thời điểm. Adaptive Learning ưu tiên concept yếu thay vì bắt bạn ôn ngẫu nhiên.',note:'Sai không phải mất tiến độ: câu sai trở thành dữ liệu để hệ thống tạo lịch ôn tốt hơn.',view:'learn',target:'#adaptive172Panel, #srs166Panel, #learnView .learning-mastery-dashboard'},
    {icon:'⚡',title:'Điện Cường Hóa',body:'Đây là nơi phát triển Level, sao và theo dõi bộ kỹ năng riêng của từng Pow.',note:'Nâng sao không đổi bộ kỹ năng của Pow; nó làm chính bộ kỹ năng đó mạnh và đặc trưng hơn.',view:'gear',target:'#gearView .ph-title, #gearView .ph-hero, #gearView .ph-progress-card'},
    {icon:'🔮',title:'PowBall để nhận Pow mới',body:'PowBall có nhiều bậc với pool, tỷ lệ và bảo chứng riêng. Pow đặc biệt vẫn có thể xuất hiện nhưng hiếm hơn Pow thông thường.',note:'Tất cả 99 Pow đều có con đường sở hữu; không cần học chiêu của Pow khác.',view:'chests',target:'#chestsView .pb142-hero, #chestsView .section-title, #chestsView .panel'},
    {icon:'📖',title:'Powdex là sổ tay 99 Pow',body:'Powdex giúp xem toàn bộ Pow, phẩm chất, hệ và những Pow bạn đã sở hữu.',note:'Dùng bộ lọc để tìm Pow phù hợp đội hình thay vì chỉ chọn theo phẩm chất.',view:'powdex',target:'#powdexView .section-title, #powdexView #rarityFilters'},
    {icon:'🗺️',title:'Phiêu lưu để vận dụng kiến thức',body:'Phiêu lưu dùng kiến thức bạn đã học làm điều kiện tiến tới các màn và thử thách tiếp theo.',note:'Màn chưa mở sẽ chỉ rõ yêu cầu học tập cần hoàn thành.',view:'adventure',target:'#adventureView .world-section-title, #adventureView .world-view-switch'},
    {icon:'👑',title:'Boss là bài kiểm tra tổng hợp',body:'Boss ngày, Boss tuần và Boss thăng Rank kiểm tra kiến thức đã học với mức khó và phần thưởng khác nhau.',note:'Boss không phải nơi ném vào kiến thức chưa từng học.',view:'boss',target:'#bossView .section-title, #bossView .world-view-switch, #bossView .panel'},
    {icon:'🏅',title:'Tamer Rank là hành trình học',body:'Rank phản ánh tiến độ tổng thể: học đủ nội dung, đạt Mastery, thi thăng hạng và vượt Boss để sang bậc tiếp theo.',note:'Pow Level tăng sức mạnh Pow; Tamer Rank mở rộng hành trình của chính người chơi.',view:'tamer',target:'#tamerView .tm142-header, #tamerNextActionV147, #tamerPromotionProgress'},
    {icon:'🌐',title:'Cộng đồng Powder',body:'Cộng đồng cho phép tìm Tamer bằng UID, kết bạn, xem trạng thái Online và hồ sơ trưng bày.',note:'Giao diện Cộng đồng phải mở ngay; dữ liệu Online sẽ tải sau để không làm bạn chờ ở màn hình trống.',view:'social',target:'#socialHubV154'},
    {icon:'✉️',title:'Hộp thư và sự kiện Online',body:'Quà bảo trì, bồi thường, đăng nhập và sự kiện được quản lý từ server. Mỗi phần thưởng chỉ nhận một lần.',note:'Biểu tượng ✉️ trên thanh trên cùng mở Trung tâm Online khi hệ thống đã sẵn sàng.',view:'home',target:'#liveopsBell156'},
    {icon:'⚙️',title:'Cài đặt và hỗ trợ',body:'Bạn có thể chỉnh hiệu năng, âm thanh, reduced motion, tài khoản, Cloud Save và mở lại hướng dẫn này bất cứ lúc nào.',note:'Nếu máy yếu, ưu tiên chế độ hiệu năng và Reduced Motion trước khi giảm chất lượng nội dung.',view:'settings',target:'#settingsView .settings-header-v140, #guideSettingsV146'},
    {icon:'🚀',title:'Bạn đã sẵn sàng',body:'Không cần nhớ mọi hệ thống ngay. Chỉ cần nhớ vòng lặp: Học → Pow mạnh lên → Phiêu lưu → mở nội dung mới → quay lại học.',note:'Nút ? luôn mở lại hướng dẫn cơ bản này.',view:'home',read:1200}
  ];

  const FULL_STEPS=steps.slice(),QUICK_STEP_INDEXES=[0,1,3,8,14],QUICK_STEPS=QUICK_STEP_INDEXES.map(i=>FULL_STEPS[i]);let quickMode=false;
  const applyMode=mode=>{quickMode=mode==='quick';const source=quickMode?QUICK_STEPS:FULL_STEPS;steps.splice(0,steps.length,...source)};
  const showView=name=>{try{window.POWDER_APP?.showView?.(name)}catch(_){}};
  const clearTimer=(id)=>{if(id)clearTimeout(id);return 0};
  function clearTarget(){currentTarget=null}
  function setMask(el,rect){if(!el)return;el.style.left=`${rect.left}px`;el.style.top=`${rect.top}px`;el.style.width=`${Math.max(0,rect.width)}px`;el.style.height=`${Math.max(0,rect.height)}px`}
  function maskAll(){const w=innerWidth,h=innerHeight;setMask(masks[0],{left:0,top:0,width:w,height:h});for(let i=1;i<4;i++)setMask(masks[i],{left:0,top:0,width:0,height:0})}
  function maskAround(r,pad=10){const w=innerWidth,h=innerHeight,l=Math.max(0,Math.min(w,r.left-pad)),t=Math.max(0,Math.min(h,r.top-pad)),rr=Math.max(l,Math.min(w,r.right+pad)),bb=Math.max(t,Math.min(h,r.bottom+pad));setMask(masks[0],{left:0,top:0,width:w,height:t});setMask(masks[1],{left:0,top:t,width:l,height:bb-t});setMask(masks[2],{left:rr,top:t,width:w-rr,height:bb-t});setMask(masks[3],{left:0,top:bb,width:w,height:h-bb});return{left:l,top:t,right:rr,bottom:bb,width:rr-l,height:bb-t}}
  function close(mark=true){autoTimer=clearTimer(autoTimer);unlockTimer=clearTimer(unlockTimer);transitionTimer=clearTimer(transitionTimer);renderToken++;clearTarget();layer?.remove();layer=focus=card=null;masks=[];running=false;nextLocked=false;document.documentElement.classList.remove('onboarding-open','onboarding-switching');if(mark){const s=state();s.seen=true;s.completed=s.completed||index>=steps.length-1;s.last=index;s.at=Date.now();s.version=VERSION;save(s)}}
  function findTarget(step){const candidates=(step.target||'').split(',').map(x=>x.trim()).filter(Boolean);return candidates.map(s=>$(s)).find(el=>el&&el.offsetParent!==null)||null}
  function position(step){if(!running||!layer||!card)return false;clearTarget();currentTarget=findTarget(step);if(!currentTarget){focus.hidden=true;maskAll();card.classList.add('is-center');card.style.left='50%';card.style.top='50%';card.style.right='auto';card.style.bottom='auto';return false}currentTarget.scrollIntoView({block:'center',inline:'nearest',behavior:'auto'});const r=currentTarget.getBoundingClientRect();if(!Number.isFinite(r.width)||r.width<2||r.height<2){focus.hidden=true;maskAll();card.classList.add('is-center');return false}const pad=8,hole=maskAround(r,pad);focus.hidden=false;focus.style.left=`${r.left-pad}px`;focus.style.top=`${r.top-pad}px`;focus.style.width=`${Math.max(0,r.width+pad*2)}px`;focus.style.height=`${Math.max(0,r.height+pad*2)}px`;card.classList.remove('is-center');const cw=Math.min(430,innerWidth-28),ch=Math.min(card.offsetHeight||350,innerHeight-28),gap=16;let left=hole.right+gap,top=Math.max(14,Math.min(innerHeight-ch-14,hole.top));if(left+cw>innerWidth-14)left=hole.left-cw-gap;if(left<14){left=Math.max(14,(innerWidth-cw)/2);top=hole.bottom+gap;if(top+ch>innerHeight-14)top=Math.max(14,hole.top-ch-gap)}card.style.left=`${Math.round(left)}px`;card.style.top=`${Math.round(top)}px`;card.style.right='auto';card.style.bottom='auto';return true}
  function waitForTarget(step,token,tries=0){if(!running||token!==renderToken)return;if(position(step)||tries>=TARGET_WAIT_TRIES)return;setTimeout(()=>waitForTarget(step,token,tries+1),TARGET_WAIT_MS)}
  function unlockNext(step,token){unlockTimer=clearTimer(unlockTimer);nextLocked=true;const btn=card?.querySelector('.onboarding-next');if(btn){btn.disabled=true;btn.dataset.ready='0';btn.textContent='Đọc hướng dẫn…'}const ms=Math.max(700,Number(step.read)|| (index===0?FIRST_READ_MS:MIN_READ_MS));unlockTimer=setTimeout(()=>{if(!running||token!==renderToken)return;nextLocked=false;const b=card?.querySelector('.onboarding-next');if(b){b.disabled=false;b.dataset.ready='1';b.textContent=index===steps.length-1?'Bắt đầu hành trình':'Tiếp tục'}},ms)}
  function goTo(nextIndex){if(!running||transitionTimer)return;nextLocked=true;document.documentElement.classList.add('onboarding-switching');transitionTimer=setTimeout(()=>{transitionTimer=0;document.documentElement.classList.remove('onboarding-switching');index=Math.max(0,Math.min(steps.length-1,nextIndex));render()},TRANSITION_MS)}
  function render(){if(!running||!card)return;const token=++renderToken,step=steps[index];unlockTimer=clearTimer(unlockTimer);showView(step.view);card.innerHTML=`<div class="onboarding-top"><span class="onboarding-progress">Hướng dẫn ${index+1}/${steps.length}</span><button class="onboarding-close" type="button" aria-label="Đóng">×</button></div><div class="onboarding-icon">${step.icon}</div><h2>${step.title}</h2><p>${step.body}</p><div class="onboarding-callout">${step.note}</div><div class="onboarding-dots">${steps.map((_,i)=>`<i class="${i===index?'is-active':''}"></i>`).join('')}</div><div class="onboarding-actions"><button class="onboarding-skip" type="button">Bỏ qua</button>${index?'<button class="onboarding-back" type="button">Quay lại</button>':''}<button class="onboarding-next" type="button" disabled>Đọc hướng dẫn…</button></div>`;card.querySelector('.onboarding-close').onclick=()=>close(true);card.querySelector('.onboarding-skip').onclick=()=>{const s=state();s.seen=true;s.skipped=true;s.last=index;s.version=VERSION;save(s);close(false)};card.querySelector('.onboarding-back')?.addEventListener('click',()=>goTo(index-1));card.querySelector('.onboarding-next').onclick=()=>{if(nextLocked)return;if(index>=steps.length-1){const s=state();s.seen=true;s.completed=true;s.last=index;s.version=VERSION;save(s);close(false);showView('home')}else goTo(index+1)};maskAll();focus.hidden=true;requestAnimationFrame(()=>requestAnimationFrame(()=>waitForTarget(step,token)));unlockNext(step,token);window.dispatchEvent(new CustomEvent('powder:onboarding-step',{detail:{index,total:steps.length,view:step.view,title:step.title}}))}
  function start(from=0,mode='full'){autoTimer=clearTimer(autoTimer);applyMode(mode);index=Math.max(0,Math.min(steps.length-1,Number(from)||0));if(running&&layer){render();return}running=true;document.documentElement.classList.add('onboarding-open');layer=document.createElement('div');layer.className='onboarding-layer';layer.innerHTML='<div class="onboarding-mask mask-top"></div><div class="onboarding-mask mask-left"></div><div class="onboarding-mask mask-right"></div><div class="onboarding-mask mask-bottom"></div><div class="onboarding-focus"></div><article class="onboarding-card"></article>';document.body.appendChild(layer);masks=[...layer.querySelectorAll('.onboarding-mask')];focus=layer.querySelector('.onboarding-focus');card=layer.querySelector('.onboarding-card');maskAll();render()}
  function installHelp(){if(!$('.onboarding-help-btn')){const b=document.createElement('button');b.className='onboarding-help-btn';b.type='button';b.title='Hướng dẫn người mới';b.setAttribute('aria-label','Hướng dẫn người mới');b.textContent='?';b.onclick=()=>start(0);document.body.appendChild(b)}}
  function installSettings(){const grid=$('#settingsView .settings-dashboard-v140');if(!grid||$('#guideSettingsV146'))return;const a=document.createElement('article');a.id='guideSettingsV146';a.className='panel settings-card-v140 guide-settings-v146';a.innerHTML=`<div class="settings-card-head-v140"><span class="settings-card-icon-v140">🧭</span><div><p class="eyebrow">HƯỚNG DẪN</p><h2>Hướng dẫn người mới</h2></div></div><p class="muted">Xem lại hướng dẫn cơ bản: học tập, SRS, Pow, PowBall, Phiêu lưu, Boss, Tamer, Cộng đồng và tài khoản.</p><div class="guide-settings-list-v146"><div><b>📚 Học</b><small>HSK · English · SRS</small></div><div><b>⚡ Nuôi Pow</b><small>Level · Sao · Build</small></div><div><b>🗺️ Hành trình</b><small>Phiêu lưu · Boss · Rank</small></div><div><b>🌐 Online</b><small>Bạn bè · Thư · Cloud</small></div></div><div class="guide-settings-actions-v146"><button class="btn primary" id="restartGuideV146" type="button">▶ Xem hướng dẫn từ đầu</button><button class="btn secondary" id="resetGuideV146" type="button">↺ Hiện lại cho người mới</button></div>`;grid.prepend(a);a.querySelector('#restartGuideV146').onclick=()=>start(0);a.querySelector('#resetGuideV146').onclick=()=>{localStorage.removeItem(KEY);start(0)}}
  function maybeAutoStart(){if(running||autoTimer||state().seen)return;const saveData=window.POWDER_APP?.getSave?.();if(!saveData?.starterId)return;const isNew=(saveData.rank||0)===0&&(saveData.wins||0)===0&&(saveData.lessonsDone||[]).length===0;if(!isNew)return;autoTimer=setTimeout(()=>{autoTimer=0;if(!running&&!state().seen)start(0,'quick')},650)}
  function boot(){installHelp();installSettings();const setup=$('#setupScreen'),app=$('#app');if(window.MutationObserver&&(setup||app)){const obs=new MutationObserver(()=>{if(!running)maybeAutoStart()});if(setup)obs.observe(setup,{attributes:true,attributeFilter:['hidden']});if(app)obs.observe(app,{attributes:true,attributeFilter:['hidden']})}document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="settings"],[data-open-view="settings"]'))setTimeout(installSettings,0)},{passive:true});setTimeout(maybeAutoStart,900);addEventListener('resize',()=>{if(!running||resizeRaf)return;resizeRaf=requestAnimationFrame(()=>{resizeRaf=0;if(running)position(steps[index])})},{passive:true});window.POWDER_ONBOARDING_V146={version:VERSION,start,reset:()=>{localStorage.removeItem(KEY);start(0)},state,isRunning:()=>running,steps:()=>FULL_STEPS.map(x=>({title:x.title,view:x.view})),flowSteps:()=>steps.map(x=>({title:x.title,view:x.view})),mode:()=>quickMode?'quick':'full'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
