(()=>{'use strict';
const root=document.documentElement;
let tier='full',fps=60,last=0,frames=[],raf=0,sampleTimer=0,priorityTimer=0,priorityIdle=0,lowWindows=0,goodWindows=0,sampling=false;
function getSave(){try{return window.POWDER_APP?.getSave?.()||null}catch(_){return null}}
function prefs(){const s=getSave()?.settings||{},coarse=matchMedia?.('(pointer:coarse)')?.matches||false,w=innerWidth||1200,mem=Number(navigator.deviceMemory||8),cores=Number(navigator.hardwareConcurrency||8),profile=['quality','balanced','performance'].includes(s.performanceProfile)?s.performanceProfile:(s.performanceLite===false?'quality':'balanced');return{profile,prefer:profile!=='quality',weak:coarse||w<=760||mem<=4||cores<=4,reduced:!!s.reducedMotion}}
function apply(next,reason='auto'){if(!['full','balanced','low'].includes(next))next='balanced';if(tier===next&&root.dataset.perfReason===reason)return;tier=next;root.classList.toggle('perf-lite',tier!=='full');root.classList.toggle('perf-degraded',tier!=='full');root.classList.toggle('perf-critical',tier==='low');root.dataset.perfMode=tier;root.dataset.perfReason=reason;try{window.dispatchEvent(new CustomEvent('powder:performance-tier',{detail:{tier,fps,reason}}))}catch(_){}}
function detect(){const p=prefs();root.dataset.performanceProfile=p.profile;if(p.reduced)return apply('low','reduced-motion');if(p.profile==='performance')return apply('low','profile');if(p.profile==='balanced')return apply('balanced','profile');if(p.weak&&tier==='full')return apply('balanced','device');if(p.profile==='quality'&&root.dataset.perfReason==='profile')return apply('full','profile')}
function evaluate(){if(frames.length<24)return;const sorted=frames.slice().sort((a,b)=>a-b),avg=frames.reduce((a,b)=>a+b,0)/frames.length,p90=sorted[Math.min(sorted.length-1,Math.floor(sorted.length*.9))]||avg;fps=Math.max(1,Math.min(120,1000/avg));root.dataset.fps=Math.round(fps);const p=prefs();if(p.reduced){lowWindows=goodWindows=0;apply('low','reduced-motion')}else if(fps<42||p90>29){lowWindows++;goodWindows=0;if(lowWindows>=2)apply('low','fps')}else if(fps<54||p90>22){lowWindows++;goodWindows=0;if(tier==='full'||lowWindows>=2)apply('balanced','fps')}else if(fps>=57&&p90<19){goodWindows++;lowWindows=Math.max(0,lowWindows-1);if(goodWindows>=3){if(tier==='low')apply('balanced','recovery');else if(tier==='balanced'&&!p.weak&&p.profile==='quality')apply('full','recovery');goodWindows=0}}else{lowWindows=Math.max(0,lowWindows-1);goodWindows=0}}
function frame(now){raf=0;if(document.hidden||!sampling)return;if(last){const dt=now-last;if(dt>0&&dt<250)frames.push(dt)}last=now;if(frames.length>=72){sampling=false;evaluate();scheduleSample();return}raf=requestAnimationFrame(frame)}
function scheduleSample(delay){clearTimeout(sampleTimer);if(document.hidden)return;const active=document.body?.dataset?.activeView||'';sampleTimer=setTimeout(startSample,delay??(active==='battle'||active==='chests'?4500:11000))}
function startSample(){if(document.hidden||sampling)return;sampling=true;frames.length=0;last=0;if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}
function prioritize(){priorityTimer=0;const active=document.querySelector('.view:not([hidden]),#setupScreen:not([hidden])');if(!active)return;const ir=window.POWDER_IMAGE_RUNTIME_V1826;if(ir?.prioritize){ir.prioritize(active);return}const imgs=[...active.querySelectorAll('img')];imgs.forEach((img,i)=>{try{img.decoding='async';if(i<3){img.loading='eager';img.fetchPriority=i===0?'high':'auto'}else{img.loading='lazy';img.fetchPriority='low'}}catch(_){}})}
function cancelPriority(){clearTimeout(priorityTimer);priorityTimer=0;if(priorityIdle&&window.cancelIdleCallback){try{cancelIdleCallback(priorityIdle)}catch(_){}priorityIdle=0}}function schedulePriority(){cancelPriority();if(document.hidden||document.body?.dataset?.activeView==='settings')return;const run=()=>{priorityTimer=0;priorityIdle=0;if(!document.hidden)prioritize()};if(window.requestIdleCallback)priorityIdle=requestIdleCallback(run,{timeout:300});else priorityTimer=setTimeout(run,80)}
function syncLearningFocus(){const modal=document.getElementById('lessonModal'),on=!!modal&&!modal.hidden;root.classList.toggle('learning-focus',on)}
function installLessonFocus(){const modal=document.getElementById('lessonModal');if(!modal||!window.MutationObserver)return;new MutationObserver(syncLearningFocus).observe(modal,{attributes:true,attributeFilter:['hidden']});syncLearningFocus()}
function syncModalPause(){const open=[...document.querySelectorAll('.modal')].some(x=>!x.hidden);root.classList.toggle('modal-open-v182',open)}function installModalPause(){const modals=[...document.querySelectorAll('.modal')];if(!modals.length||!window.MutationObserver)return;const mo=new MutationObserver(syncModalPause);modals.forEach(m=>mo.observe(m,{attributes:true,attributeFilter:['hidden']}));syncModalPause()}
function stopSample(){sampling=false;frames.length=0;last=0;if(raf){cancelAnimationFrame(raf);raf=0}clearTimeout(sampleTimer);sampleTimer=0}
function visibility(){root.classList.toggle('page-hidden',document.hidden);if(document.hidden){stopSample();cancelPriority()}else{detect();schedulePriority();if(document.body?.dataset?.activeView!=='settings')startSample()}}
function onView(e){frames.length=0;last=0;const v=e?.detail?.view||document.body?.dataset?.activeView||'';if(v==='settings'){stopSample();return}schedulePriority();if(!sampling)startSample()}
function boot(){detect();installLessonFocus();installModalPause();schedulePriority();visibility()}
addEventListener('resize',()=>{detect();schedulePriority()},{passive:true});document.addEventListener('visibilitychange',visibility,{passive:true});window.addEventListener('powder:view-changed',onView,{passive:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.POWDER_PERFORMANCE_V1757={version:'18.2.6-image-gpu-memory-sweep',tier:()=>tier,fps:()=>Math.round(fps),refresh:()=>{detect();syncLearningFocus();schedulePriority();startSample()}};window.POWDER_PERFORMANCE_V139=window.POWDER_PERFORMANCE_V1757;window.POWDER_PERFORMANCE_V134=window.POWDER_PERFORMANCE_V1757;
})();
