(()=>{'use strict';
const VERSION='18.2.6-image-runtime-integration';
const $=(s,r=document)=>r?.querySelector?.(s)||null;
const $$=(s,r=document)=>r?.querySelectorAll?[...r.querySelectorAll(s)]:[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lastSignatureByView=Object.create(null),imageQueued=false,imageIdle=0,imageTimer=0,refreshQueued=false,ready=false,touchEnhanced=false,pendingForce=false;
function app(){return window.POWDER_APP}
function save(){try{return app()?.getSave?.()||null}catch(_){return null}}
function lm(){return window.POWDER_LEARNING_MASTER_V2}
function percent(v){return `${Math.max(0,Math.min(100,Math.round(Number(v)||0)))}%`}
function lowPower(){const coarse=matchMedia?.('(pointer:coarse)')?.matches,mem=Number(navigator.deviceMemory||8),cores=Number(navigator.hardwareConcurrency||8);return mem<=4||cores<=4||(coarse&&innerWidth<=760)}
function installPerformanceTier(){const html=document.documentElement;const mirror=()=>{const perf=window.POWDER_PERFORMANCE_V1757,tier=perf?.tier?.()||html.dataset.perfMode||'balanced';html.classList.toggle('perf-low',tier!=='full');html.dataset.performanceTier=tier==='full'?'full':tier==='low'?'adaptive-low':'adaptive-balanced';html.classList.toggle('perf-paused',document.hidden)};window.addEventListener('powder:performance-tier',mirror,{passive:true});document.addEventListener('visibilitychange',mirror,{passive:true});mirror();}
function optimizeImage(img){if(!img||img.dataset.v131Optimized)return;img.dataset.v131Optimized='1';try{img.decoding='async';const critical=!!img.closest('.brand,#activePowArt,.battle-arena,.cv7-battle-shell,.powball-stage,.summon-reveal,.summon-art,.loading-screen');if(!critical){img.loading='lazy';img.fetchPriority='low';}else if(img.closest('.brand,#activePowArt'))img.fetchPriority='high';}catch(_){}}
function optimizeImages(root=document){const ir=window.POWDER_IMAGE_RUNTIME_V1826;if(ir?.scan)return ir.scan(root);$$('img',root).forEach(optimizeImage)}
function queueImages(root=null){const ir=window.POWDER_IMAGE_RUNTIME_V1826;if(ir?.refresh){ir.refresh();return}if(imageIdle&&window.cancelIdleCallback){try{cancelIdleCallback(imageIdle)}catch(_){}imageIdle=0}clearTimeout(imageTimer);imageTimer=0;if(imageQueued)return;imageQueued=true;const run=()=>{imageQueued=false;imageIdle=0;imageTimer=0;if(document.hidden)return;const target=root||document.querySelector('.view:not([hidden])')||document;optimizeImages(target)};if(window.requestIdleCallback)imageIdle=requestIdleCallback(run,{timeout:650});else imageTimer=setTimeout(run,80)}
function statusData(s){const L=lm(),daily=L?.todaySummary?.(s)||{total:0,zh:0,en:0},boss=L?.dailyBossStatus?.(s,s.rank)||{cost:30,ready:false,paid:false},mastery=Math.round(L?.averageMastery?.(s)||s.mastery||0),due=L?.dueQuestions?.(s)?.length||0,adv=s.adventure||{},wins=Object.values(adv.stageWins||{}).filter(Boolean).length;return{daily,boss,mastery,due,wins}}
function journeyMarkup(s){const d=statusData(s),learnDone=d.daily.total>=6&&d.daily.zh>=4&&d.daily.en>=2,masteryReady=d.mastery>=80,bossDone=!!d.boss.paid,bossReady=!!d.boss.ready;return `
 <div class="v131-journey-copy"><small>HÀNH TRÌNH HÔM NAY</small><b>${learnDone?'Đã đủ nhịp học':'Đang học'} · ${d.mastery}% Mastery</b></div>
 <div class="v131-journey-steps">
  <button data-v131-view="learn" class="${learnDone?'done':'active'}"><i>1</i><span><b>Học</b><small>${d.daily.total}/6 · 中 ${d.daily.zh}/4 · EN ${d.daily.en}/2</small></span></button>
  <button data-v131-view="learn" class="${masteryReady?'done':''}"><i>2</i><span><b>Mastery</b><small>${d.mastery}% · SRS ${d.due}</small></span></button>
  <button data-v131-view="adventure" class="${d.wins?'done':''}"><i>3</i><span><b>Phó bản</b><small>${d.wins} màn đã vượt</small></span></button>
  <button data-v131-view="boss" class="${bossDone?'done':bossReady?'ready':''}"><i>4</i><span><b>Boss ngày</b><small>${bossDone?'Đã mở':bossReady?'Sẵn sàng':`${Number(s.knowledge||0)}/${d.boss.cost||0} Knowledge`}</small></span></button>
 </div>`}
function ensureJourneyBars(s,view=document.body?.dataset?.activeView||''){const id={learn:'learnView',adventure:'adventureView',boss:'bossView'}[view];if(!id)return;const root=document.getElementById(id);if(!root)return;let bar=$('.v131-journey-bar',root);if(!bar){bar=document.createElement('section');bar.className='v131-journey-bar';const title=$('.section-title',root)||root.firstElementChild;title?.insertAdjacentElement('afterend',bar)||root.prepend(bar);}bar.innerHTML=journeyMarkup(s);}
function ensureHomePulse(s){const host=$('#v130DailyCommand');if(!host)return;let pulse=$('.v131-command-pulse',host);const d=statusData(s),remaining=Math.max(0,6-d.daily.total);if(!pulse){pulse=document.createElement('div');pulse.className='v131-command-pulse';host.appendChild(pulse);}pulse.innerHTML=`<span>⚡ <b>${remaining?`Còn ${remaining} Learning Unit`:'Đã đủ 6 Learning Units'}</b></span><span>🧠 Mastery <b>${d.mastery}%</b></span><span>🔁 SRS <b>${d.due}</b></span><span>👑 Boss <b>${d.boss.paid?'Đã mở':d.boss.ready?'Sẵn sàng':'Chưa đủ'}</b></span>`;}
function ensurePerformanceStatus(){const host=$('#settingsView .audio-settings-v811');if(!host)return;let box=$('.v131-performance-status',host);if(!box){box=document.createElement('div');box.className='v131-performance-status';host.appendChild(box);}const tier=document.documentElement.dataset.performanceTier||'full',light=tier!=='full',reduced=!!save()?.settings?.reducedMotion;box.innerHTML=`<div><span>⚙️</span><b>Tối ưu hiển thị tự động</b><em>${light?'Ưu tiên mượt':'Hiệu ứng đầy đủ'}</em></div><p>${light?'Powder đang giảm các hiệu ứng trang trí nặng ngoài Combat để giữ thao tác ổn định. Combat, Pow Ball và hiệu ứng mở quan trọng vẫn được giữ.':'Thiết bị đang chạy hồ sơ hiệu ứng đầy đủ. Nếu khung hình giảm, Powder sẽ tự hạ các hiệu ứng trang trí nặng.'}${reduced?' · Giảm chuyển động đang bật theo lựa chọn của bạn.':''}</p>`;}
function syncActiveNav(){const active=$('.nav-btn.is-active');if(!active)return;try{const tier=window.POWDER_PERFORMANCE_V1757?.tier?.()||'balanced';active.scrollIntoView({behavior:tier==='full'?'smooth':'auto',block:'nearest',inline:'center'})}catch(_){}}
function enhanceTouchTargets(){if(touchEnhanced||!matchMedia?.('(pointer:coarse)')?.matches)return;touchEnhanced=true;$$('button,.btn,[role="button"],select,input[type="checkbox"]').forEach(el=>el.classList.add('v131-touch'));}
function modalState(){const open=$$('.modal').filter(m=>!m.hidden);document.documentElement.classList.toggle('v131-modal-open',open.length>0);if(!open.length)return;const top=open.at(-1),card=$('.modal-card',top);if(card&&!card.hasAttribute('role')){card.setAttribute('role','dialog');card.setAttribute('aria-modal','true');}}
function installModalUX(){if(!window.MutationObserver)return;const mo=new MutationObserver(modalState);$$('.modal').forEach(m=>mo.observe(m,{attributes:true,attributeFilter:['hidden']}));document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const open=$$('.modal').filter(m=>!m.hidden).at(-1);if(!open)return;const close=$('[data-close]',open)||$('#bossModalClose',open);if(close){e.preventDefault();close.click();}});modalState();}
function installSmartNav(){document.addEventListener('click',e=>{const jump=e.target.closest?.('[data-v131-view]');if(jump){app()?.showView?.(jump.dataset.v131View);setTimeout(syncActiveNav,30);return;}if(e.target.closest?.('.nav-btn,[data-open-view],[data-world-view]'))setTimeout(syncActiveNav,40);},{passive:true});}
function installObserver(){const run=()=>{queueImages();modalState()};window.addEventListener('powder:rendered',run,{passive:true});window.addEventListener('powder:view-changed',run,{passive:true})}
function refresh(force=false){const s=save();if(!s?.starterId)return;const view=document.body?.dataset?.activeView||'home',d=statusData(s),sig=[s.rank,s.knowledge,d.daily.total,d.daily.zh,d.daily.en,d.mastery,d.due,d.boss.ready,d.boss.paid,d.wins].join('|');if(!force&&lastSignatureByView[view]===sig)return;lastSignatureByView[view]=sig;if(view==='learn'||view==='adventure'||view==='boss')ensureJourneyBars(s,view);if(view==='home')ensureHomePulse(s);if(view==='settings')ensurePerformanceStatus();queueImages(document.querySelector('.view:not([hidden])')||document);enhanceTouchTargets();}
function queueRefresh(force=false){pendingForce=pendingForce||force;if(refreshQueued)return;refreshQueued=true;requestAnimationFrame(()=>{refreshQueued=false;const f=pendingForce;pendingForce=false;refresh(f)});}
function wrapRender(){const B=window.POWDER_BIG_UPDATE_V130;if(B&&!B.__v131Wrapped){for(const key of ['render','onView']){const old=B[key];if(typeof old==='function')B[key]=function(...args){const out=old.apply(this,args);queueRefresh();return out;};}B.__v131Wrapped=true;}}
function installViewportGuard(){const update=()=>{document.documentElement.style.setProperty('--v131-vh',`${window.visualViewport?.height||innerHeight}px`);document.documentElement.classList.toggle('v131-compact',innerWidth<=760)};let t=0;const q=()=>{clearTimeout(t);t=setTimeout(update,80)};window.addEventListener('resize',q,{passive:true});window.visualViewport?.addEventListener?.('resize',q,{passive:true});update();}
function boot(){if(ready)return;if(!app()||!window.POWDER_DATA)return setTimeout(boot,90);ready=true;installPerformanceTier();installViewportGuard();installModalUX();installSmartNav();wrapRender();optimizeImages();enhanceTouchTargets();refresh(true);syncActiveNav();console.info('[Powder 18.2.6 Scoped Polish / Image Runtime ready]',{tier:document.documentElement.dataset.performanceTier});}
window.POWDER_POLISH_V131={version:VERSION,refresh:()=>queueRefresh(true),optimizeImages};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
