(()=>{'use strict';
const D=window.POWDER_DATA,V=window.POWDER_SKILL_V81;if(!D||!V)return;
const slotLabel={basic:'Đòn cơ bản',skill1:'Skill 1',skill2:'Skill 2',ultimate:'Ultimate',exclusive:'Độc quyền 7★'};
function powOf(x){return typeof x==='string'?D.pows.find(p=>p.id===x):x}
function metaOf(pow,slot){return V.pows?.[pow?.id]?.skills?.[slot]||null}
function stageOf(pow,star){const v=V.pows?.[pow?.id];if(!v)return null;const s=Math.max(Number(v.nativeStar)||0,Number(star)||0);return v.starProgression?.find(x=>Number(x.star)===s)||v.starProgression?.[0]||null}
function slotFromSkill(pow,skill,slot){if(slot)return slot;const v=V.pows?.[pow?.id];if(!v||!skill)return null;return Object.keys(v.skills||{}).find(k=>v.skills[k]?.id===skill.id)||null}
function rulesFor(powOrId,skill,slot){const pow=powOf(powOrId);if(!pow||!skill)return null;const s=slotFromSkill(pow,skill,slot)||skill.v81Slot||'skill1',m=metaOf(pow,s),v=V.pows?.[pow.id];if(s==='exclusive')return{summary:skill.description||skill.rulesText||'Độc quyền Thượng cổ.',activation:'Chỉ đúng Pow Thượng cổ sở hữu kỹ năng này, mở tại 7★ và dùng theo điều kiện tooltip.',effect:skill.description||skill.rulesText||'—',target:skill.target||'Theo tooltip.',notCounted:'Không thể học, copy, chuyển hoặc cấp cho Pow khác. Hành động phụ không tự tạo chuỗi.',limit:'1 lần/Pow/trận theo luật Exclusive Thượng cổ.',build:v?.goodPartners||'Phối hợp theo core riêng.'};return{summary:m?.description||skill.v81Description||skill.description||'—',activation:`Kỹ năng cố định ${slotLabel[s]||s} của ${pow.name}; khả dụng từ ${skill.unlockStar??pow.nativeStar??0}★.`,effect:m?.description||skill.v81Description||skill.description||'—',target:skill.target||'Theo cơ chế kỹ năng.',notCounted:'Không học/copy/thay chiêu. Trang bị và Cổ vật chỉ khuếch đại mechanic đã có; follow-up/đòn phụ không tự kích hoạt chuỗi.',limit:'Giữ nguyên tên và chức năng riêng của Pow. Khống chế cứng không được kéo dài trái quy tắc; Boss chuyển hiệu ứng phù hợp sang SPEED/thanh lượt khi cần.',build:v?.goodPartners||v?.teamRole||'Phối hợp theo core riêng của Pow.'};}
function passiveFor(powOrId){const pow=powOf(powOrId),v=V.pows?.[pow?.id];if(!pow||!v)return null;return{summary:v.coreDescription||v.core,activation:'Cơ chế bẩm sinh của chính Pow.',effect:v.coreDescription||v.core,notCounted:'Không phải skill có thể học/copy/thay; Trang bị/Cổ vật không được sinh mechanic mới.',limit:'Chỉ thuộc đúng Pow này.',build:v.goodPartners||v.teamRole||'Phối hợp theo core riêng.'};}
for(const p of D.pows||[]){const v=V.pows?.[p.id];if(!v)continue;p.abilities=p.abilities||{};p.abilities.passive={id:`${p.id}.core`,name:v.core,description:v.coreDescription||v.core,fixedCore:true,ownerId:p.id,rules:passiveFor(p)};}
window.POWDER_SKILL_DETAILS={version:'8.1-fixed-kit',rulesFor,passiveFor,stageOf,metaOf};
})();
