(()=>{'use strict';
const D=window.POWDER_DATA,E=window.POWDER_ENGINE,C=window.POWDER_CONFIG,V=window.POWDER_SKILL_V81,SD=window.POWDER_SKILL_DETAILS,ART=window.POWDER_SKILL_ART;if(!D||!E||!C||!V)return;
const slotKeys=['basic','skill1','skill2','ultimate'];
const slotNames={basic:'Đòn cơ bản',skill1:'Skill 1',skill2:'Skill 2',ultimate:'Ultimate'};
const clone=x=>x==null?x:(typeof structuredClone==='function'?structuredClone(x):JSON.parse(JSON.stringify(x)));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function pow(id){return D.pows.find(p=>p.id===id)}
function save(){try{return window.POWDER_APP?.getSave?.()||JSON.parse(localStorage.getItem(C.storageKey)||'{}')}catch(_){return{}}}
function stars(id){const p=pow(id),raw=save().owned?.[id]?.stars;return Math.max(0,Number(raw??p?.startStars??0)||0)}
function kit(p){return V.pows?.[typeof p==='string'?p:p?.id]||null}
function defaults(p){const k=kit(p);return {basic:k?.skills?.basic?.id||p?.abilities?.basic?.id||null,skill1:k?.skills?.skill1?.id||p?.abilities?.skills?.[0]?.id||null,skill2:k?.skills?.skill2?.id||p?.abilities?.skills?.[1]?.id||null,ultimate:k?.skills?.ultimate?.id||p?.abilities?.ultimate?.id||null}}
function getLoadout(id){const p=pow(id);return p?defaults(p):null}
function saveLoadout(){return false}
function abilityForSlot(p,key){if(!p)return null;if(key==='basic')return p.abilities?.basic||null;if(key==='skill1')return p.abilities?.skills?.[0]||null;if(key==='skill2')return p.abilities?.skills?.[1]||null;if(key==='ultimate')return p.abilities?.ultimate||null;if(key==='exclusive')return p.exclusiveSkill||p.abilities?.exclusive||null;return null}
function skillById(p,id){if(!p||!id)return null;for(const key of slotKeys){const a=abilityForSlot(p,key);if(a?.id===id)return a}const ex=abilityForSlot(p,'exclusive');return ex?.id===id?ex:null}
function poolForSlot(p,key){const a=abilityForSlot(p,key);return a?[a]:[]}
function available(p,key){const a=abilityForSlot(p,key),st=stars(p.id);return a&&st>=Number(a.unlockStar||0)?[a]:[]}
function stageAt(p,star){const v=kit(p);if(!v)return null;const n=Number(star)||0;if(n<Number(v.nativeStar||0))return{star:n,stage:'Khởi đầu',coefficient:1,effect:1,core:'Chưa đạt mốc sao gốc để mở đầy đủ sức mạnh bộ kỹ năng.'};return (v.starProgression||[]).find(x=>Number(x.star)===n)||(v.starProgression||[]).at(-1)||null}
function getDefaultAbility(id,key){return clone(abilityForSlot(pow(id),key))}
function getAbility(id,key){const p=pow(id),base=abilityForSlot(p,key);if(!p||!base)return null;const st=stars(id);if(st<Number(base.unlockStar||0))return {id:base.id,name:'Chưa mở khóa',power:0,type:base.type||'skill',unlockStar:base.unlockStar,locked:true,fixedSkill:true};let out=clone(base);if(p.specialStarter&&window.POWDER_FORM_RESOLVER?.resolveAbility)out=window.POWDER_FORM_RESOLVER.resolveAbility(p,out,st);out.v81Stage=stageAt(p,st);out.fixedSkill=true;return out}
function snapshotLoadout(id){const p=pow(id);if(!p)return null;return Object.fromEntries(slotKeys.map(k=>[k,getAbility(id,k)]))}
function openSelector(){return false}
function upgradeText(p,key,star){const row=stageAt(p,star);return row?.[key]||''}
function metaDescription(p,key,a){return kit(p)?.skills?.[key]?.description||a?.v81Description||a?.description||'—'}function artFor(a){return ART?.get?.(a)||a?.skillArt||''}
function targetText(a){const target=String(a?.target||'enemy').toLowerCase();if(target==='self')return'Bản thân';if(target==='ally'||target==='lowest-ally')return'Đồng minh';if(target==='team'||target==='all-allies')return'Toàn đội';if(target==='all-enemies')return'Toàn bộ địch';if(target==='revive')return'Đồng minh đã bị hạ';return'Một kẻ địch'}
function resourceText(a,key){const parts=[];if(Number(a?.manaCost)>0)parts.push(`${Number(a.manaCost)} Mana`);if(key==='ultimate')parts.push('4 Nộ');if(Number(a?.cooldown)>0)parts.push(`CD ${Number(a.cooldown)}`);parts.push(targetText(a));return parts.join(' · ')}
function ensureModal(){if(document.querySelector('#fixedSkillRuleModal'))return;document.body.insertAdjacentHTML('beforeend',`<section id="fixedSkillRuleModal" class="modal" hidden><div class="backdrop" data-fixed-rule-close></div><article class="modal-card skill-rule-modal"><header><div><p class="eyebrow">KỸ NĂNG CỐ ĐỊNH</p><h2 id="fixedSkillRuleTitle">Chi tiết kỹ năng</h2><small id="fixedSkillRuleMeta"></small></div><button class="icon-btn" data-fixed-rule-close>×</button></header><div id="fixedSkillRuleBody" class="modal-body"></div><footer><button class="btn primary" data-fixed-rule-close>Đã hiểu</button></footer></article></section>`);document.querySelectorAll('[data-fixed-rule-close]').forEach(b=>b.onclick=()=>document.querySelector('#fixedSkillRuleModal').hidden=true)}
function openRule(id,key){const p=pow(id),a=abilityForSlot(p,key);if(!p||!a)return;ensureModal();const modal=document.querySelector('#fixedSkillRuleModal'),st=stars(id),v=kit(p),row=stageAt(p,st),r=SD?.rulesFor?.(p,a,key);modal.querySelector('#fixedSkillRuleTitle').textContent=`${a.name} · ${p.name}`;modal.querySelector('#fixedSkillRuleMeta').textContent=`${slotNames[key]||'Độc quyền'} · CỐ ĐỊNH · ${st}/${p.maxStars}★`;const art=artFor(a);modal.querySelector('#fixedSkillRuleBody').innerHTML=`<div class="fixed-skill-rule ${art?'has-skill-art':''}">${art?`<div class="fixed-skill-rule-art"><img src="${esc(art)}" alt="${esc(a.name)}" loading="lazy" decoding="async"></div>`:''}<div class="fixed-skill-rule-copy"><p><b>Thuộc bộ kỹ năng:</b> ${esc(p.name)}</p><p>${esc(v?.skills?.[key]?.description||a.description||a.rulesText||'—')}</p>${row?`<div class="fixed-stage-box"><b>${esc(row.stage)} · ${row.star}★</b><span>Hệ số trực tiếp ×${Number(row.coefficient||1).toFixed(2)} · Hiệu lực ×${Number(row.effect||1).toFixed(2)}</span></div>`:''}<div class="skill-rule-grid"><div><b>Điều kiện</b><span>${esc(r?.activation||'Theo tooltip.')}</span></div><div><b>Giới hạn</b><span>${esc(r?.limit||'Theo quy tắc của kỹ năng.')}</span></div><div><b>Không được tính</b><span>${esc(r?.notCounted||'Không học/copy/thay chiêu.')}</span></div><div><b>Core</b><span>${esc(v?.coreDescription||v?.core||'—')}</span></div></div></div></div>`;modal.hidden=false}
function renderBoard(root,id){const p=pow(id),v=kit(p);if(!root||!p)return;const st=stars(id),current=stageAt(p,st),nextStar=st<p.maxStars?st+1:null,next=nextStar==null?null:stageAt(p,nextStar);let html=slotKeys.map((key,i)=>{const a=abilityForSlot(p,key),locked=st<Number(a?.unlockStar||0),desc=metaDescription(p,key,a),nextTxt=next?upgradeText(p,key,nextStar):'',art=artFor(a);return `<article class="pow-skill-slot slot-${i+1} slot-kind-${key} ${locked?'locked':''} ${art?'has-skill-art':''}"><span class="skill-frame-corner"></span>${art?`<div class="pow-skill-art"><img src="${esc(art)}" alt="${esc(a?.name||'Kỹ năng')}" loading="lazy" decoding="async"></div>`:''}<div class="pow-skill-copy"><small>${esc(slotNames[key])} · CỐ ĐỊNH</small><b>${esc(a?.name||'—')}</b><span>${locked?`Mở ${a?.unlockStar||0}★`:esc(resourceText(a,key))}</span><em>${esc(desc)}</em>${nextTxt?`<div class="fixed-next-upgrade"><i>${nextStar}★</i><span>${esc(nextTxt)}</span></div>`:''}<button type="button" class="skill-rule-open" data-fixed-rule="${key}" data-fixed-pow="${esc(id)}">Chi tiết · tăng sao</button>${key==='ultimate'?'<i class="ultimate-rune">✦</i>':''}</div></article>`}).join('');if(p.exclusiveSkill){const ex=p.exclusiveSkill,locked=st<7;html+=`<article class="pow-exclusive-slot ${locked?'locked':''}"><small>ĐỘC QUYỀN THƯỢNG CỔ · CỐ ĐỊNH</small><b>${esc(ex.name)}</b><span>${locked?'Mở 7★':'7★ · 1 lần/Pow/trận'}</span><em>${esc(ex.description||ex.rulesText||'—')}</em><button type="button" class="skill-rule-open exclusive-rule-open" data-fixed-rule="exclusive" data-fixed-pow="${esc(id)}">Chi tiết</button></article>`}root.innerHTML=html;root.querySelectorAll('[data-fixed-rule]').forEach(b=>b.onclick=()=>openRule(b.dataset.fixedPow,b.dataset.fixedRule));const parent=root.closest('.inventory-ability-list'),card=parent?.querySelector('.pow-passive-card');if(card){const passive=p.abilities?.passive||{},passiveArt=p.passiveArt||passive.art||'',passiveDescription=passive.description||passive.rules?.summary||'Nội tại sẽ hiển thị khi dữ liệu thiết kế sẵn sàng.';card.innerHTML=`<div class="pow-passive-layout ${passiveArt?'has-passive-art':''}">${passiveArt?`<div class="pow-passive-art"><img src="${esc(passiveArt)}" alt="Nội tại ${esc(p.name)}" loading="lazy" decoding="async"></div>`:''}<div class="pow-passive-copy"><b>${esc(passive.name||'NỘI TẠI')}</b><small>${esc(passiveDescription)}</small><div class="passive-rule-mini"><span><i>Core chiến đấu</i>${esc(v?.coreDescription||v?.core||p.coreName||'Theo bộ kỹ năng riêng')}</span><span><i>Mốc hiện tại</i>${esc(current?.stage||'Khởi đầu')} · ${st}/${p.maxStars}★</span><span><i>Luật cố định</i>Không học · không copy · không thay</span><span><i>Đội hình phù hợp</i>${esc(v?.goodPartners||v?.teamRole||'Theo vai trò chiến đấu')}</span>${next?.core?`<span><i>Nâng ${nextStar}★</i>${esc(next.core)}</span>`:''}</div></div></div>`}}
function decoratePanels(){document.querySelectorAll('.inventory-ability-list[data-skill-pow]').forEach(panel=>{const id=panel.dataset.skillPow,board=panel.querySelector('.pow-skill-board');if(!board||!id)return;const signature=`${id}:${stars(id)}:${ART?.version||'none'}`;if(board.dataset.fixedSkillSignature===signature&&board.childElementCount)return;renderBoard(board,id);board.dataset.fixedSkillSignature=signature;panel.querySelectorAll('.skill-select-open').forEach(b=>b.remove())})}
let decorateQueued=false;function scheduleDecorate(){if(decorateQueued)return;decorateQueued=true;const run=()=>{decorateQueued=false;decoratePanels()};if(typeof requestAnimationFrame==='function')requestAnimationFrame(run);else setTimeout(run,16)}
function cleanLegacy(){try{localStorage.removeItem(`${C.storageKey}_skill_loadouts_v2`)}catch(_){}if(window.POWDER_APP){window.POWDER_APP.getSkillLoadout=id=>getLoadout(id);window.POWDER_APP.setSkillLoadout=()=>false}}
const decoratedViews=new Set(['inventory','powdex','gear']);
cleanLegacy();if(decoratedViews.has(document.body?.dataset?.activeView||''))decoratePanels();window.addEventListener('powder:rendered',e=>{const v=e?.detail?.view||document.body?.dataset?.activeView||'';if(decoratedViews.has(v))scheduleDecorate()},{passive:true});window.addEventListener('powder:view-changed',e=>{const v=e?.detail?.view||'';if(decoratedViews.has(v))scheduleDecorate()},{passive:true});
document.addEventListener('click',e=>{if(e.target?.closest?.('#gearView [data-ph-tab="skills"]'))scheduleDecorate()},{capture:true,passive:true});
window.POWDER_SKILL_LOADOUT={getLoadout,snapshotLoadout,saveLoadout,getAbility,getDefaultAbility,skillById,poolForSlot,openSelector,available,stars,renderBoard,stageAt,version:'12.4-passive-core-separated',fixed:true};
})();
