(()=>{'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const online=()=>window.POWDER_ONLINE_V150,app=()=>window.POWDER_APP,data=()=>window.POWDER_DATA;
const powThumb=asset=>window.POWDER_THUMBNAILS?.[asset]||asset;
const st={data:null,busy:false,lastSearch:[],timer:0,heartbeat:0,promise:null,lastLoaded:0,lastError:''};
const ranks=['Nhập môn','Sơ cấp','Trung cấp','Cao cấp','Chuyên nghiệp','Cao thủ','Thách đấu'];
const act={idle:'Đang nghỉ',home:'Ở Căn cứ',learn:'Đang học',adventure:'Đang phiêu lưu',boss:'Đang ở Điện Boss',battle:'Đang chiến đấu',gear:'Đang Cường Hóa',shop:'Đang ở Chợ',powball:'Đang mở PowBall',powdex:'Đang xem Powdex',tamer:'Đang xem Tamer',social:'Đang ở Cộng đồng',settings:'Đang cài đặt',offline:'Ngoại tuyến'};
function pow(id){return data()?.pows?.find(x=>x.id===id)||null}function powArt(id){return pow(id)?.asset||''}function powName(id){return pow(id)?.name||id||'—'}
async function raw(action,payload={},opt={}){if(!online()?.hasSession?.())throw new Error('Hãy đăng nhập Powder Online trước.');return online().request('/functions/v1/powder-social',{method:'POST',body:JSON.stringify({action,...payload}),...opt})}
function toast(t){let e=$('#socialToastV154');if(!e){e=document.createElement('div');e.id='socialToastV154';e.className='social-toast-v154';document.body.appendChild(e)}e.textContent=t;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,2600)}
function statusDot(p){return `<i class="soc154-dot ${p?.online?'online':'offline'}"></i>`}
function avatar(p){const art=powArt(p?.favoritePowId);return art?`<img src="${esc(art)}" alt="">`:`<span>${esc((p?.displayName||'T').slice(0,1).toUpperCase())}</span>`}
function card(p,actions=''){if(!p)return'';const limited=p.private||p.friendsOnly;return `<article class="soc154-user"><div class="soc154-avatar">${avatar(p)}${statusDot(p)}</div><div class="soc154-user-main"><small>${esc(p.tamerUid||'')}</small><b>${esc(p.displayName||'Tamer')}</b>${limited?`<span>${p.private?'Hồ sơ riêng tư':'Chỉ bạn bè xem chi tiết'}</span>`:`<span>${esc(ranks[p.rank]||'Nhập môn')} · ${p.powCount||0} Pow · Mastery ${Math.round(Number(p.mastery||0))}%</span><em>${esc(p.online?(act[p.activity]||'Đang Online'):'Ngoại tuyến')}</em>`}</div><div class="soc154-user-actions">${actions}</div></article>`}
function signalRender(state='ready'){window.dispatchEvent(new CustomEvent('powder:social-render',{detail:{state,at:Date.now()}}))}
function renderLoggedOut(root){root.innerHTML=`<section class="soc154-login"><div class="soc154-globe">🌐</div><p class="eyebrow">POWDER COMMUNITY</p><h1>Kết nối các Tamer</h1><p>Cộng đồng đã sẵn sàng. Đăng nhập Powder Online để tìm bạn bằng UID, xem trạng thái Online và hồ sơ Tamer.</p><button class="btn primary" data-soc154-login>Đăng nhập Powder Online</button></section>`;root.querySelector('[data-soc154-login]')?.addEventListener('click',()=>online()?.open?.());signalRender('logged-out')}
function renderLoading(root){root.innerHTML=`<section class="soc154-hero soc154-loading-shell"><div class="soc154-my-avatar soc154-pulse">🌐</div><div><p class="eyebrow">POWDER COMMUNITY</p><h1>Cộng đồng Powder</h1><p>Giao diện đã mở. Đang lấy hồ sơ và danh sách bạn bè từ máy chủ…</p><div class="soc154-badges"><span>Đang đồng bộ</span><span>Không khóa giao diện</span></div></div></section><section class="soc154-grid-top"><article class="soc154-panel soc154-loading-panel"><h2>Tìm Tamer</h2><p>Bạn có thể sử dụng ngay sau khi dữ liệu Online tải xong.</p></article><article class="soc154-panel soc154-loading-panel"><h2>Lời mời kết bạn</h2><p>Đang kiểm tra dữ liệu…</p></article></section><section class="soc154-panel soc154-loading-panel"><h2>Bạn bè</h2><p>Đang tải danh sách. Nếu mạng chậm, trang vẫn tiếp tục phản hồi bình thường.</p></section>`;signalRender('loading')}
function renderError(root,msg){root.innerHTML=`<section class="soc154-login soc154-error-shell"><div class="soc154-globe">⚠️</div><p class="eyebrow">POWDER COMMUNITY</p><h1>Chưa lấy được dữ liệu Online</h1><p>${esc(msg||'Kết nối Cộng đồng đang chậm.')}</p><button class="btn primary" data-soc154-retry>Thử lại</button></section>`;root.querySelector('[data-soc154-retry]')?.addEventListener('click',()=>load(true));signalRender('error')}
function ownPows(){const save=app()?.getSave?.()||{};return Object.keys(save.owned||{}).map(id=>pow(id)).filter(Boolean)}
function render(root=$('#socialHubV154')){if(!root)return;if(!online()?.hasSession?.()){st.data=null;renderLoggedOut(root);return}if(!st.data){renderLoading(root);load(false);return}const d=st.data,me=d.me||{},friends=d.friends||[],incoming=d.incoming||[],outgoing=d.outgoing||[];root.innerHTML=`
<section class="soc154-hero"><div class="soc154-my-avatar">${avatar(me)}</div><div><p class="eyebrow">HỒ SƠ TAMER ONLINE</p><h1>${esc(me.displayName||'Tamer')}</h1><button class="soc154-uid" data-soc154-copy>${esc(me.tamerUid||'UID')}</button><p>${esc(me.bio||'Chưa có lời giới thiệu. Hãy thêm một câu để bạn bè nhận ra bạn.')}</p><div class="soc154-badges"><span>${esc(ranks[me.rank]||'Nhập môn')}</span><span>${me.powCount||0} Pow</span><span>${friends.length} bạn bè</span><span>${statusDot(me)} Online</span></div></div><div class="soc154-hero-actions"><button class="btn secondary" data-soc154-edit>Chỉnh hồ sơ</button><button class="btn primary" data-soc154-refresh>Làm mới</button></div></section>
<section class="soc154-grid-top"><article class="soc154-panel"><div class="soc154-panel-head"><div><p class="eyebrow">TÌM TAMER</p><h2>UID hoặc tên người chơi</h2></div></div><form class="soc154-search" data-soc154-search><input id="soc154SearchInput" placeholder="Ví dụ: PWR-... hoặc tên Tamer" autocomplete="off"><button>Tìm</button></form><div id="soc154SearchResults" class="soc154-stack">${st.lastSearch.length?st.lastSearch.map(p=>card(p,`<button data-soc154-profile="${esc(p.id)}">Hồ sơ</button>${p.friend?'':`<button class="primary" data-soc154-add="${esc(p.id)}" ${p.allowFriendRequests===false?'disabled':''}>Kết bạn</button>`}`)).join(''):'<div class="soc154-empty">Tìm người chơi để kết nối bằng UID hoặc tên.</div>'}</div></article>
<article class="soc154-panel"><div class="soc154-panel-head"><div><p class="eyebrow">LỜI MỜI</p><h2>${incoming.length} đang chờ</h2></div></div><div class="soc154-stack">${incoming.map(r=>card(r.profile,`<button class="primary" data-soc154-accept="${r.id}">Đồng ý</button><button data-soc154-decline="${r.id}">Từ chối</button>`)).join('')||'<div class="soc154-empty">Không có lời mời mới.</div>'}${outgoing.length?`<div class="soc154-subtitle">ĐÃ GỬI</div>${outgoing.map(r=>card(r.profile,`<button data-soc154-cancel="${r.id}">Hủy</button>`)).join('')}`:''}</div></article></section>
<section class="soc154-panel soc154-friends"><div class="soc154-panel-head"><div><p class="eyebrow">BẠN BÈ</p><h2>${friends.length} Tamer đã kết nối</h2></div><span>${friends.filter(x=>x.online).length} đang Online</span></div><div class="soc154-friend-grid">${friends.map(p=>card(p,`<button data-soc154-profile="${esc(p.id)}">Xem hồ sơ</button>${p.online?`<span class="soc154-online-note">● Online</span>`:`<span class="soc154-offline-note">Offline</span>`}`)).join('')||'<div class="soc154-empty wide">Chưa có bạn bè. Hãy tìm UID của một Tamer để kết nối.</div>'}</div></section>
<section class="soc154-next"><span>🌐</span><div><b>Cộng đồng Tamer</b><p>Kết bạn, xem trạng thái Online và hồ sơ Tamer. Chiến đấu của người chơi chỉ diễn ra trong Map, Boss và Sự kiện.</p></div></section>`;bind(root);signalRender('ready');if(Date.now()-st.lastLoaded>15000)load(false)}
function bind(root){root.querySelector('[data-soc154-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(st.data.me.tamerUid);toast('Đã sao chép UID Tamer.')}catch{}});root.querySelector('[data-soc154-refresh]')?.addEventListener('click',()=>load(true));root.querySelector('[data-soc154-edit]')?.addEventListener('click',openEdit);root.querySelector('[data-soc154-search]')?.addEventListener('submit',async e=>{e.preventDefault();const q=$('#soc154SearchInput')?.value.trim();if(!q)return;try{const d=await raw('search',{query:q});st.lastSearch=d.results||[];render()}catch(x){toast(x.message)}});root.querySelectorAll('[data-soc154-add]').forEach(b=>b.onclick=()=>actReq('send_request',{userId:b.dataset.soc154Add},'Đã gửi lời mời kết bạn.'));root.querySelectorAll('[data-soc154-accept]').forEach(b=>b.onclick=()=>actReq('respond_request',{requestId:b.dataset.soc154Accept,decision:'accept'},'Đã trở thành bạn bè.'));root.querySelectorAll('[data-soc154-decline]').forEach(b=>b.onclick=()=>actReq('respond_request',{requestId:b.dataset.soc154Decline,decision:'decline'},'Đã từ chối lời mời.'));root.querySelectorAll('[data-soc154-cancel]').forEach(b=>b.onclick=()=>actReq('cancel_request',{requestId:b.dataset.soc154Cancel},'Đã hủy lời mời.'));root.querySelectorAll('[data-soc154-profile]').forEach(b=>b.onclick=()=>openProfile(b.dataset.soc154Profile))}
async function actReq(action,payload,msg){try{await raw(action,payload);toast(msg);await load(true)}catch(e){toast(e.message)}}
async function load(force=false){if(!online()?.hasSession?.()){st.data=null;render();return null}if(st.promise)return st.promise;if(!force&&st.data&&Date.now()-st.lastLoaded<12000)return st.data;st.busy=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),7000);st.promise=(async()=>{try{const next=await raw('state',{}, {signal:controller.signal});st.data=next||{};st.lastLoaded=Date.now();st.lastError='';render();return st.data}catch(e){const msg=e?.name==='AbortError'?'Máy chủ phản hồi quá lâu. Hãy thử lại.':(e?.message||'Không thể tải Cộng đồng.');st.lastError=msg;console.error('[Community]',e);if(st.data){toast(msg);signalRender('stale')}else{const root=$('#socialHubV154');if(root)renderError(root,msg)}return null}finally{clearTimeout(timer);st.busy=false;st.promise=null}})();return st.promise}
function ensureModal(){let m=$('#soc154Modal');if(!m){m=document.createElement('section');m.id='soc154Modal';m.className='soc154-modal';m.hidden=true;m.innerHTML='<article id="soc154ModalCard"></article>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.hidden=true})}return m}
function openEdit(){const m=ensureModal(),c=$('#soc154ModalCard'),me=st.data.me||{},pows=ownPows();c.innerHTML=`<div class="soc154-modal-head"><div><p class="eyebrow">HỒ SƠ CÔNG KHAI</p><h2>Chỉnh hồ sơ Tamer</h2></div><button data-soc154-close>×</button></div><label>Giới thiệu<textarea id="soc154Bio" maxlength="160">${esc(me.bio||'')}</textarea></label><label>Pow yêu thích<select id="soc154Favorite"><option value="">Chưa chọn</option>${pows.map(p=>`<option value="${esc(p.id)}" ${p.id===me.favoritePowId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Quyền riêng tư<select id="soc154Visibility"><option value="public" ${me.visibility==='public'?'selected':''}>Mọi Tamer</option><option value="friends" ${me.visibility==='friends'?'selected':''}>Chỉ bạn bè</option><option value="private" ${me.visibility==='private'?'selected':''}>Riêng tư</option></select></label><label class="soc154-check"><input type="checkbox" id="soc154Allow" ${me.allowFriendRequests!==false?'checked':''}> Cho phép nhận lời mời kết bạn</label><div><small>Đội hình trưng bày · chọn tối đa 5 Pow</small><div class="soc154-pow-picks">${pows.map(p=>`<label><input type="checkbox" data-soc154-showcase value="${esc(p.id)}" ${(me.showcaseTeam||[]).includes(p.id)?'checked':''}><img src="${esc(powThumb(p.asset))}"><span>${esc(p.name)}</span></label>`).join('')}</div></div><div class="soc154-modal-actions"><button class="btn secondary" data-soc154-close>Hủy</button><button class="btn primary" data-soc154-save>Lưu hồ sơ</button></div>`;m.hidden=false;c.querySelectorAll('[data-soc154-close]').forEach(b=>b.onclick=()=>m.hidden=true);c.querySelector('[data-soc154-save]').onclick=async()=>{const showcase=[...c.querySelectorAll('[data-soc154-showcase]:checked')].slice(0,5).map(x=>x.value);try{await raw('update_profile',{bio:$('#soc154Bio').value,visibility:$('#soc154Visibility').value,allowFriendRequests:$('#soc154Allow').checked,favoritePowId:$('#soc154Favorite').value,showcaseTeam:showcase});m.hidden=true;toast('Đã cập nhật hồ sơ.');await load(true)}catch(e){toast(e.message)}}}
async function openProfile(id){try{const d=await raw('profile',{userId:id}),p=d.profile,m=ensureModal(),c=$('#soc154ModalCard'),limited=p.private||p.friendsOnly;c.innerHTML=`<div class="soc154-modal-head"><div><p class="eyebrow">TAMER PROFILE</p><h2>${esc(p.displayName)}</h2><small>${esc(p.tamerUid)}</small></div><button data-soc154-close>×</button></div><div class="soc154-profile-big"><div class="soc154-big-avatar">${avatar(p)}</div>${limited?`<div><h3>${p.private?'Hồ sơ riêng tư':'Chỉ hiển thị cho bạn bè'}</h3><p>Tamer này đã giới hạn thông tin hồ sơ.</p></div>`:`<div><h3>${esc(ranks[p.rank]||'Nhập môn')} ${statusDot(p)}</h3><p>${esc(p.bio||'Chưa có giới thiệu.')}</p><div class="soc154-badges"><span>${p.powCount} Pow</span><span>${p.wins} thắng</span><span>Mastery ${Math.round(Number(p.mastery||0))}%</span><span>${esc(p.online?(act[p.activity]||'Online'):'Ngoại tuyến')}</span></div></div>`}</div>${!limited&&p.favoritePowId?`<div class="soc154-favorite"><img src="${esc(powThumb(powArt(p.favoritePowId)))}"><div><small>POW YÊU THÍCH</small><b>${esc(powName(p.favoritePowId))}</b></div></div>`:''}${!limited&&p.showcaseTeam?.length?`<div class="soc154-showcase"><small>ĐỘI HÌNH TRƯNG BÀY</small><div>${p.showcaseTeam.map(id=>{const pw=pow(id);return pw?`<article><img src="${esc(powThumb(pw.asset))}"><b>${esc(pw.name)}</b></article>`:''}).join('')}</div></div>`:''}<div class="soc154-modal-actions"><button class="btn secondary" data-soc154-close>Đóng</button>${p.friend?`<button class="btn danger" data-soc154-remove="${esc(p.id)}">Hủy kết bạn</button>`:''}</div>`;m.hidden=false;c.querySelectorAll('[data-soc154-close]').forEach(b=>b.onclick=()=>m.hidden=true);c.querySelector('[data-soc154-remove]')?.addEventListener('click',async()=>{if(!confirm(`Hủy kết bạn với ${p.displayName}?`))return;await raw('remove_friend',{userId:p.id});m.hidden=true;await load(true)})}catch(e){toast(e.message)}}
function currentActivity(){if(window.POWDER_PVP_V155?.isInMatch?.())return 'battle';const active=$('.nav-btn.is-active')?.dataset.view||'home';return active==='chests'?'powball':active}
async function heartbeat(){if(!online()?.hasSession?.()||navigator.onLine===false||document.hidden)return;try{await raw('heartbeat',{activity:currentActivity()})}catch{}}
function scheduleHeartbeat(delay=120000){clearTimeout(st.heartbeat);st.heartbeat=0;if(document.hidden||$('#socialView')?.hidden||!online()?.hasSession?.()||navigator.onLine===false)return;st.heartbeat=setTimeout(async()=>{st.heartbeat=0;await heartbeat();scheduleHeartbeat()},Math.max(15000,delay))}
function boot(){document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="social"],[data-open-view="social"]'))setTimeout(()=>{render();heartbeat();scheduleHeartbeat()},0)},{passive:true});window.addEventListener('powder:online-login',()=>setTimeout(()=>{st.data=null;st.lastLoaded=0;heartbeat();if(!$('#socialView')?.hidden)render();scheduleHeartbeat(15000)},350));window.addEventListener('online',()=>{if(!$('#socialView')?.hidden)render();heartbeat();scheduleHeartbeat(15000)});window.addEventListener('offline',()=>{clearTimeout(st.heartbeat);st.heartbeat=0},{passive:true});window.addEventListener('powder:view-changed',e=>{if(e?.detail?.view==='social')scheduleHeartbeat(15000);else{clearTimeout(st.heartbeat);st.heartbeat=0}},{passive:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('#socialView')?.hidden){render();heartbeat();scheduleHeartbeat()}else{clearTimeout(st.heartbeat);st.heartbeat=0}},{passive:true});scheduleHeartbeat()}
window.POWDER_SOCIAL_V155={version:'17.7.2',render,load,heartbeat,state:()=>st.data};window.POWDER_SOCIAL_V154=window.POWDER_SOCIAL_V155;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
