(()=>{'use strict';
const VERSION='18.2.6-image-gpu-integrated-stability-runtime';
const $=(s,r=document)=>r?.querySelector?.(s)||null;
const $$=(s,r=document)=>r?.querySelectorAll?[...r.querySelectorAll(s)]:[];
let ready=false,refreshTimer=0,lastHealth='';
function app(){return window.POWDER_APP||null}
function world(){return window.POWDER_WORLD_V9||window.POWDER_WORLD_V8||null}
function fmtTime(ts){if(!Number(ts))return'Chưa ghi';try{return new Date(Number(ts)).toLocaleString('vi-VN')}catch(_){return'—'}}
function health(){const a=app()?.getSaveHealth?.()||{},w=world()?.getSaveHealth?.()||{};return{a,w}}
function fmtBytes(n){n=Math.max(0,Number(n)||0);return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`}
function healthMarkup(){const {a,w}=health(),aErr=Array.isArray(a.errors)?a.errors:[],pending=Number(w.pendingArtifactSummon?.count||0),exchange=!!w.pendingCurrencyExchange?.id,recovered=!!(a.recoverySource||a.meta?.recoverySource||w.meta?.recoverySource),ok=!aErr.length&&!pending&&!exchange,bytes=Number(a.bytes||0)+Number(w.bytes||0);return `<div class="v132-health-head"><div><span>${ok?'✓':'!'}</span><div><b>${ok?'Dữ liệu đang an toàn':'Có giao dịch đang được phục hồi'}</b><small>Tiến độ · Cổ vật · Shop · Learning</small></div></div><em>${recovered?'Đã tự phục hồi':'Tự động bảo vệ'}</em></div><div class="v132-health-grid"><div><small>Tiến độ</small><b>Đã xác nhận</b><span>${aErr.length?`${aErr.length} cảnh báo`:'Không có lỗi cấu trúc'}</span></div><div><small>Kho Cổ vật</small><b>${Number(w.artifactInstances||0)} bản</b><span>${pending?`Đang phục hồi ${pending} vé`:exchange?'Đang hoàn tất đổi Tinh Tệ':'Không có giao dịch treo'}</span></div><div><small>Dung lượng save</small><b>${fmtBytes(bytes)}</b><span>${Number(a.backupSlots||0)} dự phòng · ${Number(a.fullBackupSlots||0)} bản đầy đủ</span></div><div><small>Lần lưu gần nhất</small><b>${fmtTime(a.meta?.lastSavedAt)}</b><span>${String(a.meta?.lastReason||'Tự động')}</span></div></div>${aErr.length?`<p class="v132-health-warn">${aErr.slice(0,3).join(' · ')}</p>`:''}<div class="v132-health-actions"><button class="btn secondary small" data-v132-backup>Tạo bản sao an toàn</button><button class="btn secondary small" data-v132-verify>Kiểm tra lại</button></div>`}
function ensureHealthPanel(){const root=$('#settingsView .settings-grid');if(!root)return;let card=$('.v132-save-health',root);if(!card){card=document.createElement('article');card.className='panel v132-save-health';const danger=$('.danger',root);danger?.insertAdjacentElement('beforebegin',card)||root.appendChild(card)}const sig=JSON.stringify(health());if(sig!==lastHealth){lastHealth=sig;card.innerHTML=`<h2>An toàn dữ liệu</h2><p class="muted">Powder tự tạo vùng ghi an toàn trước khi xác nhận save và giữ bản phục hồi nếu trình duyệt bị đóng giữa thao tác.</p>${healthMarkup()}`;card.querySelector('[data-v132-backup]')?.addEventListener('click',()=>{const a=app(),w=world();const full=a?.createFullBackup?.('manual');if(!full){a?.createBackup?.('manual');w?.createBackup?.('manual')}a?.saveNow?.('manual-backup');w?.saveNow?.('manual-backup');showToast(full?'Đã tạo bản sao đầy đủ Pow, Learning, Trang bị và Cổ vật.':'Đã tạo bản sao an toàn.');lastHealth='';ensureHealthPanel()});card.querySelector('[data-v132-verify]')?.addEventListener('click',()=>{app()?.saveNow?.('manual-verify');world()?.saveNow?.('manual-verify');lastHealth='';ensureHealthPanel();showToast('Đã kiểm tra và xác nhận dữ liệu hiện tại.');});}}
function showToast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.hidden=true,2300)}
function markScrollable(root=document){const selectors=['.table-scroll','.filter-row','.world-view-switch','.button-row','.v131-journey-steps','.ph-team-editor-tools','.pa126-materials ul','.w93-shop-tabs'],els=[];for(const sel of selectors)els.push(...$$(sel,root));if(!els.length)return;const measure=()=>els.map(el=>[el,el.scrollWidth>el.clientWidth+2]);const mutate=rows=>rows?.forEach?.(([el,on])=>el.classList.toggle('v132-scroll-x',!!on));const dom=window.POWDER_DOM_RUNTIME_V1825;if(dom?.measureMutate)dom.measureMutate('stability-scroll:'+String(document.body?.dataset?.activeView||''),measure,mutate);else mutate(measure())}
function hardenImages(root=document){$$('img',root).forEach(img=>{if(img.dataset.v132Safe)return;img.dataset.v132Safe='1';img.draggable=false;try{img.decoding='async'}catch(_){}})}
function refresh(){const view=document.body?.dataset?.activeView||'',root=document.querySelector('.view:not([hidden]),#setupScreen:not([hidden])')||document;if(view==='settings')ensureHealthPanel();markScrollable(root);hardenImages(root)}
function queueRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,80)}
function installSaveFlush(){const flush=()=>{try{app()?.saveNow?.('pagehide')}catch(_){}try{world()?.saveNow?.('pagehide')}catch(_){}};window.addEventListener('pagehide',flush,{capture:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)flush()},{passive:true})}
function installOverflowObserver(){if(!window.ResizeObserver)return;const ro=new ResizeObserver(queueRefresh);['settingsView','adventureView','gearView','shopView'].forEach(id=>{const el=document.getElementById(id);if(el)ro.observe(el)});window.addEventListener('resize',queueRefresh,{passive:true})}
function installMutationObserver(){const refresh=()=>{if(!document.hidden)queueRefresh()};window.addEventListener('powder:view-changed',refresh,{passive:true});window.addEventListener('powder:world-state',refresh,{passive:true});window.addEventListener('powder:economy-state',refresh,{passive:true});window.addEventListener('powder:candy-updated',refresh,{passive:true})}
function installGlobalDiagnostics(){window.addEventListener('error',e=>{const runtime=e.target===window||!!e.error||!!e.message;if(!runtime){const target=e.target,src=target?.currentSrc||target?.src||target?.href||'';if(src)console.warn('[Powder asset]',src);return}document.documentElement.dataset.v132RuntimeError='1';console.error('[Powder runtime]',e.error||e.message||'Unknown runtime error')},{capture:true});window.addEventListener('unhandledrejection',e=>{document.documentElement.dataset.v132RuntimeError='1';console.error('[Powder promise]',e.reason)})}
function boot(){if(ready)return;if(!app()||!window.POWDER_DATA)return setTimeout(boot,80);ready=true;installSaveFlush();installOverflowObserver();installMutationObserver();installGlobalDiagnostics();refresh();console.info('[Powder 18.2.6 Recovery / Image-GPU Integrated Runtime ready]',{version:VERSION,save:app()?.getSaveHealth?.(),world:world()?.getSaveHealth?.()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.POWDER_STABILITY_V132={version:VERSION,refresh:queueRefresh,getHealth:health};
})();
