import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const VERSION='21.7.8',BASE=10,STEP_MS=6000,OPEN=['active','waiting','sudden'];
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store"};
const out=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'X-Powder-Domain-Reliability':VERSION}}),num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d,now=()=>new Date().toISOString();
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({ok:false,error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,anon=Deno.env.get('SUPABASE_ANON_KEY')||'',auth=req.headers.get('Authorization')||'',token=auth.replace(/^Bearer\s+/i,'');const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error:ue}=await db.auth.getUser(token);if(ue||!user)return out({ok:false,error:'Phiên đăng nhập không hợp lệ.'},401);let body:any={};try{body=await req.json()}catch{return out({ok:false,error:'JSON không hợp lệ.'},400)}const op=String(body.op||body.action||'').toLowerCase();
async function forward(payload:any){const r=await fetch(url+'/functions/v1/powder-domain-clash-v2170',{method:'POST',headers:{Authorization:auth,apikey:anon,'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));return{status:r.status,data:{...d,reliabilityVersion:VERSION,authorityVersion:d?.authorityVersion||'21.7.0'}}}
async function clash(id:string){const {data,error}=await db.from('pvp_domain_clashes_v2170').select('*').eq('id',id).maybeSingle();if(error)throw error;return data}
async function openByMatch(matchId:string){const {data,error}=await db.from('pvp_domain_clashes_v2170').select('*').eq('match_id',matchId).in('status',OPEN).gt('expires_at',now()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data}
async function catchBase(c:any){if(!c||c.status==='resolved'||c.phase!=='base')return c;for(const uid of [String(c.player_a),String(c.player_b)])for(let guard=0;guard<BASE;guard++){c=await clash(c.id);if(!c||c.phase!=='base'||c.status==='resolved')break;const isA=String(c.player_a)===uid,field=isA?'ready_index_a':'ready_index_b',timeField=isA?'ready_at_a':'ready_at_b',idx=num(c[field],-1);if(idx<0||idx>=BASE)break;const ready=new Date(c[timeField]).getTime();if(!Number.isFinite(ready)||Date.now()-ready<=STEP_MS)break;const {data:existing}=await db.from('pvp_domain_clash_answers_v2170').select('question_index').eq('clash_id',c.id).eq('user_id',uid).eq('question_index',idx).maybeSingle();if(!existing){const ins=await db.from('pvp_domain_clash_answers_v2170').insert({clash_id:c.id,user_id:uid,question_index:idx,choice:null,correct:false,server_response_ms:STEP_MS,timed_out:true});if(ins.error&&String(ins.error.code)!=='23505')throw ins.error}const nextReady=new Date(ready+STEP_MS).toISOString(),patch:any={updated_at:now(),[field]:idx+1,[timeField]:nextReady};const up=await db.from('pvp_domain_clashes_v2170').update(patch).eq('id',c.id).eq(field,idx).select('*').maybeSingle();if(up.error)throw up.error;c=up.data||await clash(c.id)}return c}
async function catchForBody(){let c:any=null;if(body.clashId)c=await clash(String(body.clashId));else if(body.matchId)c=await openByMatch(String(body.matchId));if(c)await catchBase(c)}
async function recovered(matchId:string){const {data:ps,error}=await db.from('pvp_match_players').select('user_id,expansion_state').eq('match_id',matchId);if(error)throw error;const mine=(ps||[]).find((x:any)=>String(x.user_id)===user.id),other=(ps||[]).find((x:any)=>String(x.user_id)!==user.id);const a=String(mine?.expansion_state?.domainClashV2170?.clashId||''),b=String(other?.expansion_state?.domainClashV2170?.clashId||'');if(!a||a!==b)return null;const c=await clash(a);if(!c||c.status!=='resolved')return null;const f=await forward({op:'status',clashId:a});return{status:f.status,data:{...f.data,active:true,recovered:true,recoveredClashId:a}}}
try{if(op==='active'||op==='discover'){const matchId=String(body.matchId||'');if(matchId){const rec=await recovered(matchId);if(rec)return out(rec.data,rec.status)}}await catchForBody();const f=await forward(body);return out(f.data,f.status)}catch(e:any){console.error('powder-domain-clash-v2178',e);return out({ok:false,authority:true,reliabilityVersion:VERSION,code:'DOMAIN_RELIABILITY_ERROR',error:e?.message||String(e)},500)}});