import { createClient } from "npm:@supabase/supabase-js@2";
import { enforceAdminAccessV20160 } from "../_shared/admin-security-v20160.ts";
const VERSION='20.15.0',BUILD='powder-20.15.0-disaster-recovery-backup-validation';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'X-Powder-DR-Admin-Version':VERSION}});
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405);const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});try{
 const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const {data:{user},error:ue}=await db.auth.getUser(jwt);if(ue||!user?.email)return out({error:'Phiên Admin không hợp lệ.'},401);const email=user.email.toLowerCase();const {data:a}=await db.from('admin_allowlist').select('role,active').eq('email',email).maybeSingle();if(!a?.active||!['owner','admin','support'].includes(String(a.role)))return out({error:'Không đủ quyền Disaster Recovery.'},403);const role=String(a.role),body=await req.json().catch(()=>({})),action=String(body.action||'state'),channel=body.channel==='staging'?'staging':'production',buildId=String(body.buildId||BUILD).slice(0,180);const owner=()=>{if(role!=='owner')throw Object.assign(new Error('Chỉ Owner được ARM/DISARM Disaster Recovery Gate.'),{status:403})};
 const state=async()=>{const [{data:posture,error:pe},{data:evidence,error:ee},{data:audit,error:ae},{data:cfg,error:ce}]=await Promise.all([db.rpc('powder_dr_posture_v20150',{p_channel:channel,p_build:buildId}),db.from('disaster_recovery_evidence_v20150').select('id,channel,build_id,runner_revision,backup_provider,backup_artifact_sha256,backup_size_bytes,backup_created_at,restore_started_at,restore_completed_at,rpo_minutes,rto_minutes,restore_environment,isolated_restore,source_read_only,schema_source_sha256,schema_restore_sha256,table_digests,post_restore_smoke,failure_injection,rollback_validation,evidence_sha256,calculated_pass,failure_reasons,ingested_at').eq('channel',channel).eq('build_id',buildId).order('ingested_at',{ascending:false}).limit(20),db.from('disaster_recovery_audit_v20150').select('*').eq('channel',channel).order('created_at',{ascending:false}).limit(30),db.from('disaster_recovery_config_v20150').select('*').eq('channel',channel).single()]);if(pe||ee||ae||ce)throw pe||ee||ae||ce;return{ok:true,version:VERSION,role,channel,buildId,posture,evidence:evidence||[],audit:audit||[],config:cfg,evidenceIngestConfigured:(Deno.env.get('POWDER_DR_EVIDENCE_TOKEN')||'').length>=24,serverTime:new Date().toISOString()}};
 await enforceAdminAccessV20160({req,db,jwt,userId:user.id,email,role:role,functionName:'powder-admin-disaster-recovery',action:action});
 if(action==='state')return out(await state());
 if(action==='set_enabled'){owner();const enabled=body.enabled===true;const {data,error}=await db.rpc('powder_dr_set_enabled_v20150',{p_channel:channel,p_enabled:enabled,p_actor:email});if(error)throw error;await db.from('admin_audit_logs').insert({admin_user_id:user.id,admin_email:email,action:'disaster_recovery_20150_gate_enabled',details:{version:VERSION,channel,buildId,enabled}});return out({ok:true,result:data,state:await state()});}
 return out({error:'Action không hợp lệ. 20.15 không cho Admin tự nhập PASS; evidence chỉ được ingest từ external isolated-restore runner.'},400);
}catch(e:any){console.error('[powder-admin-disaster-recovery 20.15]',e);return out({error:String(e?.message||e)},Number(e?.status)||500)}});
