import { createClient } from "npm:@supabase/supabase-js@2";
import { enforceAdminAccessV20160 } from "../_shared/admin-security-v20160.ts";
const VERSION='20.14.0',BUILD='powder-20.14.0-production-load-soak-testing';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'X-Powder-Load-Soak-Version':VERSION}});
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405);const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});try{
 const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const {data:{user},error:ue}=await db.auth.getUser(jwt);if(ue||!user?.email)return out({error:'Phiên Admin không hợp lệ.'},401);const email=user.email.toLowerCase();const {data:a}=await db.from('admin_allowlist').select('role,active').eq('email',email).maybeSingle();if(!a?.active||!['owner','admin'].includes(String(a.role)))return out({error:'Không đủ quyền Load & Soak.'},403);const role=String(a.role),body=await req.json().catch(()=>({})),action=String(body.action||'state'),channel=body.channel==='staging'?'staging':'production',buildId=String(body.buildId||BUILD).slice(0,180);const owner=()=>{if(role!=='owner')throw Object.assign(new Error('Chỉ Owner được ARM/DISARM Load & Soak Gate.'),{status:403})};
 const state=async()=>{const [{data:posture,error:pe},{data:evidence,error:ee},{data:audit,error:ae}]=await Promise.all([db.rpc('powder_load_soak_posture_v20140',{p_channel:channel,p_build:buildId}),db.from('load_soak_evidence_v20140').select('id,channel,build_id,profile,runner_revision,scenario_sha256,evidence_sha256,started_at,completed_at,duration_seconds,total_requests,peak_vus,error_rate,p50_ms,p95_ms,p99_ms,throughput_rps,max_db_pool_pct,server_memory_growth_pct,scenario_counts,integrity,degrade,metrics_source,metrics_source_revision,calculated_pass,failure_reasons,ingested_at').eq('channel',channel).eq('build_id',buildId).order('completed_at',{ascending:false}).limit(30),db.from('load_soak_audit_v20140').select('*').eq('channel',channel).order('created_at',{ascending:false}).limit(30)]);if(pe||ee||ae)throw pe||ee||ae;return{ok:true,version:VERSION,role,channel,buildId,posture,evidence:evidence||[],audit:audit||[],evidenceIngestConfigured:(Deno.env.get('POWDER_LOAD_EVIDENCE_TOKEN')||'').length>=24,serverTime:new Date().toISOString()}};
 await enforceAdminAccessV20160({req,db,jwt,userId:user.id,email,role:role,functionName:'powder-admin-load-soak',action:action});
 if(action==='state')return out(await state());
 if(action==='set_enabled'){owner();const enabled=body.enabled===true;const {data,error}=await db.rpc('powder_load_soak_set_enabled_v20140',{p_channel:channel,p_enabled:enabled,p_actor:email});if(error)throw error;await db.from('admin_audit_logs').insert({admin_user_id:user.id,admin_email:email,action:'load_soak_20140_gate_enabled',details:{version:VERSION,channel,enabled}});return out({ok:true,result:data,state:await state()});}
 return out({error:'Action không hợp lệ. Evidence PASS chỉ được ingest bởi external runner token; Admin không thể tự nhập PASS.'},400);
}catch(e:any){console.error('[powder-admin-load-soak 20.14]',e);return out({error:String(e?.message||e)},Number(e?.status)||500)}});
