import { createClient } from "npm:@supabase/supabase-js@2";
import { enforceAdminAccessV20160 } from "../_shared/admin-security-v20160.ts";
const VERSION='20.5.0';
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'X-Powder-Admin-Version':VERSION}});
const clean=(v:unknown)=>String(v??'').trim().replace(/[(),%_]/g,' ').slice(0,80),num=(v:unknown,a:number,b:number)=>Math.max(a,Math.min(b,Math.trunc(Number(v)||0)));
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Method not allowed'},405);const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});try{
 const jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const {data:{user},error:ue}=await db.auth.getUser(jwt);if(ue||!user?.email)return out({error:'Phiên đăng nhập không hợp lệ.'},401);const email=user.email.toLowerCase();const {data:allow}=await db.from('admin_allowlist').select('role,active').eq('email',email).maybeSingle();if(!allow?.active||!['owner','admin','support'].includes(String(allow.role)))return out({error:'Tài khoản này không có quyền quản trị Powder.'},403);const role=String(allow.role),b=await req.json().catch(()=>({})),action=String(b.action||'dashboard');const need=(r:string[])=>{if(!r.includes(role))throw Object.assign(new Error('Bạn không có quyền thực hiện thao tác này.'),{status:403})};
 const prof=async(id:string)=>{const {data,error}=await db.from('profiles').select('*').eq('id',id).maybeSingle();if(error||!data)throw Object.assign(new Error('Không tìm thấy người chơi.'),{status:404});return data};
 const save=async(id:string)=>{const {data,error}=await db.from('player_saves').select('*').eq('user_id',id).maybeSingle();if(error)throw error;return data};
 const bootstrap=async(id:string)=>{await db.rpc('powder_economy_bootstrap',{p_user:id,p_starter:null});await db.rpc('powder_world_bootstrap',{p_user:id})};
 const audit=async(name:string,p:any,details:any={})=>db.from('admin_audit_logs').insert({admin_user_id:user.id,admin_email:email,action:name,target_user_id:p?.id||null,target_uid:p?.tamer_uid||'',details:{version:VERSION,role,...details}});
 const summary=(s:any,e:any,p:any,pows:number,artifacts:number,equipment:number)=>{const m=s?.save_data?.main||{};return{rank:Number(p?.rank??m.rank??0),coins:Number(e?.coins||0),knowledge:Number(e?.knowledge||0),powCandy:Number(e?.pow_candy||0),elementCoin:Number(e?.element_coin||0),artifactTickets:Number(e?.artifact_tickets||0),powballs:e?.powballs||{},ownedPows:pows,artifactCount:artifacts,equipmentCount:equipment,lessonsDone:Array.isArray(m.lessonsDone)?m.lessonsDone.length:0,wins:Number(p?.wins??m.wins??0),tamerExp:Number(p?.tamer_exp??m.exp??0),mastery:Number(p?.mastery??m.mastery??0),firstZh:Number(p?.first_zh||0),firstEn:Number(p?.first_en||0),promotionPending:p?.promotion_pending??null,team:Array.isArray(m.team)?m.team:[],activePowId:m.activePowId||null,saveVersion:Number(m.saveVersion||s?.schema_version||0),revision:Number(s?.revision||0),appVersion:s?.app_version||'',updatedAt:s?.updated_at||null,deviceId:s?.device_id||''}};
 await enforceAdminAccessV20160({req,db,jwt,userId:user.id,email,role:role,functionName:'powder-admin',action:action});
 if(action==='me')return out({ok:true,admin:{id:user.id,email,role}});
 if(action==='dashboard'){const since=new Date(Date.now()-7*86400000).toISOString();const [t,n7,su,ba,sv,txs,arts]=await Promise.all([db.from('profiles').select('id',{count:'exact',head:true}),db.from('profiles').select('id',{count:'exact',head:true}).gte('created_at',since),db.from('profiles').select('id',{count:'exact',head:true}).eq('game_status','suspended'),db.from('profiles').select('id',{count:'exact',head:true}).eq('game_status','banned'),db.from('player_saves').select('user_id',{count:'exact',head:true}),db.from('economy_transactions').select('id',{count:'exact',head:true}),db.from('player_artifacts').select('instance_id',{count:'exact',head:true})]);const {data:recent}=await db.from('profiles').select('id,tamer_uid,display_name,email,game_status,created_at,updated_at').order('created_at',{ascending:false}).limit(6);return out({ok:true,admin:{email,role},stats:{players:t.count||0,new7:n7.count||0,suspended:su.count||0,banned:ba.count||0,cloudSaves:sv.count||0,transactions:txs.count||0,artifacts:arts.count||0},recent:recent||[]})}
 if(action==='players'){const q=clean(b.search),status=String(b.status||'all'),limit=num(b.limit,1,100)||30,offset=num(b.offset,0,100000);let query=db.from('profiles').select('id,tamer_uid,display_name,email,game_status,moderation_reason,moderation_until,created_at,updated_at,last_admin_action_at',{count:'exact'}).order('created_at',{ascending:false}).range(offset,offset+limit-1);if(q)query=query.or(`tamer_uid.ilike.%${q}%,display_name.ilike.%${q}%,email.ilike.%${q}%`);if(['active','suspended','banned'].includes(status))query=query.eq('game_status',status);const {data,error,count}=await query;if(error)throw error;const ids=(data||[]).map((x:any)=>x.id);const sm=new Map(),em=new Map(),tm=new Map(),pc=new Map<string,number>(),ac=new Map<string,number>(),ec=new Map<string,number>();if(ids.length){const [ss,es,ts,ps,as,eqs]=await Promise.all([db.from('player_saves').select('user_id,save_data,revision,app_version,updated_at,device_id').in('user_id',ids),db.from('player_economy').select('*').in('user_id',ids),db.from('tamer_progress').select('*').in('user_id',ids),db.from('player_pows').select('user_id').in('user_id',ids),db.from('player_artifacts').select('user_id').in('user_id',ids),db.from('player_equipment').select('user_id,copies').in('user_id',ids)]);for(const x of ss.data||[])sm.set(x.user_id,x);for(const x of es.data||[])em.set(x.user_id,x);for(const x of ts.data||[])tm.set(x.user_id,x);for(const x of ps.data||[])pc.set(x.user_id,(pc.get(x.user_id)||0)+1);for(const x of as.data||[])ac.set(x.user_id,(ac.get(x.user_id)||0)+1);for(const x of eqs.data||[])ec.set(x.user_id,(ec.get(x.user_id)||0)+Number(x.copies||0));}return out({ok:true,total:count||0,players:(data||[]).map((p:any)=>({...p,save:summary(sm.get(p.id),em.get(p.id),tm.get(p.id),pc.get(p.id)||0,ac.get(p.id)||0,ec.get(p.id)||0)}))})}
 if(action==='player'){const id=String(b.userId||''),p=await prof(id);const [s,e,tp,pows,arts,eqs,au,logs,txs]=await Promise.all([save(id),db.from('player_economy').select('*').eq('user_id',id).maybeSingle().then(x=>x.data),db.from('tamer_progress').select('*').eq('user_id',id).maybeSingle().then(x=>x.data),db.from('player_pows').select('pow_id,stars,level,pow_exp,shards,copies,shiny,source,obtained_at').eq('user_id',id).order('obtained_at').then(x=>x.data||[]),db.from('player_artifacts').select('instance_id,artifact_id,upgrade_level,is_locked,is_favorite,equipped_by,acquired_at').eq('user_id',id).order('acquired_at',{ascending:false}).then(x=>x.data||[]),db.from('player_equipment').select('equipment_id,copies,acquired_at').eq('user_id',id).then(x=>x.data||[]),db.auth.admin.getUserById(id),db.from('admin_audit_logs').select('id,admin_email,action,details,created_at').eq('target_user_id',id).order('created_at',{ascending:false}).limit(20).then(x=>x.data||[]),db.from('economy_transactions').select('id,tx_type,delta,result,created_at').eq('user_id',id).order('created_at',{ascending:false}).limit(30).then(x=>x.data||[])]);const eqCount=eqs.reduce((a:any,x:any)=>a+Number(x.copies||0),0);return out({ok:true,player:{...p,auth:{createdAt:au.data?.user?.created_at||null,lastSignInAt:au.data?.user?.last_sign_in_at||null,emailConfirmedAt:au.data?.user?.email_confirmed_at||null},save:summary(s,e,tp,pows.length,arts.length,eqCount),economy:e,progress:tp,pows,artifacts:arts,equipment:eqs,transactions:txs,logs},permissions:{mutate:['owner','admin'].includes(role),exportSave:role==='owner'}})}
 if(action==='adjust_resource'){need(['owner','admin']);const id=String(b.userId||''),resource=String(b.resource||''),delta=num(b.delta,-1000000,1000000),reason=String(b.reason||'').trim().slice(0,300);const cols:any={coins:'coins',knowledge:'knowledge',powCandy:'pow_candy',artifactTickets:'artifact_tickets',elementCoin:'element_coin'};if(!cols[resource]||!delta)return out({error:'Giá trị điều chỉnh không hợp lệ.'},400);await bootstrap(id);const p=await prof(id),{data:e}=await db.from('player_economy').select('*').eq('user_id',id).single(),col=cols[resource],before=Number(e?.[col]||0),after=Math.max(0,before+delta);const {error}=await db.from('player_economy').update({[col]:after,updated_at:new Date().toISOString()}).eq('user_id',id);if(error)throw error;await db.from('economy_transactions').insert({user_id:id,tx_key:`admin:${crypto.randomUUID()}`,tx_type:'admin_adjust',delta:{[resource]:after-before},result:{resource,before,after,reason,admin:email}});await audit('adjust_resource',p,{resource,delta:after-before,before,after,reason});return out({ok:true,before,after})}
 if(action==='set_rank'){need(['owner','admin']);const id=String(b.userId||''),rank=num(b.rank,0,6);await bootstrap(id);const p=await prof(id),{data:tp}=await db.from('tamer_progress').select('rank').eq('user_id',id).single(),before=Number(tp?.rank||0);const {error}=await db.from('tamer_progress').update({rank,promotion_pending:null,promotion_exam_score:null,updated_at:new Date().toISOString()}).eq('user_id',id);if(error)throw error;await audit('set_rank',p,{before,after:rank,reason:String(b.reason||'')});return out({ok:true,before,after:rank})}
 if(action==='rename'){need(['owner','admin']);const id=String(b.userId||''),name=String(b.name||'').trim().slice(0,32);if(name.length<2)return out({error:'Tên Tamer phải có ít nhất 2 ký tự.'},400);const p=await prof(id);const {error}=await db.from('profiles').update({display_name:name,last_admin_action_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await audit('rename',p,{before:p.display_name,after:name});return out({ok:true,name})}
 if(action==='moderate'){need(['owner','admin']);const id=String(b.userId||''),status=String(b.status||'active'),reason=String(b.reason||'').trim().slice(0,500);if(!['active','suspended','banned'].includes(status))return out({error:'Trạng thái không hợp lệ.'},400);if(status!=='active'&&!reason)return out({error:'Khóa/cấm cần lý do.'},400);const p=await prof(id);const {error}=await db.from('profiles').update({game_status:status,moderation_reason:status==='active'?'':reason,moderation_until:null,last_admin_action_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await audit('moderate',p,{before:p.game_status,after:status,reason});return out({ok:true,status})}
 if(action==='export_save'){need(['owner']);const id=String(b.userId||''),p=await prof(id),s=await save(id);await audit('export_save',p,{revision:s?.revision||0});return out({ok:true,uid:p.tamer_uid,save:s?.save_data||null,revision:s?.revision||0})}
 if(action==='logs'){const {data,error}=await db.from('admin_audit_logs').select('id,admin_email,action,target_user_id,target_uid,details,created_at').order('created_at',{ascending:false}).limit(num(b.limit,1,100)||50);if(error)throw error;return out({ok:true,logs:data||[]})}
 return out({error:'Action không tồn tại.'},400)
}catch(e:any){console.error(e);return out({error:e?.message||'Admin server error'},Number(e?.status)||500)}});
