create or replace function public.powder_official_launch_preflight_v2000(p_channel text default 'production',p_build text default 'powder-20.0.0-official-launch-gate',p_manifest_hash text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; b public.release_builds; ch public.release_channels; ro public.release_rollout_v1950; integ jsonb:='{}'::jsonb; obs jsonb:='{}'::jsonb; sec jsonb:='{}'::jsonb; active_pilot int:=0; recent_pilot int:=0; pvp_matches bigint:=0; crashes bigint:=0; low_fps int:=0; save_bad int:=0; critical int:=0; high int:=0; evidence_pass int:=0; ops_critical int:=0; ops_high int:=0; rollback_ok boolean:=false; candidate_ok boolean:=false; integrity_ok boolean:=false; pilot_ok boolean:=false; rollout_ok boolean:=false; evidence_ok boolean:=false; incident_ok boolean:=false; obs_ok boolean:=true; sec_ok boolean:=false; ready boolean:=false;
begin
 select * into ch from public.release_channels where channel=c; select * into ro from public.release_rollout_v1950 where channel=c; select * into b from public.release_builds where channel=c and build_id=p_build limit 1;
 begin integ:=public.powder_integrity_snapshot_v1960(); exception when others then integ:=jsonb_build_object('ready',false,'error',sqlerrm); end;
 begin obs:=public.powder_observability_rollout_gate_v2020(c,p_build); exception when others then obs:=jsonb_build_object('enabled',true,'healthy',false,'sufficient',false,'error',sqlerrm); end;
 begin sec:=public.powder_security_posture_v2030(); exception when others then sec:=jsonb_build_object('ready',false,'error',sqlerrm); end;
 select count(*) into active_pilot from public.pilot_cohort_v1970 where active=true;
 select count(distinct d.user_id),coalesce(sum(d.pvp_matches),0),coalesce(sum(d.crash_count),0),count(*) filter(where d.avg_fps>0 and d.avg_fps<30),count(*) filter(where coalesce((d.last_summary->>'savePass')::boolean,true)=false) into recent_pilot,pvp_matches,crashes,low_fps,save_bad from public.pilot_device_health_v1970 d join public.pilot_cohort_v1970 c0 on c0.user_id=d.user_id and c0.active=true where d.last_seen_at>=now()-interval '7 days';
 select count(*) filter(where i.severity='critical'),count(*) filter(where i.severity='high') into critical,high from public.pilot_issue_reports_v1970 i join public.pilot_cohort_v1970 c0 on c0.user_id=i.user_id and c0.active=true where i.status in ('open','triaged');
 select count(*) filter(where severity='critical'),count(*) filter(where severity='high') into ops_critical,ops_high from public.official_incidents_v2010 where channel=c and status in ('open','monitoring');
 select count(*) into evidence_pass from public.official_launch_evidence_v2000 e where e.channel=c and e.build_id=p_build and e.status='pass' and e.check_key in ('load_1960','recovery_1940','polish_1980','freeze_1990') and (p_manifest_hash='' or e.manifest_hash=p_manifest_hash) and e.evidence_sha256 ~ '^[0-9a-fA-F]{64}$';
 if ro.rollback_target_build<>'' then rollback_ok:=exists(select 1 from public.release_builds rb where rb.channel=c and rb.build_id=ro.rollback_target_build and rb.checksum ~ '^[0-9a-fA-F]{64}$' and rb.build_id<>p_build); end if;
 candidate_ok:=b.build_id is not null and b.version='20.0.0' and b.status in ('candidate','active') and b.checksum ~ '^[0-9a-fA-F]{64}$'; integrity_ok:=coalesce((integ->>'ready')::boolean,false)=true; pilot_ok:=active_pilot between 20 and 50 and recent_pilot>=20 and pvp_matches>=20 and crashes=0 and low_fps=0 and save_bad=0 and critical=0 and high=0; rollout_ok:=coalesce(ro.emergency_mode,'normal')='normal' and coalesce(ch.hard_maintenance,false)=false; evidence_ok:=evidence_pass=4; incident_ok:=ops_critical=0 and ops_high=0; obs_ok:=case when coalesce((obs->>'enabled')::boolean,false) then coalesce((obs->>'healthy')::boolean,false) and coalesce((obs->>'sufficient')::boolean,false) else true end; sec_ok:=coalesce((sec->>'ready')::boolean,false)=true;
 ready:=candidate_ok and integrity_ok and pilot_ok and rollout_ok and evidence_ok and rollback_ok and incident_ok and obs_ok and sec_ok;
 return jsonb_build_object('version','20.0.0','channel',c,'buildId',p_build,'manifestHash',p_manifest_hash,'ready',ready,'checks',jsonb_build_object('candidate',candidate_ok,'integrity',integrity_ok,'realPilot',pilot_ok,'rolloutNormal',rollout_ok,'evidence4of4',evidence_ok,'rollbackTarget',rollback_ok,'liveOpsIncidents',incident_ok,'observability',obs_ok,'securityPosture',sec_ok),'candidate',case when b.build_id is null then null else to_jsonb(b) end,'release',case when ch.channel is null then null else to_jsonb(ch) end,'rollout',case when ro.channel is null then null else to_jsonb(ro) end,'integrity',integ,'pilot',jsonb_build_object('activePilot',active_pilot,'recentPilot7d',recent_pilot,'pvpMatches',pvp_matches,'crashes',crashes,'lowFpsDevices',low_fps,'saveBadDevices',save_bad,'openCritical',critical,'openHigh',high),'liveOps',jsonb_build_object('openCritical',ops_critical,'openHigh',ops_high,'blockers',ops_critical+ops_high),'observability',obs,'security',sec,'evidencePass',evidence_pass,'checkedAt',now());
end$$;
