-- Powder 21.0.1 · Launch Stabilization & Post-Launch Guardrails
-- Server-derived health evidence, optional automatic HALT, incident posture, safe resume.
begin;

create table if not exists public.post_launch_guardrails_v21001(
  channel text primary key check(channel in ('production','staging')),
  build_id text not null default 'powder-21.0.1-launch-stabilization',
  manifest_hash text not null default '',
  artifact_sha256 text not null default '',
  rollback_target_build text not null default 'powder-21.0.0-official-production',
  enabled boolean not null default true,
  armed boolean not null default false,
  warmup_minutes integer not null default 30 check(warmup_minutes between 5 and 240),
  evidence_max_age_minutes integer not null default 15 check(evidence_max_age_minutes between 5 and 120),
  min_sample_count integer not null default 1000 check(min_sample_count between 100 and 10000000),
  error_rate_max double precision not null default 0.01 check(error_rate_max between 0 and 0.25),
  p95_max_ms integer not null default 1500 check(p95_max_ms between 100 and 30000),
  p99_max_ms integer not null default 2500 check(p99_max_ms between 100 and 60000),
  crash_rate_max double precision not null default 0.003 check(crash_rate_max between 0 and 0.25),
  save_conflict_max integer not null default 0 check(save_conflict_max between 0 and 100000),
  transaction_blocker_max integer not null default 0 check(transaction_blocker_max between 0 and 100000),
  state text not null default 'hold' check(state in ('healthy','hold','degraded')),
  last_reason text not null default '',
  armed_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by text not null default ''
);
insert into public.post_launch_guardrails_v21001(channel) values('production'),('staging') on conflict(channel) do nothing;

create table if not exists public.post_launch_health_evidence_v21001(
  id bigint generated by default as identity primary key,
  channel text not null check(channel in ('production','staging')),
  build_id text not null,
  manifest_hash text not null,
  artifact_sha256 text not null,
  sample_count bigint not null,
  error_rate double precision not null,
  p95_ms integer not null,
  p99_ms integer not null,
  crash_rate double precision not null,
  save_conflicts integer not null default 0,
  transaction_blockers integer not null default 0,
  critical_open integer not null default 0,
  high_open integer not null default 0,
  reliability_mode text not null default 'normal',
  circuit_state text not null default 'closed',
  status text not null check(status in ('pass','hold')),
  reasons jsonb not null default '[]'::jsonb,
  evidence_sha256 text not null,
  runner_revision text not null default '',
  checked_at timestamptz not null default now(),
  checked_by text not null default 'ci'
);
create index if not exists post_launch_health_v21001_latest_idx on public.post_launch_health_evidence_v21001(channel,build_id,checked_at desc);

create table if not exists public.post_launch_incidents_v21001(
  id bigint generated by default as identity primary key,
  channel text not null check(channel in ('production','staging')),
  build_id text not null,
  severity text not null check(severity in ('critical','high','medium','low')),
  category text not null,
  status text not null default 'open' check(status in ('open','monitoring','resolved')),
  summary text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by text not null default 'system',
  resolved_at timestamptz,
  resolved_by text not null default ''
);
create index if not exists post_launch_incidents_v21001_open_idx on public.post_launch_incidents_v21001(channel,build_id,status,severity,created_at desc);

alter table public.post_launch_guardrails_v21001 enable row level security;
alter table public.post_launch_health_evidence_v21001 enable row level security;
alter table public.post_launch_incidents_v21001 enable row level security;
revoke all on public.post_launch_guardrails_v21001, public.post_launch_health_evidence_v21001, public.post_launch_incidents_v21001 from public,anon,authenticated;
grant select,insert,update on public.post_launch_guardrails_v21001, public.post_launch_health_evidence_v21001, public.post_launch_incidents_v21001 to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.powder_post_launch_record_health_v21001(
  p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,
  p_sample_count bigint,p_error_rate double precision,p_p95_ms integer,p_p99_ms integer,
  p_crash_rate double precision,p_save_conflicts integer,p_transaction_blockers integer,
  p_critical_open integer,p_high_open integer,p_reliability_mode text,p_circuit_state text,
  p_evidence_sha256 text,p_runner_revision text,p_actor text default 'ci'
) returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; cfg public.post_launch_guardrails_v21001; rs jsonb:='[]'::jsonb; st text:='pass'; nowts timestamptz:=now();
begin
  if p_build<>'powder-21.0.1-launch-stabilization' then raise exception 'LS21001_BUILD_MISMATCH'; end if;
  if p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' or p_evidence_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'LS21001_HASH_INVALID'; end if;
  if p_sample_count<0 or p_error_rate<0 or p_error_rate>1 or p_crash_rate<0 or p_crash_rate>1 or p_p95_ms<0 or p_p99_ms<0 or p_save_conflicts<0 or p_transaction_blockers<0 or p_critical_open<0 or p_high_open<0 then raise exception 'LS21001_METRIC_INVALID'; end if;
  select * into cfg from public.post_launch_guardrails_v21001 where channel=c for update;
  if cfg.build_id<>p_build then raise exception 'LS21001_CONFIG_BUILD_MISMATCH'; end if;
  if cfg.manifest_hash<>'' and lower(cfg.manifest_hash)<>lower(p_manifest_hash) then raise exception 'LS21001_MANIFEST_DRIFT'; end if;
  if cfg.artifact_sha256<>'' and lower(cfg.artifact_sha256)<>lower(p_artifact_sha256) then raise exception 'LS21001_ARTIFACT_DRIFT'; end if;
  if p_sample_count<cfg.min_sample_count then st:='hold';rs:=rs||jsonb_build_array('insufficient_sample');end if;
  if p_error_rate>cfg.error_rate_max then st:='hold';rs:=rs||jsonb_build_array('error_rate');end if;
  if p_p95_ms>cfg.p95_max_ms then st:='hold';rs:=rs||jsonb_build_array('p95');end if;
  if p_p99_ms>cfg.p99_max_ms then st:='hold';rs:=rs||jsonb_build_array('p99');end if;
  if p_crash_rate>cfg.crash_rate_max then st:='hold';rs:=rs||jsonb_build_array('crash_rate');end if;
  if p_save_conflicts>cfg.save_conflict_max then st:='hold';rs:=rs||jsonb_build_array('save_conflict');end if;
  if p_transaction_blockers>cfg.transaction_blocker_max then st:='hold';rs:=rs||jsonb_build_array('transaction_blocker');end if;
  if p_critical_open>0 then st:='hold';rs:=rs||jsonb_build_array('critical_incident');end if;
  if p_high_open>0 then st:='hold';rs:=rs||jsonb_build_array('high_incident');end if;
  if lower(coalesce(p_reliability_mode,''))<>'normal' then st:='hold';rs:=rs||jsonb_build_array('reliability_mode');end if;
  if lower(coalesce(p_circuit_state,''))<>'closed' then st:='hold';rs:=rs||jsonb_build_array('circuit_state');end if;
  insert into public.post_launch_health_evidence_v21001(channel,build_id,manifest_hash,artifact_sha256,sample_count,error_rate,p95_ms,p99_ms,crash_rate,save_conflicts,transaction_blockers,critical_open,high_open,reliability_mode,circuit_state,status,reasons,evidence_sha256,runner_revision,checked_at,checked_by)
  values(c,p_build,lower(p_manifest_hash),lower(p_artifact_sha256),p_sample_count,p_error_rate,p_p95_ms,p_p99_ms,p_crash_rate,p_save_conflicts,p_transaction_blockers,p_critical_open,p_high_open,p_reliability_mode,p_circuit_state,st,rs,lower(p_evidence_sha256),left(coalesce(p_runner_revision,''),120),nowts,left(coalesce(p_actor,'ci'),160));
  update public.post_launch_guardrails_v21001 set manifest_hash=lower(p_manifest_hash),artifact_sha256=lower(p_artifact_sha256),state=case when st='pass' then 'healthy' else 'hold' end,last_reason=case when st='pass' then '' else rs::text end,updated_at=nowts,updated_by=left(coalesce(p_actor,'ci'),160) where channel=c;
  if cfg.enabled and cfg.armed and st='hold' then
    update public.release_rollout_v1950 set emergency_mode='halt',emergency_message='Launch Stabilization 21.0.1 automatic HOLD: '||rs::text,updated_at=nowts,updated_by='guardrail-v21001' where channel=c;
    insert into public.post_launch_incidents_v21001(channel,build_id,severity,category,summary,evidence,created_by) values(c,p_build,case when p_critical_open>0 or p_crash_rate>cfg.crash_rate_max*2 then 'critical' else 'high' end,'health_guardrail','21.0.1 post-launch health crossed configured threshold',jsonb_build_object('reasons',rs,'sampleCount',p_sample_count,'errorRate',p_error_rate,'p95Ms',p_p95_ms,'p99Ms',p_p99_ms,'crashRate',p_crash_rate),'guardrail-v21001');
  end if;
  return jsonb_build_object('ok',true,'status',st,'reasons',rs,'automaticHaltApplied',cfg.enabled and cfg.armed and st='hold','checkedAt',nowts);
end $function$;

create or replace function public.powder_post_launch_posture_v21001(p_channel text default 'production',p_build text default 'powder-21.0.1-launch-stabilization')
returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; cfg public.post_launch_guardrails_v21001; ev public.post_launch_health_evidence_v21001; ro public.release_rollout_v1950; crit int:=0;hi int:=0;fresh boolean:=false;healthy boolean:=false;
begin
 select * into cfg from public.post_launch_guardrails_v21001 where channel=c;
 select * into ev from public.post_launch_health_evidence_v21001 where channel=c and build_id=p_build order by checked_at desc limit 1;
 select * into ro from public.release_rollout_v1950 where channel=c;
 select count(*) filter(where severity='critical'),count(*) filter(where severity='high') into crit,hi from public.post_launch_incidents_v21001 where channel=c and build_id=p_build and status<>'resolved';
 fresh:=ev.id is not null and ev.checked_at>=now()-make_interval(mins=>coalesce(cfg.evidence_max_age_minutes,15));
 healthy:=coalesce(cfg.enabled,false) and fresh and ev.status='pass' and crit=0 and hi=0 and coalesce(ro.emergency_mode,'normal')='normal';
 return jsonb_build_object('version','21.0.1','buildId',p_build,'healthy',healthy,'armed',coalesce(cfg.armed,false),'state',coalesce(cfg.state,'hold'),'freshEvidence',fresh,'latestStatus',ev.status,'checkedAt',ev.checked_at,'openCritical',crit,'openHigh',hi,'emergencyMode',coalesce(ro.emergency_mode,'normal'),'rollbackTargetBuild',coalesce(cfg.rollback_target_build,''),'automaticRollback',false,'automaticHalt',coalesce(cfg.armed,false));
end $function$;

create or replace function public.powder_post_launch_arm_v21001(p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_rollback_target text,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;
begin
 if p_build<>'powder-21.0.1-launch-stabilization' or p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'LS21001_ARM_BINDING_INVALID'; end if;
 if coalesce(p_rollback_target,'')='' or p_rollback_target=p_build then raise exception 'LS21001_ROLLBACK_TARGET_INVALID'; end if;
 update public.post_launch_guardrails_v21001 set build_id=p_build,manifest_hash=lower(p_manifest_hash),artifact_sha256=lower(p_artifact_sha256),rollback_target_build=p_rollback_target,enabled=true,armed=true,state='hold',armed_at=now(),last_reason='Awaiting fresh post-launch server evidence',updated_at=now(),updated_by=p_actor where channel=c;
 return public.powder_post_launch_posture_v21001(c,p_build);
end $function$;

create or replace function public.powder_post_launch_emergency_hold_v21001(p_channel text,p_build text,p_reason text,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;nowts timestamptz:=now();
begin
 if p_build<>'powder-21.0.1-launch-stabilization' then raise exception 'LS21001_BUILD_MISMATCH';end if;
 update public.post_launch_guardrails_v21001 set state='hold',last_reason=left(coalesce(p_reason,'Manual emergency HOLD'),500),updated_at=nowts,updated_by=p_actor where channel=c;
 update public.release_rollout_v1950 set emergency_mode='halt',emergency_message='21.0.1 manual HOLD: '||left(coalesce(p_reason,'Owner hold'),300),updated_at=nowts,updated_by=p_actor where channel=c;
 insert into public.post_launch_incidents_v21001(channel,build_id,severity,category,summary,created_by) values(c,p_build,'high','manual_hold',left(coalesce(p_reason,'Owner emergency HOLD'),800),p_actor);
 return public.powder_post_launch_posture_v21001(c,p_build);
end $function$;

create or replace function public.powder_post_launch_resume_v21001(p_channel text,p_build text,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; cfg public.post_launch_guardrails_v21001;ev public.post_launch_health_evidence_v21001;crit int;hi int;
begin
 select * into cfg from public.post_launch_guardrails_v21001 where channel=c for update;
 select * into ev from public.post_launch_health_evidence_v21001 where channel=c and build_id=p_build order by checked_at desc limit 1;
 select count(*) filter(where severity='critical'),count(*) filter(where severity='high') into crit,hi from public.post_launch_incidents_v21001 where channel=c and build_id=p_build and status<>'resolved';
 if not cfg.armed then raise exception 'LS21001_NOT_ARMED';end if;
 if ev.id is null or ev.status<>'pass' or ev.checked_at<now()-make_interval(mins=>cfg.evidence_max_age_minutes) then raise exception 'LS21001_FRESH_PASS_REQUIRED';end if;
 if crit>0 or hi>0 then raise exception 'LS21001_INCIDENTS_OPEN';end if;
 update public.release_rollout_v1950 set emergency_mode='normal',emergency_message='',updated_at=now(),updated_by=p_actor where channel=c;
 update public.post_launch_guardrails_v21001 set state='healthy',last_reason='',updated_at=now(),updated_by=p_actor where channel=c;
 return public.powder_post_launch_posture_v21001(c,p_build);
end $function$;

insert into public.security_admin_surfaces_v20160(function_name,allowed_roles,notes) values
('powder-admin-launch-stability',array['owner','admin','support'],'21.0.1 post-launch health posture; mutations are Owner+AAL2.')
on conflict(function_name) do update set allowed_roles=excluded.allowed_roles,notes=excluded.notes,updated_at=now();
insert into public.security_critical_actions_v20160(function_name,action,require_owner,require_aal2) values
('powder-admin-launch-stability','arm',true,true),
('powder-admin-launch-stability','emergency_hold',true,true),
('powder-admin-launch-stability','resume',true,true)
on conflict(function_name,action) do update set require_owner=excluded.require_owner,require_aal2=excluded.require_aal2;

revoke all on function public.powder_post_launch_record_health_v21001(text,text,text,text,bigint,double precision,integer,integer,double precision,integer,integer,integer,integer,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_post_launch_posture_v21001(text,text) from public,anon,authenticated;
revoke all on function public.powder_post_launch_arm_v21001(text,text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_post_launch_emergency_hold_v21001(text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_post_launch_resume_v21001(text,text,text) from public,anon,authenticated;
grant execute on function public.powder_post_launch_record_health_v21001(text,text,text,text,bigint,double precision,integer,integer,double precision,integer,integer,integer,integer,text,text,text,text,text) to service_role;
grant execute on function public.powder_post_launch_posture_v21001(text,text) to service_role;
grant execute on function public.powder_post_launch_arm_v21001(text,text,text,text,text,text) to service_role;
grant execute on function public.powder_post_launch_emergency_hold_v21001(text,text,text,text) to service_role;
grant execute on function public.powder_post_launch_resume_v21001(text,text,text) to service_role;
commit;
