-- Powder 21.0.0 · Official Production readiness evidence over frozen Gold Master predecessor
begin;
create table if not exists public.official_production_config_v21000(id smallint primary key default 1 check(id=1),enabled boolean not null default false,evidence_max_age_hours int not null default 24 check(evidence_max_age_hours between 1 and 168),updated_at timestamptz not null default now(),updated_by text not null default '');
insert into public.official_production_config_v21000(id) values(1) on conflict(id) do nothing;
create table if not exists public.official_production_evidence_v21000(id bigserial primary key,channel text not null default 'production',build_id text not null,manifest_hash text not null,artifact_sha256 text not null,deployment_pass boolean not null default false,manual_smoke_pass boolean not null default false,load_soak_pass boolean not null default false,disaster_recovery_pass boolean not null default false,security_pass boolean not null default false,save_integrity_pass boolean not null default false,rollback_pass boolean not null default false,critical_count int not null default 0,high_count int not null default 0,pass boolean not null default false,evidence_sha256 text not null,runner_revision text not null default '',created_at timestamptz not null default now(),created_by text not null default 'ci');
create index if not exists official_production_evidence_v21000_idx on public.official_production_evidence_v21000(channel,build_id,created_at desc);
create or replace function public.powder_official_production_record_v21000(p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_deployment boolean,p_manual boolean,p_load boolean,p_dr boolean,p_security boolean,p_save boolean,p_rollback boolean,p_critical int,p_high int,p_evidence_sha256 text,p_runner_revision text,p_actor text default 'ci') returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;crit int:=greatest(0,coalesce(p_critical,0));hi int:=greatest(0,coalesce(p_high,0));ok boolean;rid bigint;
begin if p_build<>'powder-21.0.0-official-production' then raise exception 'OFF21000_BUILD_MISMATCH';end if;if p_manifest_hash!~'^[0-9a-fA-F]{16,64}$' or p_artifact_sha256!~'^[0-9a-fA-F]{64}$' or p_evidence_sha256!~'^[0-9a-fA-F]{64}$' then raise exception 'OFF21000_HASH_INVALID';end if;ok:=coalesce(p_deployment,false) and coalesce(p_manual,false) and coalesce(p_load,false) and coalesce(p_dr,false) and coalesce(p_security,false) and coalesce(p_save,false) and coalesce(p_rollback,false) and crit=0 and hi=0;insert into public.official_production_evidence_v21000(channel,build_id,manifest_hash,artifact_sha256,deployment_pass,manual_smoke_pass,load_soak_pass,disaster_recovery_pass,security_pass,save_integrity_pass,rollback_pass,critical_count,high_count,pass,evidence_sha256,runner_revision,created_by) values(c,p_build,lower(p_manifest_hash),lower(p_artifact_sha256),coalesce(p_deployment,false),coalesce(p_manual,false),coalesce(p_load,false),coalesce(p_dr,false),coalesce(p_security,false),coalesce(p_save,false),coalesce(p_rollback,false),crit,hi,ok,lower(p_evidence_sha256),left(coalesce(p_runner_revision,''),160),left(coalesce(p_actor,'ci'),160)) returning id into rid;return jsonb_build_object('ok',true,'id',rid,'pass',ok,'critical',crit,'high',hi,'recordedAt',now());end $function$;
create or replace function public.powder_official_production_posture_v21000(p_channel text default 'production',p_build text default 'powder-21.0.0-official-production',p_manifest_hash text default '') returns jsonb language plpgsql security definer set search_path=public as $function$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;cfg public.official_production_config_v21000;e public.official_production_evidence_v21000;pred public.release_canary_state_v20200;pred_stage public.release_canary_stage_evidence_v20200;gm jsonb:='{}'::jsonb;fresh boolean:=false;pred_ok boolean:=false;ready boolean:=false;
begin select * into cfg from public.official_production_config_v21000 where id=1;select * into e from public.official_production_evidence_v21000 where channel=c and build_id=p_build and (p_manifest_hash='' or manifest_hash=lower(p_manifest_hash)) order by created_at desc limit 1;select * into pred from public.release_canary_state_v20200 where channel=c and build_id='powder-20.20.0-gold-master';select * into pred_stage from public.release_canary_stage_evidence_v20200 where channel=c and build_id='powder-20.20.0-gold-master' and rollout_percent=100;begin gm:=public.powder_gold_master_posture_v20200(c,'powder-20.20.0-gold-master',coalesce(pred.manifest_hash,''));exception when others then gm:=jsonb_build_object('ready',false,'error',sqlerrm);end;fresh:=e.id is not null and e.created_at>=now()-make_interval(hours=>coalesce(cfg.evidence_max_age_hours,24));pred_ok:=pred.rollout_percent=100 and pred.finalized_at is not null and pred_stage.status='pass' and coalesce((gm->>'ready')::boolean,false);ready:=coalesce(cfg.enabled,false) and fresh and pred_ok and coalesce(e.pass,false) and coalesce(e.critical_count,1)=0 and coalesce(e.high_count,1)=0;return jsonb_build_object('version','21.0.0','ready',ready,'armed',coalesce(cfg.enabled,false),'fresh',fresh,'predecessorReady',pred_ok,'predecessorGoldMaster',gm,'evidence',case when e.id is null then null else to_jsonb(e) end,'checks',jsonb_build_object('goldMaster20_20Finalized',pred_ok,'deployment',coalesce(e.deployment_pass,false),'manualSmoke',coalesce(e.manual_smoke_pass,false),'loadSoak',coalesce(e.load_soak_pass,false),'disasterRecovery',coalesce(e.disaster_recovery_pass,false),'security',coalesce(e.security_pass,false),'saveIntegrity',coalesce(e.save_integrity_pass,false),'rollback',coalesce(e.rollback_pass,false),'criticalZero',coalesce(e.critical_count,1)=0,'highZero',coalesce(e.high_count,1)=0),'checkedAt',now());end $function$;
alter table public.official_production_config_v21000 enable row level security;alter table public.official_production_evidence_v21000 enable row level security;revoke all on public.official_production_config_v21000,public.official_production_evidence_v21000 from public,anon,authenticated;grant select,insert,update,delete on public.official_production_config_v21000,public.official_production_evidence_v21000 to service_role;grant usage,select on sequence public.official_production_evidence_v21000_id_seq to service_role;revoke all on function public.powder_official_production_record_v21000(text,text,text,text,boolean,boolean,boolean,boolean,boolean,boolean,boolean,int,int,text,text,text),public.powder_official_production_posture_v21000(text,text,text) from public,anon,authenticated;grant execute on function public.powder_official_production_record_v21000(text,text,text,text,boolean,boolean,boolean,boolean,boolean,boolean,boolean,int,int,text,text,text),public.powder_official_production_posture_v21000(text,text,text) to service_role;
commit;
