create table if not exists public.security_probe_v2030(
  probe_key text primary key,
  created_at timestamptz not null default now()
);
alter table public.security_probe_v2030 enable row level security;
revoke all on public.security_probe_v2030 from public,anon,authenticated;
grant select,insert,delete on public.security_probe_v2030 to service_role;

create table if not exists public.security_review_snapshots_v2030(
  id bigint generated by default as identity primary key,
  posture jsonb not null,
  created_at timestamptz not null default now(),
  created_by text not null default ''
);
alter table public.security_review_snapshots_v2030 enable row level security;
revoke all on public.security_review_snapshots_v2030 from public,anon,authenticated;
grant select,insert on public.security_review_snapshots_v2030 to service_role;

create or replace function public.powder_security_duplicate_probe_v2030()
returns jsonb language plpgsql security definer set search_path=public as $$
declare k text:='probe-'||gen_random_uuid()::text; duplicate_blocked boolean:=false;
begin
  insert into public.security_probe_v2030(probe_key) values(k);
  begin insert into public.security_probe_v2030(probe_key) values(k); exception when unique_violation then duplicate_blocked:=true; end;
  delete from public.security_probe_v2030 where probe_key=k;
  return jsonb_build_object('version','20.3.0','duplicateBlocked',duplicate_blocked,'cleaned',not exists(select 1 from public.security_probe_v2030 where probe_key=k));
end$$;

create or replace function public.powder_security_posture_v2030()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  critical_tables text[]:=array['admin_allowlist','account_devices','daily_reward_claims','learning_reward_claims','mail_claims','player_saves','pvp_action_receipts_v1870','pvp_domain_action_receipts_v1880','official_incidents_v2010','observability_api_samples_v2020'];
  sensitive_rpcs text[]:=array['powder_cloud_save_commit_v1828','powder_rate_guard_v1831','powder_pvp_action_v1870','powder_pvp_action_v1880','powder_claim_daily_reward','powder_claim_mail','powder_learning_reward','powder_battle_reward','powder_boss_reward'];
  rls_missing int:=0; direct_write int:=0; rpc_client_exec int:=0; invalid_admin_roles int:=0;
  reward_guards boolean:=false; pvp_guards boolean:=false; device_guard boolean:=false; cloud_guard boolean:=false; rate_guard boolean:=false;
  probe jsonb:='{}'::jsonb; ready boolean:=false;
begin
  select count(*) into rls_missing from unnest(critical_tables) t(name)
  where not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=t.name and c.relrowsecurity=true);

  select count(*) into direct_write from unnest(critical_tables) t(name)
  where has_table_privilege('anon',format('public.%I',t.name),'INSERT,UPDATE,DELETE')
     or has_table_privilege('authenticated',format('public.%I',t.name),'INSERT,UPDATE,DELETE');

  select count(*) into rpc_client_exec from information_schema.routine_privileges rp
  where rp.specific_schema='public' and rp.routine_name=any(sensitive_rpcs) and rp.grantee in ('anon','authenticated') and rp.privilege_type='EXECUTE';

  select count(*) into invalid_admin_roles from public.admin_allowlist where active=true and role not in ('owner','admin','support');

  reward_guards :=
    exists(select 1 from pg_constraint where conrelid='public.daily_reward_claims'::regclass and contype in ('p','u')) and
    exists(select 1 from pg_constraint where conrelid='public.learning_reward_claims'::regclass and contype in ('p','u')) and
    exists(select 1 from pg_constraint where conrelid='public.mail_claims'::regclass and contype in ('p','u'));
  pvp_guards :=
    exists(select 1 from pg_constraint where conrelid='public.pvp_action_receipts_v1870'::regclass and contype in ('p','u')) and
    exists(select 1 from pg_constraint where conrelid='public.pvp_domain_action_receipts_v1880'::regclass and contype in ('p','u'));
  device_guard := exists(select 1 from information_schema.columns where table_schema='public' and table_name='account_devices' and column_name='revoked_at');
  cloud_guard := exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='powder_cloud_save_commit_v1828' and grantee='service_role' and privilege_type='EXECUTE') and not exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='powder_cloud_save_commit_v1828' and grantee in ('anon','authenticated'));
  rate_guard := exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='powder_rate_guard_v1831' and grantee='service_role' and privilege_type='EXECUTE') and not exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='powder_rate_guard_v1831' and grantee in ('anon','authenticated'));
  begin probe:=public.powder_security_duplicate_probe_v2030(); exception when others then probe:=jsonb_build_object('duplicateBlocked',false,'cleaned',false,'error',sqlerrm); end;
  ready:=rls_missing=0 and direct_write=0 and rpc_client_exec=0 and invalid_admin_roles=0 and reward_guards and pvp_guards and device_guard and cloud_guard and rate_guard and coalesce((probe->>'duplicateBlocked')::boolean,false) and coalesce((probe->>'cleaned')::boolean,false);
  return jsonb_build_object('version','20.3.0','ready',ready,'checkedAt',now(),
    'counts',jsonb_build_object('rlsMissing',rls_missing,'directWriteViolations',direct_write,'sensitiveRpcClientExec',rpc_client_exec,'invalidAdminRoles',invalid_admin_roles),
    'guards',jsonb_build_object('rewardIdempotency',reward_guards,'pvpIdempotency',pvp_guards,'deviceRevoke',device_guard,'cloudCasServiceOnly',cloud_guard,'rateGuardServiceOnly',rate_guard,'duplicateProbe',probe),
    'adminRoles',(select coalesce(jsonb_object_agg(role,cnt),'{}'::jsonb) from (select role,count(*)::int cnt from public.admin_allowlist where active=true group by role) x));
end$$;

revoke all on function public.powder_security_duplicate_probe_v2030() from public,anon,authenticated;
revoke all on function public.powder_security_posture_v2030() from public,anon,authenticated;
grant execute on function public.powder_security_duplicate_probe_v2030() to service_role;
grant execute on function public.powder_security_posture_v2030() to service_role;
