-- Powder 20.5.0 · Player Support / GM Console
create table if not exists public.support_cases_v2050 (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'general' check (category in ('account','save','reward','pvp','event','technical','report','general')),
  priority text not null default 'normal' check (priority in ('low','normal','high','critical')),
  subject text not null check (char_length(subject) between 3 and 160),
  description text not null default '',
  status text not null default 'open' check (status in ('open','investigating','waiting_player','waiting_admin','resolved','closed')),
  assigned_to text not null default '',
  created_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text not null default ''
);
create index if not exists support_cases_v2050_user_idx on public.support_cases_v2050(user_id,updated_at desc);
create index if not exists support_cases_v2050_status_idx on public.support_cases_v2050(status,priority,updated_at desc);

create table if not exists public.support_case_notes_v2050 (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.support_cases_v2050(id) on delete cascade,
  author_email text not null default '',
  author_role text not null default 'support',
  note text not null check (char_length(note) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index if not exists support_case_notes_v2050_case_idx on public.support_case_notes_v2050(case_id,created_at desc);

create table if not exists public.support_compensation_requests_v2050 (
  id uuid primary key default gen_random_uuid(),
  case_id uuid references public.support_cases_v2050(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Bồi thường hỗ trợ Powder',
  reason text not null default '',
  rewards jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected','sent')),
  requested_by text not null default '',
  requested_at timestamptz not null default now(),
  reviewed_by text not null default '',
  reviewed_at timestamptz,
  review_note text not null default '',
  campaign_id uuid references public.mail_campaigns(id) on delete set null,
  batch_id uuid references public.compensation_batches(id) on delete set null
);
create index if not exists support_comp_req_user_idx on public.support_compensation_requests_v2050(user_id,requested_at desc);
create index if not exists support_comp_req_status_idx on public.support_compensation_requests_v2050(status,requested_at desc);

alter table public.support_cases_v2050 enable row level security;
alter table public.support_case_notes_v2050 enable row level security;
alter table public.support_compensation_requests_v2050 enable row level security;
revoke all on public.support_cases_v2050,public.support_case_notes_v2050,public.support_compensation_requests_v2050 from public,anon,authenticated;
grant select,insert,update,delete on public.support_cases_v2050,public.support_case_notes_v2050,public.support_compensation_requests_v2050 to service_role;
grant usage,select on sequence public.support_case_notes_v2050_id_seq to service_role;

drop policy if exists support_cases_v2050_deny_client on public.support_cases_v2050;
create policy support_cases_v2050_deny_client on public.support_cases_v2050 for all to anon,authenticated using(false) with check(false);
drop policy if exists support_case_notes_v2050_deny_client on public.support_case_notes_v2050;
create policy support_case_notes_v2050_deny_client on public.support_case_notes_v2050 for all to anon,authenticated using(false) with check(false);
drop policy if exists support_comp_req_v2050_deny_client on public.support_compensation_requests_v2050;
create policy support_comp_req_v2050_deny_client on public.support_compensation_requests_v2050 for all to anon,authenticated using(false) with check(false);

create or replace function public.powder_support_reward_valid_v2050(p jsonb)
returns boolean language plpgsql immutable as $$
declare k text; v int;begin
 if p is null or jsonb_typeof(p)<>'object' then return false; end if;
 for k in select jsonb_object_keys(p) loop
  if k not in ('coins','knowledge','powCandyCommon','powCandyRare','powCandyLegendary','artifactTickets','elementCoin','powballs') then return false; end if;
 end loop;
 if coalesce((p->>'coins')::int,0) not between 0 and 100000 then return false; end if;
 if coalesce((p->>'knowledge')::int,0) not between 0 and 1000 then return false; end if;
 if coalesce((p->>'powCandyCommon')::int,0) not between 0 and 1000 then return false; end if;
 if coalesce((p->>'powCandyRare')::int,0) not between 0 and 500 then return false; end if;
 if coalesce((p->>'powCandyLegendary')::int,0) not between 0 and 100 then return false; end if;
 if coalesce((p->>'artifactTickets')::int,0) not between 0 and 100 then return false; end if;
 if coalesce((p->>'elementCoin')::int,0) not between 0 and 10000 then return false; end if;
 if jsonb_typeof(p->'powballs') is not null and jsonb_typeof(p->'powballs')<>'object' then return false; end if;
 if jsonb_typeof(p->'powballs')='object' then
  for k,v in select key,value::int from jsonb_each_text(p->'powballs') loop
   if k not in ('common','rare','super_rare','epic','legendary','mythic','ancient') or v not between 0 and 10 then return false; end if;
  end loop;
 end if;
 return p <> '{}'::jsonb;
exception when others then return false;end$$;

create or replace function public.powder_support_approve_compensation_v2050(p_request uuid,p_admin text,p_note text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare r public.support_compensation_requests_v2050; mc public.mail_campaigns; cb public.compensation_batches; backup_id uuid;begin
 select * into r from public.support_compensation_requests_v2050 where id=p_request for update;
 if not found then raise exception 'COMPENSATION_REQUEST_NOT_FOUND'; end if;
 if r.status='sent' and r.campaign_id is not null then return jsonb_build_object('ok',true,'idempotent',true,'requestId',r.id,'campaignId',r.campaign_id,'batchId',r.batch_id); end if;
 if r.status<>'pending' then raise exception 'COMPENSATION_REQUEST_NOT_PENDING'; end if;
 if not public.powder_support_reward_valid_v2050(r.rewards) then raise exception 'COMPENSATION_REWARD_INVALID'; end if;
 backup_id:=public.powder_create_player_backup(r.user_id,'pre_compensation','Support compensation request '||r.id::text,p_admin);
 insert into public.mail_campaigns(title,body,audience,recipient_user_id,rewards,starts_at,expires_at,active,created_by)
 values(left(r.title,120),left(coalesce(nullif(r.reason,''),'Bồi thường từ bộ phận hỗ trợ Powder.'),3000),'user',r.user_id,r.rewards,now(),now()+interval '14 days',true,left(p_admin,160)) returning * into mc;
 insert into public.compensation_batches(title,reason,audience,recipient_user_id,rewards,campaign_id,created_by)
 values(left(r.title,120),left(r.reason,500),'user',r.user_id,r.rewards,mc.id,left(p_admin,160)) returning * into cb;
 update public.support_compensation_requests_v2050 set status='sent',reviewed_by=left(p_admin,160),reviewed_at=now(),review_note=left(coalesce(p_note,''),1000),campaign_id=mc.id,batch_id=cb.id where id=r.id;
 return jsonb_build_object('ok',true,'idempotent',false,'requestId',r.id,'campaignId',mc.id,'batchId',cb.id,'backupId',backup_id);
end$$;
revoke all on function public.powder_support_reward_valid_v2050(jsonb) from public,anon,authenticated;
revoke all on function public.powder_support_approve_compensation_v2050(uuid,text,text) from public,anon,authenticated;
grant execute on function public.powder_support_reward_valid_v2050(jsonb) to service_role;
grant execute on function public.powder_support_approve_compensation_v2050(uuid,text,text) to service_role;

create or replace function public.powder_support_posture_v2050()
returns jsonb language plpgsql security definer set search_path=public as $$
declare direct_writes int:=0; rpc_client int:=0; invalid_roles int:=0;begin
 select count(*) into direct_writes from information_schema.role_table_grants where table_schema='public' and table_name in ('support_cases_v2050','support_case_notes_v2050','support_compensation_requests_v2050') and grantee in ('anon','authenticated') and privilege_type in ('INSERT','UPDATE','DELETE');
 select count(*) into rpc_client from information_schema.routine_privileges where routine_schema='public' and routine_name in ('powder_support_approve_compensation_v2050') and grantee in ('PUBLIC','anon','authenticated') and privilege_type='EXECUTE';
 select count(*) into invalid_roles from public.admin_allowlist where active=true and role not in ('owner','admin','support');
 return jsonb_build_object('version','20.5.0','ready',direct_writes=0 and rpc_client=0 and invalid_roles=0,'counts',jsonb_build_object('directWrites',direct_writes,'sensitiveRpcClientExec',rpc_client,'invalidAdminRoles',invalid_roles),'checkedAt',now());
end$$;
revoke all on function public.powder_support_posture_v2050() from public,anon,authenticated;
grant execute on function public.powder_support_posture_v2050() to service_role;
