-- Powder 21.0.3 · Live Observability & SLO Enforcement
-- Server-derived SLO/SLI, multi-window burn-rate, error-budget guard and safe HALT.
begin;

create table if not exists public.live_slo_config_v21003(
  channel text primary key check(channel in ('production','staging')),
  build_id text not null default 'powder-21.0.3-live-observability-slo',
  manifest_hash text not null default '',
  artifact_sha256 text not null default '',
  enabled boolean not null default true,
  armed boolean not null default false,
  evidence_max_age_minutes integer not null default 15 check(evidence_max_age_minutes between 5 and 120),
  min_requests_60m integer not null default 500 check(min_requests_60m between 100 and 10000000),
  availability_target double precision not null default 0.995 check(availability_target between 0.90 and 0.99999),
  p95_target_ms integer not null default 1500 check(p95_target_ms between 100 and 30000),
  p99_target_ms integer not null default 2500 check(p99_target_ms between 100 and 60000),
  fast_burn_max double precision not null default 4.0 check(fast_burn_max between 1 and 100),
  slow_burn_max double precision not null default 2.0 check(slow_burn_max between 1 and 100),
  error_budget_remaining_min double precision not null default 0.25 check(error_budget_remaining_min between 0 and 1),
  state text not null default 'hold' check(state in ('healthy','hold','degraded')),
  last_reason text not null default '',
  armed_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by text not null default ''
);
insert into public.live_slo_config_v21003(channel) values('production'),('staging') on conflict(channel) do nothing;

create table if not exists public.live_slo_snapshots_v21003(
  id bigint generated by default as identity primary key,
  channel text not null check(channel in ('production','staging')),
  build_id text not null,
  manifest_hash text not null,
  artifact_sha256 text not null,
  requests_15m bigint not null default 0,
  requests_60m bigint not null default 0,
  requests_360m bigint not null default 0,
  error_rate_15m double precision not null default 0,
  error_rate_60m double precision not null default 0,
  error_rate_360m double precision not null default 0,
  p95_60m integer not null default 0,
  p99_60m integer not null default 0,
  fast_burn double precision not null default 0,
  slow_burn double precision not null default 0,
  errors_30d bigint not null default 0,
  requests_30d bigint not null default 0,
  error_budget_remaining double precision not null default 1,
  crashes_60m bigint not null default 0,
  save_conflicts_60m bigint not null default 0,
  status text not null check(status in ('pass','hold')),
  reasons jsonb not null default '[]'::jsonb,
  evidence_sha256 text not null,
  checked_at timestamptz not null default now(),
  checked_by text not null default 'slo-v21003'
);
create index if not exists live_slo_snapshots_v21003_latest_idx on public.live_slo_snapshots_v21003(channel,build_id,checked_at desc);

create table if not exists public.live_slo_incidents_v21003(
  id bigint generated by default as identity primary key,
  channel text not null check(channel in ('production','staging')),
  build_id text not null,
  severity text not null check(severity in ('critical','high','medium','low')),
  category text not null,
  status text not null default 'open' check(status in ('open','monitoring','resolved')),
  summary text not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by text not null default 'slo-v21003',
  resolved_at timestamptz,
  resolved_by text not null default ''
);
create index if not exists live_slo_incidents_v21003_open_idx on public.live_slo_incidents_v21003(channel,build_id,status,severity,created_at desc);

alter table public.live_slo_config_v21003 enable row level security;
alter table public.live_slo_snapshots_v21003 enable row level security;
alter table public.live_slo_incidents_v21003 enable row level security;
revoke all on public.live_slo_config_v21003, public.live_slo_snapshots_v21003, public.live_slo_incidents_v21003 from public,anon,authenticated;
grant select,insert,update on public.live_slo_config_v21003, public.live_slo_snapshots_v21003, public.live_slo_incidents_v21003 to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.powder_live_slo_capture_v21003(
  p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_actor text default 'slo-v21003'
) returns jsonb language plpgsql security definer set search_path=public as $f$
declare
  c text:=case when p_channel='staging' then 'staging' else 'production' end;
  cfg public.live_slo_config_v21003; h15 jsonb; h60 jsonb; h360 jsonb;
  req30 bigint:=0; err30 bigint:=0; allowed double precision:=0.005; er15 double precision:=0; er60 double precision:=0; er360 double precision:=0;
  fast double precision:=0; slow double precision:=0; budget double precision:=1; rs jsonb:='[]'::jsonb; st text:='pass'; evsha text; nowts timestamptz:=now();
begin
  if p_build<>'powder-21.0.3-live-observability-slo' then raise exception 'SLO21003_BUILD_MISMATCH'; end if;
  if p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'SLO21003_HASH_INVALID'; end if;
  select * into cfg from public.live_slo_config_v21003 where channel=c for update;
  if cfg.build_id<>p_build then raise exception 'SLO21003_CONFIG_BUILD_MISMATCH'; end if;
  if cfg.manifest_hash<>'' and lower(cfg.manifest_hash)<>lower(p_manifest_hash) then raise exception 'SLO21003_MANIFEST_DRIFT'; end if;
  if cfg.artifact_sha256<>'' and lower(cfg.artifact_sha256)<>lower(p_artifact_sha256) then raise exception 'SLO21003_ARTIFACT_DRIFT'; end if;
  h15:=public.powder_observability_health_v2020(c,p_build,15); h60:=public.powder_observability_health_v2020(c,p_build,60); h360:=public.powder_observability_health_v2020(c,p_build,360);
  er15:=coalesce((h15->>'errorRate')::double precision,0); er60:=coalesce((h60->>'errorRate')::double precision,0); er360:=coalesce((h360->>'errorRate')::double precision,0);
  allowed:=greatest(0.000001,1-cfg.availability_target); fast:=er15/allowed; slow:=er360/allowed;
  select count(*),count(*) filter(where not ok) into req30,err30 from public.observability_api_samples_v2020 where channel=c and build_id=p_build and created_at>=now()-interval '30 days';
  budget:=case when req30<=0 then 1 else greatest(0,1-(err30::double precision/greatest(req30::double precision*allowed,1))) end;
  if coalesce((h60->>'requests')::bigint,0)<cfg.min_requests_60m then st:='hold';rs:=rs||jsonb_build_array('insufficient_60m_sample');end if;
  if coalesce((h60->>'p95Ms')::double precision,0)>cfg.p95_target_ms then st:='hold';rs:=rs||jsonb_build_array('p95_slo');end if;
  if coalesce((h60->>'p99Ms')::double precision,0)>cfg.p99_target_ms then st:='hold';rs:=rs||jsonb_build_array('p99_slo');end if;
  if fast>cfg.fast_burn_max then st:='hold';rs:=rs||jsonb_build_array('fast_burn');end if;
  if slow>cfg.slow_burn_max then st:='hold';rs:=rs||jsonb_build_array('slow_burn');end if;
  if budget<cfg.error_budget_remaining_min then st:='hold';rs:=rs||jsonb_build_array('error_budget_low');end if;
  if coalesce((h60->>'crashes')::bigint,0)>0 then st:='hold';rs:=rs||jsonb_build_array('crash');end if;
  if coalesce((h60->>'saveConflicts')::bigint,0)>0 then st:='hold';rs:=rs||jsonb_build_array('save_conflict');end if;
  evsha:=encode(digest(concat_ws('|',c,p_build,lower(p_manifest_hash),lower(p_artifact_sha256),h15::text,h60::text,h360::text,req30,err30,round(fast::numeric,6),round(slow::numeric,6),round(budget::numeric,6)), 'sha256'),'hex');
  insert into public.live_slo_snapshots_v21003(channel,build_id,manifest_hash,artifact_sha256,requests_15m,requests_60m,requests_360m,error_rate_15m,error_rate_60m,error_rate_360m,p95_60m,p99_60m,fast_burn,slow_burn,errors_30d,requests_30d,error_budget_remaining,crashes_60m,save_conflicts_60m,status,reasons,evidence_sha256,checked_at,checked_by)
  values(c,p_build,lower(p_manifest_hash),lower(p_artifact_sha256),coalesce((h15->>'requests')::bigint,0),coalesce((h60->>'requests')::bigint,0),coalesce((h360->>'requests')::bigint,0),er15,er60,er360,round(coalesce((h60->>'p95Ms')::double precision,0))::int,round(coalesce((h60->>'p99Ms')::double precision,0))::int,fast,slow,err30,req30,budget,coalesce((h60->>'crashes')::bigint,0),coalesce((h60->>'saveConflicts')::bigint,0),st,rs,evsha,nowts,left(coalesce(p_actor,'slo-v21003'),160));
  update public.live_slo_config_v21003 set manifest_hash=lower(p_manifest_hash),artifact_sha256=lower(p_artifact_sha256),state=case when st='pass' then 'healthy' else 'hold' end,last_reason=case when st='pass' then '' else rs::text end,updated_at=nowts,updated_by=left(coalesce(p_actor,'slo-v21003'),160) where channel=c;
  if cfg.enabled and cfg.armed and st='hold' then
    update public.release_rollout_v1950 set emergency_mode='halt',emergency_message='SLO 21.0.3 automatic HOLD: '||rs::text,updated_at=nowts,updated_by='slo-v21003' where channel=c;
    insert into public.live_slo_incidents_v21003(channel,build_id,severity,category,summary,evidence,created_by) values(c,p_build,case when fast>cfg.fast_burn_max*2 or coalesce((h60->>'crashes')::bigint,0)>0 then 'critical' else 'high' end,'slo_breach','21.0.3 SLO/error-budget threshold crossed',jsonb_build_object('reasons',rs,'fastBurn',fast,'slowBurn',slow,'errorBudgetRemaining',budget,'health60m',h60),'slo-v21003');
  end if;
  return jsonb_build_object('ok',true,'status',st,'reasons',rs,'fastBurn',fast,'slowBurn',slow,'errorBudgetRemaining',budget,'evidenceSha256',evsha,'automaticHaltApplied',cfg.enabled and cfg.armed and st='hold','checkedAt',nowts);
end $f$;

create or replace function public.powder_live_slo_posture_v21003(p_channel text default 'production',p_build text default 'powder-21.0.3-live-observability-slo')
returns jsonb language plpgsql security definer set search_path=public as $f$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;cfg public.live_slo_config_v21003;ev public.live_slo_snapshots_v21003;crit int:=0;hi int:=0;fresh boolean:=false;ready boolean:=false;
begin
  select * into cfg from public.live_slo_config_v21003 where channel=c;
  select * into ev from public.live_slo_snapshots_v21003 where channel=c and build_id=p_build order by checked_at desc limit 1;
  select count(*) filter(where severity='critical'),count(*) filter(where severity='high') into crit,hi from public.live_slo_incidents_v21003 where channel=c and build_id=p_build and status<>'resolved';
  fresh:=ev.id is not null and ev.checked_at>=now()-make_interval(mins=>coalesce(cfg.evidence_max_age_minutes,15));
  ready:=coalesce(cfg.armed,false) and fresh and ev.status='pass' and crit=0 and hi=0;
  return jsonb_build_object('version','21.0.3','buildId',p_build,'ready',ready,'armed',coalesce(cfg.armed,false),'state',coalesce(cfg.state,'hold'),'fresh',fresh,'openCritical',crit,'openHigh',hi,'fastBurn',coalesce(ev.fast_burn,0),'slowBurn',coalesce(ev.slow_burn,0),'errorBudgetRemaining',coalesce(ev.error_budget_remaining,1),'p95Ms',coalesce(ev.p95_60m,0),'p99Ms',coalesce(ev.p99_60m,0),'latestCheckedAt',ev.checked_at,'reasons',coalesce(ev.reasons,'[]'::jsonb));
end $f$;

create or replace function public.powder_live_slo_arm_v21003(p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $f$ declare c text:=case when p_channel='staging' then 'staging' else 'production' end;
begin
 if p_build<>'powder-21.0.3-live-observability-slo' or p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'SLO21003_ARM_INVALID';end if;
 update public.live_slo_config_v21003 set build_id=p_build,manifest_hash=lower(p_manifest_hash),artifact_sha256=lower(p_artifact_sha256),armed=true,state='hold',last_reason='Awaiting server-derived SLO evidence',armed_at=now(),updated_at=now(),updated_by=left(coalesce(p_actor,''),160) where channel=c;
 return public.powder_live_slo_posture_v21003(c,p_build);
end $f$;

create or replace function public.powder_live_slo_disarm_v21003(p_channel text,p_build text,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $f$ declare c text:=case when p_channel='staging' then 'staging' else 'production' end;
begin
 if p_build<>'powder-21.0.3-live-observability-slo' then raise exception 'SLO21003_BUILD_MISMATCH';end if;
 update public.live_slo_config_v21003 set armed=false,state='hold',last_reason='SLO Guard DISARMED',updated_at=now(),updated_by=left(coalesce(p_actor,''),160) where channel=c;
 return public.powder_live_slo_posture_v21003(c,p_build);
end $f$;

create or replace function public.powder_live_slo_assert_release_allowed_v21003(p_channel text default 'production',p_build text default 'powder-21.0.3-live-observability-slo')
returns jsonb language plpgsql security definer set search_path=public as $f$ declare p jsonb;
begin p:=public.powder_live_slo_posture_v21003(p_channel,p_build);if coalesce((p->>'ready')::boolean,false) is not true then raise exception 'SLO21003_RELEASE_BLOCKED';end if;return p;end $f$;

-- Register the new Admin surface in the centralized 20.16 security contract.
insert into public.security_admin_surfaces_v20160(function_name,allowed_roles,notes) values
('powder-admin-live-slo',array['admin','owner']::text[],'21.0.3 Live SLO/Error Budget posture and Owner ARM/DISARM')
on conflict(function_name) do update set allowed_roles=excluded.allowed_roles,notes=excluded.notes,updated_at=now();
insert into public.security_critical_actions_v20160(function_name,action,require_owner,require_aal2) values
('powder-admin-live-slo','arm',true,true),('powder-admin-live-slo','disarm',true,true),('powder-admin-live-slo','emergency_hold',true,true)
on conflict(function_name,action) do update set require_owner=excluded.require_owner,require_aal2=excluded.require_aal2;

revoke all on function public.powder_live_slo_capture_v21003(text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_live_slo_posture_v21003(text,text) from public,anon,authenticated;
revoke all on function public.powder_live_slo_arm_v21003(text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_live_slo_disarm_v21003(text,text,text) from public,anon,authenticated;
revoke all on function public.powder_live_slo_assert_release_allowed_v21003(text,text) from public,anon,authenticated;
grant execute on function public.powder_live_slo_capture_v21003(text,text,text,text,text) to service_role;
grant execute on function public.powder_live_slo_posture_v21003(text,text) to service_role;
grant execute on function public.powder_live_slo_arm_v21003(text,text,text,text,text) to service_role;
grant execute on function public.powder_live_slo_disarm_v21003(text,text,text) to service_role;
grant execute on function public.powder_live_slo_assert_release_allowed_v21003(text,text) to service_role;
commit;
