-- Powder 21.0.4 · Capacity Guard & Graceful Degradation
-- Server-derived capacity pressure, admission control, controlled Reliability actuation,
-- hysteresis recovery and fail-closed release/hotfix posture. No gameplay mutations.
begin;

create table if not exists public.capacity_guard_config_v21004(
  channel text primary key check(channel in ('production','staging')),
  build_id text not null default 'powder-21.0.4-capacity-guard',
  manifest_hash text not null default '',
  artifact_sha256 text not null default '',
  armed boolean not null default false,
  state text not null default 'hold' check(state in ('ready','hold')),
  mode text not null default 'normal' check(mode in ('normal','soft','hard')),
  db_warn_pct numeric not null default 70 check(db_warn_pct between 10 and 95),
  db_hard_pct numeric not null default 85 check(db_hard_pct between 20 and 100),
  active_conn_warn_pct numeric not null default 55 check(active_conn_warn_pct between 10 and 95),
  lock_wait_warn integer not null default 4 check(lock_wait_warn between 0 and 10000),
  queue_warn integer not null default 40 check(queue_warn between 0 and 1000000),
  queue_hard integer not null default 150 check(queue_hard between 1 and 1000000),
  p95_warn_ms integer not null default 1200 check(p95_warn_ms between 100 and 10000),
  p95_hard_ms integer not null default 2200 check(p95_hard_ms between 200 and 20000),
  error_warn numeric not null default 0.008 check(error_warn between 0 and .5),
  error_hard numeric not null default 0.02 check(error_hard between 0 and 1),
  good_streak_required integer not null default 3 check(good_streak_required between 1 and 30),
  soft_retry_after_seconds integer not null default 3 check(soft_retry_after_seconds between 1 and 60),
  hard_retry_after_seconds integer not null default 15 check(hard_retry_after_seconds between 1 and 300),
  good_streak integer not null default 0,
  bad_streak integer not null default 0,
  last_reason text not null default '',
  last_capture_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by text not null default ''
);
insert into public.capacity_guard_config_v21004(channel) values('production'),('staging') on conflict(channel) do nothing;

create table if not exists public.capacity_guard_snapshots_v21004(
  id bigint generated by default as identity primary key,
  channel text not null,
  build_id text not null,
  manifest_hash text not null,
  artifact_sha256 text not null,
  db_connections integer not null default 0,
  db_max_connections integer not null default 0,
  db_util_pct numeric not null default 0,
  active_connections integer not null default 0,
  active_conn_pct numeric not null default 0,
  lock_waits integer not null default 0,
  queue_depth integer not null default 0,
  transaction_recovery integer not null default 0,
  reconciliation_open integer not null default 0,
  p95_ms integer not null default 0,
  p99_ms integer not null default 0,
  error_rate numeric not null default 0,
  requests bigint not null default 0,
  capacity_mode text not null check(capacity_mode in ('normal','soft','hard')),
  reliability_mode text not null default 'normal',
  admission_policy jsonb not null default '{}'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  evidence_sha256 text not null,
  checked_at timestamptz not null default now(),
  checked_by text not null default 'capacity-v21004'
);
create index if not exists capacity_guard_snapshots_v21004_latest_idx on public.capacity_guard_snapshots_v21004(channel,build_id,checked_at desc);

create table if not exists public.capacity_guard_events_v21004(
  id bigint generated by default as identity primary key,
  channel text not null,
  build_id text not null,
  event_type text not null,
  before_mode text not null default '',
  after_mode text not null default '',
  reason text not null default '',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  created_by text not null default 'capacity-v21004'
);

alter table public.capacity_guard_config_v21004 enable row level security;
alter table public.capacity_guard_snapshots_v21004 enable row level security;
alter table public.capacity_guard_events_v21004 enable row level security;
revoke all on public.capacity_guard_config_v21004,public.capacity_guard_snapshots_v21004,public.capacity_guard_events_v21004 from public,anon,authenticated;
grant select,insert,update on public.capacity_guard_config_v21004,public.capacity_guard_snapshots_v21004,public.capacity_guard_events_v21004 to service_role;
grant usage,select on all sequences in schema public to service_role;

create or replace function public.powder_capacity_capture_v21004(
  p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_actor text default 'capacity-v21004'
) returns jsonb language plpgsql security definer set search_path=public as $f$
declare
  c text:=case when p_channel='staging' then 'staging' else 'production' end;
  cfg public.capacity_guard_config_v21004; h jsonb:='{}'::jsonb; rel jsonb:='{}'::jsonb;
  dbconn int:=0; dbmax int:=100; activec int:=0; waits int:=0; txq int:=0; recq int:=0; q int:=0;
  dbpct numeric:=0; activepct numeric:=0; p95 int:=0;p99 int:=0;err numeric:=0;req bigint:=0;
  desired text:='normal'; before_mode text:='normal'; final_mode text:='normal'; rel_actor text:=''; rs jsonb:='[]'::jsonb; evhash text; nextgood int:=0; nextbad int:=0;
begin
  if p_build<>'powder-21.0.4-capacity-guard' then raise exception 'CAP21004_BUILD_MISMATCH';end if;
  if p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'CAP21004_HASH_INVALID';end if;
  perform pg_advisory_xact_lock(hashtextextended('capacity-v21004:'||c,0));
  select * into cfg from public.capacity_guard_config_v21004 where channel=c for update;
  if cfg.build_id<>p_build then raise exception 'CAP21004_CONFIG_BUILD_MISMATCH';end if;
  if cfg.manifest_hash<>'' and lower(cfg.manifest_hash)<>lower(p_manifest_hash) then raise exception 'CAP21004_MANIFEST_DRIFT';end if;
  if cfg.artifact_sha256<>'' and lower(cfg.artifact_sha256)<>lower(p_artifact_sha256) then raise exception 'CAP21004_ARTIFACT_DRIFT';end if;

  select count(*)::int into dbconn from pg_stat_activity where datname=current_database();
  select count(*)::int into activec from pg_stat_activity where datname=current_database() and state='active';
  select count(*)::int into waits from pg_stat_activity where datname=current_database() and wait_event_type='Lock';
  begin dbmax:=current_setting('max_connections')::int; exception when others then dbmax:=100; end;
  dbpct:=case when dbmax>0 then round(dbconn::numeric*100/dbmax,2) else 0 end;
  activepct:=case when dbmax>0 then round(activec::numeric*100/dbmax,2) else 0 end;
  if to_regclass('public.transaction_recovery_queue_v2090') is not null then select count(*)::int into txq from public.transaction_recovery_queue_v2090 where status in ('queued','investigating');end if;
  if to_regclass('public.reconciliation_cases_v20120') is not null then select count(*)::int into recq from public.reconciliation_cases_v20120 where status in ('open','investigating','repair_proposed','repair_approved');end if;
  q:=txq+recq;
  begin h:=public.powder_observability_health_v2020(c,p_build,15); exception when others then h:=jsonb_build_object('requests',0,'errorRate',1,'p95Ms',99999,'p99Ms',99999,'error',sqlerrm); end;
  req:=coalesce((h->>'requests')::bigint,0);err:=coalesce((h->>'errorRate')::numeric,1);p95:=coalesce((h->>'p95Ms')::int,99999);p99:=coalesce((h->>'p99Ms')::int,99999);
  begin rel:=public.powder_reliability_public_status_v2080(); exception when others then rel:='{}'::jsonb; end;
  select coalesce(updated_by,'') into rel_actor from public.reliability_state_v2080 where channel=c;
  before_mode:=coalesce(cfg.mode,'normal');

  if dbpct>=cfg.db_hard_pct or q>=cfg.queue_hard or p95>=cfg.p95_hard_ms or err>=cfg.error_hard then desired:='hard';end if;
  if desired='normal' and (dbpct>=cfg.db_warn_pct or activepct>=cfg.active_conn_warn_pct or waits>=cfg.lock_wait_warn or q>=cfg.queue_warn or p95>=cfg.p95_warn_ms or err>=cfg.error_warn) then desired:='soft';end if;
  if dbpct>=cfg.db_warn_pct then rs:=rs||jsonb_build_array('db_util');end if;
  if activepct>=cfg.active_conn_warn_pct then rs:=rs||jsonb_build_array('active_connections');end if;
  if waits>=cfg.lock_wait_warn and cfg.lock_wait_warn>0 then rs:=rs||jsonb_build_array('lock_waits');end if;
  if q>=cfg.queue_warn then rs:=rs||jsonb_build_array('queue_depth');end if;
  if p95>=cfg.p95_warn_ms then rs:=rs||jsonb_build_array('p95');end if;
  if err>=cfg.error_warn then rs:=rs||jsonb_build_array('error_rate');end if;

  if desired='normal' then nextgood:=cfg.good_streak+1;nextbad:=0;final_mode:=case when cfg.mode<>'normal' and nextgood<cfg.good_streak_required then cfg.mode else 'normal' end;
  else nextgood:=0;nextbad:=cfg.bad_streak+1;final_mode:=case when desired='hard' then 'hard' when cfg.mode='hard' then 'hard' else 'soft' end;end if;

  evhash:=encode(digest(concat_ws('|',c,p_build,dbconn,dbmax,activec,waits,q,p95,p99,err,req,final_mode,now()::date)::bytea,'sha256'),'hex');
  insert into public.capacity_guard_snapshots_v21004(channel,build_id,manifest_hash,artifact_sha256,db_connections,db_max_connections,db_util_pct,active_connections,active_conn_pct,lock_waits,queue_depth,transaction_recovery,reconciliation_open,p95_ms,p99_ms,error_rate,requests,capacity_mode,reliability_mode,admission_policy,reasons,evidence_sha256,checked_by)
  values(c,p_build,lower(p_manifest_hash),lower(p_artifact_sha256),dbconn,dbmax,dbpct,activec,activepct,waits,q,txq,recq,p95,p99,err,req,final_mode,coalesce(rel->>'mode','normal'),jsonb_build_object('normal','allow','soft','defer_background','hard','reject_noncritical','retryAfterSeconds',case when final_mode='hard' then cfg.hard_retry_after_seconds else cfg.soft_retry_after_seconds end),rs,evhash,left(coalesce(p_actor,'capacity-v21004'),160));

  update public.capacity_guard_config_v21004 set mode=final_mode,state=case when armed and final_mode='normal' then 'ready' else 'hold' end,good_streak=nextgood,bad_streak=nextbad,last_reason=case when final_mode='normal' then '' else rs::text end,last_capture_at=now(),updated_at=now(),updated_by=left(coalesce(p_actor,'capacity-v21004'),160) where channel=c returning * into cfg;
  if before_mode<>final_mode then insert into public.capacity_guard_events_v21004(channel,build_id,event_type,before_mode,after_mode,reason,evidence,created_by) values(c,p_build,'capacity_transition',before_mode,final_mode,rs::text,jsonb_build_object('dbUtilPct',dbpct,'activeConnPct',activepct,'lockWaits',waits,'queueDepth',q,'p95Ms',p95,'p99Ms',p99,'errorRate',err,'requests',req,'evidenceSha256',evhash),left(coalesce(p_actor,'capacity-v21004'),160));end if;

  if cfg.armed then
    if final_mode='soft' and coalesce(rel->>'mode','normal')='normal' then perform public.powder_reliability_apply_mode_v2080(c,'degraded','Capacity 21.0.4 soft pressure',p_build,'capacity-v21004',jsonb_build_object('capacityMode',final_mode,'reasons',rs,'dbUtilPct',dbpct,'queueDepth',q,'p95Ms',p95,'errorRate',err));end if;
    if final_mode='hard' and coalesce(rel->>'mode','normal') not in ('read_only','emergency') then perform public.powder_reliability_apply_mode_v2080(c,'read_only','Capacity 21.0.4 hard pressure',p_build,'capacity-v21004',jsonb_build_object('capacityMode',final_mode,'reasons',rs,'dbUtilPct',dbpct,'queueDepth',q,'p95Ms',p95,'errorRate',err));end if;
    if final_mode='normal' and coalesce(rel->>'mode','normal') in ('degraded','read_only') and rel_actor='capacity-v21004' then perform public.powder_reliability_apply_mode_v2080(c,'normal','Capacity 21.0.4 recovered after hysteresis',p_build,'capacity-v21004',jsonb_build_object('capacityMode','normal','goodStreak',nextgood));end if;
  end if;
  return public.powder_capacity_posture_v21004(c,p_build);
end $f$;

create or replace function public.powder_capacity_posture_v21004(p_channel text default 'production',p_build text default 'powder-21.0.4-capacity-guard') returns jsonb language plpgsql security definer set search_path=public as $f$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;cfg public.capacity_guard_config_v21004;ev public.capacity_guard_snapshots_v21004;fresh boolean:=false;ready boolean:=false;
begin
 select * into cfg from public.capacity_guard_config_v21004 where channel=c;
 select * into ev from public.capacity_guard_snapshots_v21004 where channel=c and build_id=p_build order by checked_at desc limit 1;
 fresh:=ev.id is not null and ev.checked_at>=now()-interval '5 minutes';
 ready:=cfg.armed and cfg.build_id=p_build and fresh and ev.capacity_mode='normal' and cfg.mode='normal';
 return jsonb_build_object('version','21.0.4','buildId',p_build,'ready',ready,'armed',coalesce(cfg.armed,false),'state',coalesce(cfg.state,'hold'),'mode',coalesce(cfg.mode,'normal'),'fresh',fresh,'checkedAt',ev.checked_at,'dbUtilPct',coalesce(ev.db_util_pct,0),'activeConnPct',coalesce(ev.active_conn_pct,0),'lockWaits',coalesce(ev.lock_waits,0),'queueDepth',coalesce(ev.queue_depth,0),'p95Ms',coalesce(ev.p95_ms,0),'p99Ms',coalesce(ev.p99_ms,0),'errorRate',coalesce(ev.error_rate,0),'requests',coalesce(ev.requests,0),'reasons',coalesce(ev.reasons,'[]'::jsonb),'goodStreak',coalesce(cfg.good_streak,0),'goodStreakRequired',coalesce(cfg.good_streak_required,3),'retryAfterSeconds',case when cfg.mode='hard' then cfg.hard_retry_after_seconds else cfg.soft_retry_after_seconds end,'manifestHash',cfg.manifest_hash,'artifactSha256',cfg.artifact_sha256);
end $f$;

create or replace function public.powder_capacity_arm_v21004(p_channel text,p_build text,p_manifest_hash text,p_artifact_sha256 text,p_actor text) returns jsonb language plpgsql security definer set search_path=public as $f$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;
begin if p_build<>'powder-21.0.4-capacity-guard' or p_manifest_hash !~ '^[0-9a-fA-F]{16,64}$' or p_artifact_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'CAP21004_ARM_INVALID';end if;update public.capacity_guard_config_v21004 set build_id=p_build,manifest_hash=lower(p_manifest_hash),artifact_sha256=lower(p_artifact_sha256),armed=true,state='hold',mode='normal',good_streak=0,bad_streak=0,last_reason='Awaiting server-derived capacity snapshot',updated_at=now(),updated_by=left(coalesce(p_actor,''),160) where channel=c;return public.powder_capacity_posture_v21004(c,p_build);end $f$;

create or replace function public.powder_capacity_disarm_v21004(p_channel text,p_build text,p_actor text) returns jsonb language plpgsql security definer set search_path=public as $f$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end;
begin if p_build<>'powder-21.0.4-capacity-guard' then raise exception 'CAP21004_BUILD_MISMATCH';end if;update public.capacity_guard_config_v21004 set armed=false,state='hold',last_reason='Capacity Guard DISARMED',updated_at=now(),updated_by=left(coalesce(p_actor,''),160) where channel=c;return public.powder_capacity_posture_v21004(c,p_build);end $f$;

create or replace function public.powder_capacity_admit_v21004(p_operation text,p_priority text default 'normal') returns jsonb language plpgsql security definer set search_path=public as $f$
declare cfg public.capacity_guard_config_v21004;pri text:=lower(coalesce(p_priority,'normal'));allowed boolean:=true;reason text:='';retry int:=0;
begin select * into cfg from public.capacity_guard_config_v21004 where channel='production';if cfg is null or not cfg.armed then return jsonb_build_object('allowed',true,'mode','normal','reason','guard_disarmed','retryAfterSeconds',0);end if;if cfg.mode='soft' and pri in ('background','bulk','low') then allowed:=false;reason:='CAP21004_SOFT_BACKPRESSURE';retry:=cfg.soft_retry_after_seconds;elsif cfg.mode='hard' and pri not in ('critical','read') then allowed:=false;reason:='CAP21004_HARD_BACKPRESSURE';retry:=cfg.hard_retry_after_seconds;end if;return jsonb_build_object('allowed',allowed,'mode',cfg.mode,'reason',reason,'retryAfterSeconds',retry,'operation',left(coalesce(p_operation,''),160));end $f$;

create or replace function public.powder_capacity_assert_release_allowed_v21004(p_channel text default 'production',p_build text default 'powder-21.0.4-capacity-guard') returns jsonb language plpgsql security definer set search_path=public as $f$ declare p jsonb;begin p:=public.powder_capacity_posture_v21004(p_channel,p_build);if coalesce((p->>'ready')::boolean,false) is not true then raise exception 'CAP21004_RELEASE_BLOCKED';end if;return p;end $f$;

-- Player runtime reuses Reliability 20.8 state; no extra capacity polling endpoint is exposed.

-- Register new Admin surface and MFA-protected mutations.
insert into public.security_admin_surfaces_v20160(function_name,allowed_roles,notes) values('powder-admin-capacity-guard',array['owner','admin','support'],'21.0.4 capacity posture; Owner+AAL2 for ARM/DISARM/emergency actions') on conflict(function_name) do update set allowed_roles=excluded.allowed_roles,notes=excluded.notes,updated_at=now();
insert into public.security_critical_actions_v20160(function_name,action,require_owner,require_aal2) values('powder-admin-capacity-guard','arm',true,true),('powder-admin-capacity-guard','disarm',true,true),('powder-admin-capacity-guard','emergency_hold',true,true) on conflict(function_name,action) do update set require_owner=excluded.require_owner,require_aal2=excluded.require_aal2;

-- Fix Security 20.16 posture cardinality after post-launch Admin surfaces were legitimately added.
create or replace function public.powder_security_posture_v20160()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
 cfg public.security_config_v20160;legacy jsonb:='{}'::jsonb;
 surface_count int:=0;surface_missing int:=0;critical_count int:=0;invalid_roles int:=0;public_definer_exec int:=0;direct_write int:=0;recent_denied int:=0;
 expected_surfaces int:=21;
 critical_tables text[]:=array['admin_allowlist','player_saves','transaction_receipts_v2090','transaction_recovery_queue_v2090','mutation_effect_receipts_v20100','mutation_adapter_dispatch_v20110','reconciliation_cases_v20120','mutation_abuse_events_v20130','official_release_authorization_v2070','release_rollout_v1950','reliability_state_v2080','disaster_recovery_evidence_v20150','capacity_guard_config_v21004'];
 ready boolean:=false;crit_blockers int:=0;high_blockers int:=0;
begin
 select * into cfg from public.security_config_v20160 where id=1;
 begin legacy:=public.powder_security_posture_v2030(); exception when others then legacy:=jsonb_build_object('ready',false,'error',sqlerrm); end;
 select count(*) into surface_count from public.security_admin_surfaces_v20160 where enabled=true;
 surface_missing:=greatest(0,expected_surfaces-surface_count);
 select count(*) into critical_count from public.security_critical_actions_v20160;
 select count(*) into invalid_roles from public.admin_allowlist where active=true and role not in ('owner','admin','support');
 select count(distinct p.oid) into public_definer_exec from pg_proc p join pg_namespace n on n.oid=p.pronamespace join information_schema.routine_privileges rp on rp.specific_schema=n.nspname and rp.routine_name=p.proname where n.nspname='public' and p.prosecdef=true and rp.grantee in ('PUBLIC','anon','authenticated') and rp.privilege_type='EXECUTE' and p.proname not in ('powder_reliability_public_status_v2080');
 select count(*) into direct_write from unnest(critical_tables) t(name) where to_regclass('public.'||t.name) is not null and (has_table_privilege('anon',format('public.%I',t.name),'INSERT,UPDATE,DELETE') or has_table_privilege('authenticated',format('public.%I',t.name),'INSERT,UPDATE,DELETE'));
 select count(*) into recent_denied from public.security_access_audit_v20160 where allowed=false and created_at>=now()-interval '24 hours';
 crit_blockers:=direct_write+public_definer_exec+invalid_roles;
 high_blockers:=surface_missing + case when critical_count<54 then 1 else 0 end + case when coalesce(array_length(cfg.allowed_origins,1),0)=0 then 1 else 0 end + case when coalesce(cfg.enabled,false)=false then 1 else 0 end + case when coalesce((legacy->>'ready')::boolean,false)=false then 1 else 0 end;
 ready:=crit_blockers=0 and high_blockers=0 and surface_count>=expected_surfaces and critical_count>=54;
 return jsonb_build_object('version','20.16.0+21.0.4','ready',ready,'checkedAt',now(),'enabled',coalesce(cfg.enabled,false),'counts',jsonb_build_object('critical',crit_blockers,'high',high_blockers,'publicSecurityDefinerExec',public_definer_exec,'directWriteViolations',direct_write,'invalidAdminRoles',invalid_roles,'adminSurfaces',surface_count,'expectedAdminSurfaces',expected_surfaces,'surfaceMissing',surface_missing,'criticalActions',critical_count,'denied24h',recent_denied),'guards',jsonb_build_object('originAllowlistConfigured',coalesce(array_length(cfg.allowed_origins,1),0)>0,'tokenFreshness',true,'sessionRevocation',true,'criticalAal2',coalesce(cfg.require_aal2_for_critical,true),'allAdminFunctionsCentralGuard',surface_count>=expected_surfaces,'legacy2030',legacy),'config',jsonb_build_object('allowedOrigins',cfg.allowed_origins,'maxTokenAgeSeconds',cfg.max_token_age_seconds,'minTokenRemainingSeconds',cfg.min_token_remaining_seconds,'requireAal2ForCritical',cfg.require_aal2_for_critical));
end$$;

revoke all on function public.powder_capacity_capture_v21004(text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_capacity_posture_v21004(text,text) from public,anon,authenticated;
revoke all on function public.powder_capacity_arm_v21004(text,text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_capacity_disarm_v21004(text,text,text) from public,anon,authenticated;
revoke all on function public.powder_capacity_admit_v21004(text,text) from public,anon,authenticated;
revoke all on function public.powder_capacity_assert_release_allowed_v21004(text,text) from public,anon,authenticated;
grant execute on function public.powder_capacity_capture_v21004(text,text,text,text,text) to service_role;
grant execute on function public.powder_capacity_posture_v21004(text,text) to service_role;
grant execute on function public.powder_capacity_arm_v21004(text,text,text,text,text) to service_role;
grant execute on function public.powder_capacity_disarm_v21004(text,text,text) to service_role;
grant execute on function public.powder_capacity_admit_v21004(text,text) to service_role;
grant execute on function public.powder_capacity_assert_release_allowed_v21004(text,text) to service_role;

commit;
