-- Powder 20.9.0 — Data Integrity & Transaction Safety Hardening
-- Additive transaction receipt ledger. Business Edge Functions should call BEGIN before a mutation
-- and COMMIT/FAIL after the authoritative database mutation. No client can write this ledger directly.

create extension if not exists pgcrypto;

create table if not exists public.transaction_receipts_v2090 (
  user_id uuid not null,
  scope text not null check (scope in ('economy','inventory','reward','mail','event','purchase','support')),
  tx_key text not null,
  operation text not null,
  request_sha256 text not null check (request_sha256 ~ '^[0-9a-f]{64}$'),
  status text not null default 'pending' check (status in ('pending','committed','failed','reconciling')),
  lease_token uuid,
  lease_expires_at timestamptz,
  attempt_count integer not null default 1 check (attempt_count between 1 and 1000),
  result jsonb not null default '{}'::jsonb,
  error_code text not null default '',
  error_message text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  committed_at timestamptz,
  primary key (user_id, scope, tx_key)
);

create index if not exists transaction_receipts_v2090_status_updated_idx
  on public.transaction_receipts_v2090(status,updated_at);
create index if not exists transaction_receipts_v2090_user_updated_idx
  on public.transaction_receipts_v2090(user_id,updated_at desc);

create table if not exists public.transaction_integrity_events_v2090 (
  id bigint generated by default as identity primary key,
  user_id uuid,
  scope text not null default '',
  tx_key text not null default '',
  event_type text not null check (event_type in ('key_reuse_mismatch','stale_enqueued','lease_reclaimed','manual_resolution')),
  details jsonb not null default '{}'::jsonb,
  actor text not null default 'server',
  created_at timestamptz not null default now()
);
create index if not exists transaction_integrity_events_v2090_created_idx
  on public.transaction_integrity_events_v2090(created_at desc);

create table if not exists public.transaction_recovery_queue_v2090 (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  scope text not null,
  tx_key text not null,
  operation text not null,
  receipt_status text not null,
  reason text not null,
  status text not null default 'queued' check (status in ('queued','investigating','resolved_committed','resolved_not_committed','cancelled')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text,
  resolution_note text not null default '',
  unique(user_id,scope,tx_key,status)
);
create index if not exists transaction_recovery_queue_v2090_status_idx
  on public.transaction_recovery_queue_v2090(status,created_at);

alter table public.transaction_receipts_v2090 enable row level security;
alter table public.transaction_integrity_events_v2090 enable row level security;
alter table public.transaction_recovery_queue_v2090 enable row level security;
revoke all on table public.transaction_receipts_v2090 from anon,authenticated;
revoke all on table public.transaction_integrity_events_v2090 from anon,authenticated;
revoke all on table public.transaction_recovery_queue_v2090 from anon,authenticated;
grant select,insert,update,delete on table public.transaction_receipts_v2090 to service_role;
grant select,insert,update,delete on table public.transaction_integrity_events_v2090 to service_role;
grant select,insert,update,delete on table public.transaction_recovery_queue_v2090 to service_role;

create or replace function public.powder_transaction_hash_v2090(p_operation text,p_payload jsonb)
returns text language sql immutable as $function$
  select encode(digest(coalesce(p_operation,'')||'|'||coalesce(p_payload,'{}'::jsonb)::text,'sha256'),'hex');
$function$;

create or replace function public.powder_transaction_begin_v2090(
  p_user uuid,
  p_scope text,
  p_operation text,
  p_tx_key text,
  p_payload jsonb default '{}'::jsonb,
  p_lease_seconds integer default 45
) returns jsonb
language plpgsql security definer set search_path='public' as $function$
declare
  sc text:=lower(trim(coalesce(p_scope,'')));
  op text:=lower(trim(coalesce(p_operation,'')));
  k text:=trim(coalesce(p_tx_key,''));
  req_hash text;
  lease uuid:=gen_random_uuid();
  ttl integer:=greatest(10,least(180,coalesce(p_lease_seconds,45)));
  r public.transaction_receipts_v2090;
  allowed boolean:=false;
begin
  if p_user is null then raise exception 'TX_2090_USER_REQUIRED'; end if;
  if sc not in ('economy','inventory','reward','mail','event','purchase','support') then raise exception 'TX_2090_SCOPE_INVALID'; end if;
  if length(op)<2 or length(op)>80 then raise exception 'TX_2090_OPERATION_INVALID'; end if;
  if length(k)<12 or length(k)>180 or k !~ '^[A-Za-z0-9:._-]+$' then raise exception 'TX_2090_KEY_INVALID'; end if;
  req_hash:=public.powder_transaction_hash_v2090(op,coalesce(p_payload,'{}'::jsonb));
  begin allowed:=public.powder_reliability_can_write_v2080(case when sc='inventory' then 'inventory' when sc in ('reward','mail','event') then 'reward' else 'economy' end); exception when others then allowed:=false; end;
  if allowed is not true then raise exception 'TX_2090_RELIABILITY_WRITE_BLOCKED'; end if;

  perform pg_advisory_xact_lock(hashtextextended(p_user::text||'|'||sc||'|'||k,0));
  select * into r from public.transaction_receipts_v2090 where user_id=p_user and scope=sc and tx_key=k for update;
  if found then
    if r.request_sha256<>req_hash or r.operation<>op then
      insert into public.transaction_integrity_events_v2090(user_id,scope,tx_key,event_type,details)
      values(p_user,sc,k,'key_reuse_mismatch',jsonb_build_object('storedOperation',r.operation,'incomingOperation',op,'storedHash',r.request_sha256,'incomingHash',req_hash));
      raise exception 'TX_2090_KEY_REUSE_MISMATCH';
    end if;
    if r.status='committed' then
      return jsonb_build_object('ok',true,'execute',false,'idempotent',true,'status','committed','txKey',k,'result',r.result,'committedAt',r.committed_at);
    end if;
    if r.status in ('pending','reconciling') and r.lease_token is not null and r.lease_expires_at>now() then
      return jsonb_build_object('ok',true,'execute',false,'inFlight',true,'idempotent',true,'status',r.status,'txKey',k,'retryAfterMs',greatest(250,extract(epoch from (r.lease_expires_at-now()))*1000)::bigint);
    end if;
    update public.transaction_receipts_v2090
       set status='pending',lease_token=lease,lease_expires_at=now()+make_interval(secs=>ttl),attempt_count=least(1000,attempt_count+1),updated_at=now(),error_code='',error_message=''
     where user_id=p_user and scope=sc and tx_key=k
     returning * into r;
    insert into public.transaction_integrity_events_v2090(user_id,scope,tx_key,event_type,details)
    values(p_user,sc,k,'lease_reclaimed',jsonb_build_object('attempt',r.attempt_count,'leaseSeconds',ttl));
    return jsonb_build_object('ok',true,'execute',true,'idempotent',true,'reclaimed',true,'status','pending','txKey',k,'leaseToken',lease,'requestHash',req_hash,'attempt',r.attempt_count);
  end if;

  insert into public.transaction_receipts_v2090(user_id,scope,tx_key,operation,request_sha256,status,lease_token,lease_expires_at)
  values(p_user,sc,k,op,req_hash,'pending',lease,now()+make_interval(secs=>ttl));
  return jsonb_build_object('ok',true,'execute',true,'idempotent',false,'status','pending','txKey',k,'leaseToken',lease,'requestHash',req_hash,'attempt',1);
end $function$;

create or replace function public.powder_transaction_commit_v2090(
  p_user uuid,p_scope text,p_tx_key text,p_lease_token uuid,p_result jsonb default '{}'::jsonb
) returns jsonb
language plpgsql security definer set search_path='public' as $function$
declare sc text:=lower(trim(coalesce(p_scope,'')));k text:=trim(coalesce(p_tx_key,''));r public.transaction_receipts_v2090;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user::text||'|'||sc||'|'||k,0));
  select * into r from public.transaction_receipts_v2090 where user_id=p_user and scope=sc and tx_key=k for update;
  if not found then raise exception 'TX_2090_RECEIPT_NOT_FOUND'; end if;
  if r.status='committed' then return jsonb_build_object('ok',true,'idempotent',true,'status','committed','txKey',k,'result',r.result); end if;
  if r.status not in ('pending','reconciling') then raise exception 'TX_2090_RECEIPT_NOT_COMMITTABLE'; end if;
  if r.lease_token is distinct from p_lease_token then raise exception 'TX_2090_LEASE_MISMATCH'; end if;
  update public.transaction_receipts_v2090
     set status='committed',result=coalesce(p_result,'{}'::jsonb),error_code='',error_message='',lease_token=null,lease_expires_at=null,updated_at=now(),committed_at=now()
   where user_id=p_user and scope=sc and tx_key=k returning * into r;
  update public.transaction_recovery_queue_v2090 set status='resolved_committed',updated_at=now(),resolved_at=now(),resolved_by='server-auto',resolution_note='Receipt committed after recovery.'
   where user_id=p_user and scope=sc and tx_key=k and status in ('queued','investigating');
  return jsonb_build_object('ok',true,'idempotent',false,'status','committed','txKey',k,'result',r.result,'committedAt',r.committed_at);
end $function$;

create or replace function public.powder_transaction_fail_v2090(
  p_user uuid,p_scope text,p_tx_key text,p_lease_token uuid,p_error_code text,p_error_message text,p_retryable boolean default false
) returns jsonb
language plpgsql security definer set search_path='public' as $function$
declare sc text:=lower(trim(coalesce(p_scope,'')));k text:=trim(coalesce(p_tx_key,''));r public.transaction_receipts_v2090;next_status text;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user::text||'|'||sc||'|'||k,0));
  select * into r from public.transaction_receipts_v2090 where user_id=p_user and scope=sc and tx_key=k for update;
  if not found then raise exception 'TX_2090_RECEIPT_NOT_FOUND'; end if;
  if r.status='committed' then return jsonb_build_object('ok',true,'idempotent',true,'status','committed','txKey',k,'result',r.result); end if;
  if r.lease_token is distinct from p_lease_token then raise exception 'TX_2090_LEASE_MISMATCH'; end if;
  next_status:=case when coalesce(p_retryable,false) then 'pending' else 'failed' end;
  update public.transaction_receipts_v2090
     set status=next_status,error_code=left(coalesce(p_error_code,''),120),error_message=left(coalesce(p_error_message,''),800),lease_token=null,lease_expires_at=null,updated_at=now()
   where user_id=p_user and scope=sc and tx_key=k;
  return jsonb_build_object('ok',true,'status',next_status,'retryable',coalesce(p_retryable,false),'txKey',k);
end $function$;

create or replace function public.powder_transaction_reconcile_scan_v2090(p_limit integer default 100,p_actor text default 'system')
returns jsonb language plpgsql security definer set search_path='public' as $function$
declare lim integer:=greatest(1,least(500,coalesce(p_limit,100)));n integer:=0;
begin
  with stale as (
    select r.user_id,r.scope,r.tx_key,r.operation,r.status,r.request_sha256,r.attempt_count,r.updated_at
      from public.transaction_receipts_v2090 r
     where r.status in ('pending','reconciling') and r.updated_at<now()-interval '5 minutes'
     order by r.updated_at asc limit lim for update skip locked
  ), ins as (
    insert into public.transaction_recovery_queue_v2090(user_id,scope,tx_key,operation,receipt_status,reason,details)
    select s.user_id,s.scope,s.tx_key,s.operation,s.status,'STALE_PENDING_REQUIRES_AUTHORITATIVE_CHECK',
           jsonb_build_object('requestHash',s.request_sha256,'attempts',s.attempt_count,'lastUpdatedAt',s.updated_at)
      from stale s
     where not exists(select 1 from public.transaction_recovery_queue_v2090 q where q.user_id=s.user_id and q.scope=s.scope and q.tx_key=s.tx_key and q.status in ('queued','investigating'))
    returning user_id,scope,tx_key
  )
  update public.transaction_receipts_v2090 r set status='reconciling',lease_token=null,lease_expires_at=null,updated_at=now()
   where exists(select 1 from ins i where i.user_id=r.user_id and i.scope=r.scope and i.tx_key=r.tx_key);
  get diagnostics n=row_count;
  insert into public.transaction_integrity_events_v2090(event_type,details,actor)
  values('stale_enqueued',jsonb_build_object('count',n,'limit',lim),left(coalesce(p_actor,'system'),160));
  return jsonb_build_object('ok',true,'version','20.9.0','queued',n,'limit',lim,'at',now());
end $function$;

create or replace function public.powder_transaction_resolve_v2090(
  p_recovery_id uuid,p_resolution text,p_actor text,p_note text default ''
) returns jsonb language plpgsql security definer set search_path='public' as $function$
declare q public.transaction_recovery_queue_v2090;res text:=lower(trim(coalesce(p_resolution,'')));new_status text;
begin
  if res not in ('committed','not_committed','cancelled') then raise exception 'TX_2090_RESOLUTION_INVALID'; end if;
  select * into q from public.transaction_recovery_queue_v2090 where id=p_recovery_id for update;
  if not found then raise exception 'TX_2090_RECOVERY_NOT_FOUND'; end if;
  if q.status not in ('queued','investigating') then return jsonb_build_object('ok',true,'idempotent',true,'status',q.status,'recoveryId',q.id); end if;
  new_status:=case res when 'committed' then 'resolved_committed' when 'not_committed' then 'resolved_not_committed' else 'cancelled' end;
  update public.transaction_recovery_queue_v2090 set status=new_status,updated_at=now(),resolved_at=now(),resolved_by=left(coalesce(p_actor,''),160),resolution_note=left(coalesce(p_note,''),1200) where id=q.id;
  if res='not_committed' then
    update public.transaction_receipts_v2090 set status='failed',lease_token=null,lease_expires_at=null,error_code='RECOVERY_CONFIRMED_NOT_COMMITTED',error_message=left(coalesce(p_note,''),800),updated_at=now()
     where user_id=q.user_id and scope=q.scope and tx_key=q.tx_key and status<>'committed';
  elsif res='committed' then
    update public.transaction_receipts_v2090 set status='committed',lease_token=null,lease_expires_at=null,committed_at=coalesce(committed_at,now()),updated_at=now(),error_code='',error_message=''
     where user_id=q.user_id and scope=q.scope and tx_key=q.tx_key and status<>'committed';
  end if;
  insert into public.transaction_integrity_events_v2090(user_id,scope,tx_key,event_type,details,actor)
  values(q.user_id,q.scope,q.tx_key,'manual_resolution',jsonb_build_object('recoveryId',q.id,'resolution',res,'note',left(coalesce(p_note,''),400)),left(coalesce(p_actor,''),160));
  return jsonb_build_object('ok',true,'idempotent',false,'status',new_status,'recoveryId',q.id,'txKey',q.tx_key);
end $function$;

create or replace function public.powder_transaction_posture_v2090()
returns jsonb language plpgsql security definer set search_path='public' stable as $function$
declare pending_count bigint:=0;stale_count bigint:=0;recovery_open bigint:=0;mismatch_24h bigint:=0;failed_24h bigint:=0;committed_24h bigint:=0;ready boolean:=false;guard_ok boolean:=false;
begin
  select count(*),count(*) filter(where updated_at<now()-interval '5 minutes') into pending_count,stale_count from public.transaction_receipts_v2090 where status in ('pending','reconciling');
  select count(*) into recovery_open from public.transaction_recovery_queue_v2090 where status in ('queued','investigating');
  select count(*) into mismatch_24h from public.transaction_integrity_events_v2090 where event_type='key_reuse_mismatch' and created_at>=now()-interval '24 hours';
  select count(*) into failed_24h from public.transaction_receipts_v2090 where status='failed' and updated_at>=now()-interval '24 hours';
  select count(*) into committed_24h from public.transaction_receipts_v2090 where status='committed' and committed_at>=now()-interval '24 hours';
  begin perform public.powder_reliability_can_write_v2080('economy'); guard_ok:=true; exception when others then guard_ok:=false; end;
  ready:=stale_count=0 and recovery_open=0 and mismatch_24h=0 and guard_ok;
  return jsonb_build_object('version','20.9.0','ready',ready,'checkedAt',now(),'counts',jsonb_build_object('pending',pending_count,'stalePending',stale_count,'recoveryOpen',recovery_open,'keyReuseMismatch24h',mismatch_24h,'failed24h',failed_24h,'committed24h',committed_24h),'guards',jsonb_build_object('reliabilityWriteGuardReachable',guard_ok,'receiptPrimaryKey',true,'serviceRoleOnly',true,'automaticReplay',false));
end $function$;

revoke all on function public.powder_transaction_hash_v2090(text,jsonb) from public,anon,authenticated;
revoke all on function public.powder_transaction_begin_v2090(uuid,text,text,text,jsonb,integer) from public,anon,authenticated;
revoke all on function public.powder_transaction_commit_v2090(uuid,text,text,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.powder_transaction_fail_v2090(uuid,text,text,uuid,text,text,boolean) from public,anon,authenticated;
revoke all on function public.powder_transaction_reconcile_scan_v2090(integer,text) from public,anon,authenticated;
revoke all on function public.powder_transaction_resolve_v2090(uuid,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_transaction_posture_v2090() from public,anon,authenticated;
grant execute on function public.powder_transaction_hash_v2090(text,jsonb) to service_role;
grant execute on function public.powder_transaction_begin_v2090(uuid,text,text,text,jsonb,integer) to service_role;
grant execute on function public.powder_transaction_commit_v2090(uuid,text,text,uuid,jsonb) to service_role;
grant execute on function public.powder_transaction_fail_v2090(uuid,text,text,uuid,text,text,boolean) to service_role;
grant execute on function public.powder_transaction_reconcile_scan_v2090(integer,text) to service_role;
grant execute on function public.powder_transaction_resolve_v2090(uuid,text,text,text) to service_role;
grant execute on function public.powder_transaction_posture_v2090() to service_role;

-- Upgrade Official Launch 20.7 surface for the 20.9 candidate and make transaction integrity a hard preflight gate.
create or replace function public.powder_official_launch_preflight_v2070(
  p_channel text default 'production',
  p_build text default 'powder-20.9.0-data-integrity-transaction-safety',
  p_manifest_hash text default ''
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  c text:=case when p_channel='staging' then 'staging' else 'production' end;
  b public.release_builds; ch public.release_channels; ro public.release_rollout_v1950;
  auth public.official_release_authorization_v2070;
  integ jsonb:='{}'::jsonb; sec jsonb:='{}'::jsonb; rec jsonb:='{}'::jsonb; rel jsonb:='{}'::jsonb; txp jsonb:='{}'::jsonb;
  active_pilot int:=0; recent_pilot int:=0; pvp_matches bigint:=0; crashes bigint:=0; low_fps int:=0; save_bad int:=0;
  pilot_critical int:=0; pilot_high int:=0; ops_critical int:=0; ops_high int:=0; evidence_pass int:=0;
  candidate_ok boolean:=false; integrity_ok boolean:=false; security_ok boolean:=false; recovery_ok boolean:=false; transaction_ok boolean:=false;
  pilot_ok boolean:=false; rollout_ok boolean:=false; evidence_ok boolean:=false; incidents_ok boolean:=false;
  observability_ok boolean:=false; reliability_ok boolean:=false; rollback_ok boolean:=false; auth_ok boolean:=false; window_ok boolean:=false; ready boolean:=false;
begin
  select * into ch from public.release_channels where channel=c;
  select * into ro from public.release_rollout_v1950 where channel=c;
  select * into b from public.release_builds where channel=c and build_id=p_build limit 1;
  select * into auth from public.official_release_authorization_v2070 where channel=c and build_id=p_build;
  begin integ:=public.powder_integrity_snapshot_v1960(); exception when others then integ:=jsonb_build_object('ready',false,'error',sqlerrm); end;
  begin sec:=public.powder_security_posture_v2030(); exception when others then sec:=jsonb_build_object('ready',false,'error',sqlerrm); end;
  begin rec:=public.powder_recovery_posture_v2040(c,p_build); exception when others then rec:=jsonb_build_object('ready',false,'error',sqlerrm); end;
  begin rel:=public.powder_reliability_snapshot_v2080(c,p_build); exception when others then rel:=jsonb_build_object('healthy',false,'error',sqlerrm); end;
  begin txp:=public.powder_transaction_posture_v2090(); exception when others then txp:=jsonb_build_object('ready',false,'error',sqlerrm); end;
  select count(*) into active_pilot from public.pilot_cohort_v1970 where active=true;
  select count(distinct d.user_id),coalesce(sum(d.pvp_matches),0),coalesce(sum(d.crash_count),0),
         count(*) filter(where d.avg_fps>0 and d.avg_fps<30),
         count(*) filter(where coalesce((d.last_summary->>'savePass')::boolean,true)=false)
    into recent_pilot,pvp_matches,crashes,low_fps,save_bad
    from public.pilot_device_health_v1970 d
    join public.pilot_cohort_v1970 p on p.user_id=d.user_id and p.active=true
   where d.last_seen_at>=now()-interval '7 days';
  select count(*) filter(where i.severity='critical'),count(*) filter(where i.severity='high')
    into pilot_critical,pilot_high
    from public.pilot_issue_reports_v1970 i
    join public.pilot_cohort_v1970 p on p.user_id=i.user_id and p.active=true
   where i.status in ('open','triaged');
  select count(*) filter(where severity='critical'),count(*) filter(where severity='high')
    into ops_critical,ops_high from public.official_incidents_v2010
   where channel=c and status in ('open','monitoring');
  select count(*) into evidence_pass from public.official_launch_evidence_v2000 e
   where e.channel=c and e.build_id=p_build and e.status='pass'
     and e.check_key in ('load_1960','recovery_1940','polish_1980','freeze_1990')
     and (p_manifest_hash='' or e.manifest_hash=p_manifest_hash)
     and e.evidence_sha256~'^[0-9a-fA-F]{64}$';
  candidate_ok:=b.build_id is not null and b.version='20.9.0' and b.status in ('candidate','active') and b.checksum~'^[0-9a-fA-F]{64}$';
  integrity_ok:=coalesce((integ->>'ready')::boolean,false);
  security_ok:=coalesce((sec->>'ready')::boolean,false);
  recovery_ok:=coalesce((rec->>'ready')::boolean,false);
  transaction_ok:=coalesce((txp->>'ready')::boolean,false);
  pilot_ok:=active_pilot between 20 and 50 and recent_pilot>=20 and pvp_matches>=20 and crashes=0 and low_fps=0 and save_bad=0 and pilot_critical=0 and pilot_high=0;
  rollout_ok:=coalesce(ro.emergency_mode,'normal')='normal' and coalesce(ch.hard_maintenance,false)=false;
  evidence_ok:=evidence_pass=4;
  incidents_ok:=ops_critical=0 and ops_high=0;
  observability_ok:=exists(select 1 from public.observability_config_v2020 o where o.channel=c and o.enabled=true and o.min_requests>=20);
  reliability_ok:=coalesce((rel->>'healthy')::boolean,false) and coalesce(rel->'state'->>'mode','normal')='normal' and coalesce(rel->'state'->>'circuit_state','closed')='closed';
  rollback_ok:=auth.rollback_target_build<>'' and ro.rollback_target_build=auth.rollback_target_build
    and auth.rollback_target_build<>p_build
    and exists(select 1 from public.release_builds rb where rb.channel=c and rb.build_id=auth.rollback_target_build and rb.checksum~'^[0-9a-fA-F]{64}$');
  auth_ok:=auth.status='armed' and auth.manifest_hash=p_manifest_hash and auth.artifact_checksum=b.checksum;
  window_ok:=auth.window_start is not null and auth.window_end is not null and now() between auth.window_start and auth.window_end;
  ready:=candidate_ok and integrity_ok and security_ok and recovery_ok and transaction_ok and pilot_ok and rollout_ok and evidence_ok and incidents_ok and observability_ok and reliability_ok and rollback_ok and auth_ok and window_ok;
  return jsonb_build_object('version','20.9.0','channel',c,'buildId',p_build,'manifestHash',p_manifest_hash,'ready',ready,
    'checks',jsonb_build_object('candidate',candidate_ok,'integrity',integrity_ok,'securityPosture',security_ok,'recovery',recovery_ok,'transactionIntegrity',transaction_ok,
      'realPilot',pilot_ok,'rolloutNormal',rollout_ok,'evidence4of4',evidence_ok,'liveOpsIncidents',incidents_ok,
      'observabilityArmed',observability_ok,'reliabilityNormal',reliability_ok,'rollbackPinned',rollback_ok,'authorizationArmed',auth_ok,'changeWindowOpen',window_ok),
    'candidate',case when b.build_id is null then null else to_jsonb(b) end,
    'release',case when ch.channel is null then null else to_jsonb(ch) end,
    'rollout',case when ro.channel is null then null else to_jsonb(ro) end,
    'authorization',case when auth.build_id is null then null else to_jsonb(auth) end,
    'integrity',integ,'security',sec,'recovery',rec,'reliability',rel,'transactions',txp,
    'pilot',jsonb_build_object('activePilot',active_pilot,'recentPilot7d',recent_pilot,'pvpMatches',pvp_matches,'crashes',crashes,'lowFpsDevices',low_fps,'saveBadDevices',save_bad,'openCritical',pilot_critical,'openHigh',pilot_high),
    'liveOps',jsonb_build_object('openCritical',ops_critical,'openHigh',ops_high,'blockers',ops_critical+ops_high),
    'evidencePass',evidence_pass,'checkedAt',now());
end $$;

create or replace function public.powder_official_activate_canary_v2070(p_channel text,p_build text,p_manifest_hash text,p_admin text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; pf jsonb; ch public.release_channels; ro public.release_rollout_v1950; target public.release_builds; auth public.official_release_authorization_v2070; nowts timestamptz:=now();
begin
  perform pg_advisory_xact_lock(hashtextextended('official-launch-v2070:'||c,0));
  pf:=public.powder_official_launch_preflight_v2070(c,p_build,p_manifest_hash);
  if coalesce((pf->>'ready')::boolean,false) is not true then raise exception 'OFFICIAL_2070_PREFLIGHT_NOT_READY'; end if;
  select * into ch from public.release_channels where channel=c for update;
  select * into ro from public.release_rollout_v1950 where channel=c for update;
  select * into target from public.release_builds where channel=c and build_id=p_build for update;
  select * into auth from public.official_release_authorization_v2070 where channel=c and build_id=p_build for update;
  if target.version<>'20.9.0' then raise exception 'OFFICIAL_2070_CANDIDATE_INVALID'; end if;
  if ch.build_id=p_build then raise exception 'OFFICIAL_2070_ALREADY_ACTIVE'; end if;
  if auth.status<>'armed' or nowts not between auth.window_start and auth.window_end then raise exception 'OFFICIAL_2070_AUTH_NOT_ARMED'; end if;
  if auth.rollback_target_build<>ch.build_id or ro.rollback_target_build<>ch.build_id then raise exception 'OFFICIAL_2070_ROLLBACK_TARGET_DRIFT'; end if;
  update public.release_builds set status='rolled_back' where channel=c and build_id=ch.build_id;
  update public.release_builds set status='active',activated_at=nowts where channel=c and build_id=p_build;
  update public.release_channels set current_version=target.version,build_id=target.build_id,asset_epoch=coalesce(asset_epoch,0)+1,updated_at=nowts,updated_by=p_admin where channel=c;
  update public.release_rollout_v1950 set rollout_percent=5,emergency_mode='normal',emergency_message='',updated_at=nowts,updated_by=p_admin where channel=c;
  delete from public.official_rollout_server_evidence_v2070 where channel=c and build_id=p_build;
  insert into public.release_deployments(channel,action,version,build_id,previous_version,details,created_by,created_at)
  values(c,'official_canary_5_v2070',target.version,target.build_id,ch.current_version,jsonb_build_object('manifestHash',p_manifest_hash,'rollbackTarget',auth.rollback_target_build,'authorizationRevision',auth.revision,'transactionIntegrity','20.9.0'),p_admin,nowts);
  return jsonb_build_object('ok',true,'channel',c,'version',target.version,'buildId',target.build_id,'rolloutPercent',5,'previousBuildId',ch.build_id,'at',nowts);
end $$;

create or replace function public.powder_official_advance_rollout_v2070(p_channel text,p_build text,p_manifest_hash text,p_admin text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; pf jsonb; ch public.release_channels; ro public.release_rollout_v1950; auth public.official_release_authorization_v2070; cur smallint; nxt smallint; nowts timestamptz:=now();
begin
  perform pg_advisory_xact_lock(hashtextextended('official-launch-v2070:'||c,0));
  pf:=public.powder_official_launch_preflight_v2070(c,p_build,p_manifest_hash);
  if coalesce((pf->>'ready')::boolean,false) is not true then raise exception 'OFFICIAL_2070_PREFLIGHT_NOT_READY'; end if;
  select * into ch from public.release_channels where channel=c for update;
  select * into ro from public.release_rollout_v1950 where channel=c for update;
  select * into auth from public.official_release_authorization_v2070 where channel=c and build_id=p_build for update;
  if ch.build_id<>p_build then raise exception 'OFFICIAL_2070_BUILD_NOT_ACTIVE'; end if;
  if auth.status<>'armed' or nowts not between auth.window_start and auth.window_end then raise exception 'OFFICIAL_2070_AUTH_WINDOW_CLOSED'; end if;
  cur:=ro.rollout_percent; nxt:=case cur when 5 then 20 when 20 then 50 when 50 then 100 else null end;
  if nxt is null then raise exception 'OFFICIAL_2070_STAGE_NOT_ADVANCEABLE'; end if;
  if not exists(select 1 from public.official_rollout_server_evidence_v2070 e where e.channel=c and e.build_id=p_build and e.rollout_percent=cur and e.status='pass' and e.checked_at>=now()-interval '6 hours') then
    raise exception 'OFFICIAL_2070_SERVER_HEALTH_NOT_PASSED';
  end if;
  update public.release_rollout_v1950 set rollout_percent=nxt,updated_at=nowts,updated_by=p_admin where channel=c;
  insert into public.release_deployments(channel,action,version,build_id,previous_version,details,created_by,created_at)
  values(c,'official_rollout_'||nxt::text||'_v2070',ch.current_version,ch.build_id,ch.current_version,jsonb_build_object('fromPercent',cur,'toPercent',nxt,'manifestHash',p_manifest_hash,'healthSource','server-observability+transaction-integrity'),p_admin,nowts);
  return jsonb_build_object('ok',true,'channel',c,'buildId',p_build,'fromPercent',cur,'rolloutPercent',nxt,'at',nowts);
end $$;

create or replace function public.powder_official_finalize_live_v2070(p_channel text,p_build text,p_manifest_hash text,p_admin text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c text:=case when p_channel='staging' then 'staging' else 'production' end; pf jsonb; ch public.release_channels; ro public.release_rollout_v1950; auth public.official_release_authorization_v2070; nowts timestamptz:=now();
begin
  perform pg_advisory_xact_lock(hashtextextended('official-launch-v2070:'||c,0));
  pf:=public.powder_official_launch_preflight_v2070(c,p_build,p_manifest_hash);
  if coalesce((pf->>'ready')::boolean,false) is not true then raise exception 'OFFICIAL_2070_PREFLIGHT_NOT_READY'; end if;
  select * into ch from public.release_channels where channel=c for update;
  select * into ro from public.release_rollout_v1950 where channel=c for update;
  select * into auth from public.official_release_authorization_v2070 where channel=c and build_id=p_build for update;
  if ch.build_id<>p_build or ch.current_version<>'20.9.0' then raise exception 'OFFICIAL_2070_BUILD_NOT_ACTIVE'; end if;
  if ro.rollout_percent<>100 then raise exception 'OFFICIAL_2070_ROLLOUT_NOT_100'; end if;
  if not exists(select 1 from public.official_rollout_server_evidence_v2070 e where e.channel=c and e.build_id=p_build and e.rollout_percent=100 and e.status='pass' and e.checked_at>=now()-interval '6 hours') then raise exception 'OFFICIAL_2070_FINAL_HEALTH_NOT_PASSED'; end if;
  update public.launch_config_v170 set launch_status='live',content_frozen=true,registration_open=true,updated_by=p_admin,updated_at=nowts where id=1;
  update public.official_release_authorization_v2070 set status='consumed',consumed_at=nowts,updated_at=nowts,updated_by=p_admin where channel=c and build_id=p_build;
  insert into public.release_deployments(channel,action,version,build_id,previous_version,details,created_by,created_at)
  values(c,'official_live_v2070',ch.current_version,ch.build_id,ch.current_version,jsonb_build_object('rolloutPercent',100,'manifestHash',p_manifest_hash,'authorizationRevision',auth.revision,'healthSource','server-observability+transaction-integrity'),p_admin,nowts);
  return jsonb_build_object('ok',true,'official',true,'channel',c,'version',ch.current_version,'buildId',ch.build_id,'rolloutPercent',100,'at',nowts);
end $$;

revoke all on function public.powder_official_launch_preflight_v2070(text,text,text) from public,anon,authenticated;
revoke all on function public.powder_official_activate_canary_v2070(text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_official_advance_rollout_v2070(text,text,text,text) from public,anon,authenticated;
revoke all on function public.powder_official_finalize_live_v2070(text,text,text,text) from public,anon,authenticated;
grant execute on function public.powder_official_launch_preflight_v2070(text,text,text) to service_role;
grant execute on function public.powder_official_activate_canary_v2070(text,text,text,text) to service_role;
grant execute on function public.powder_official_advance_rollout_v2070(text,text,text,text) to service_role;
grant execute on function public.powder_official_finalize_live_v2070(text,text,text,text) to service_role;
