-- Powder 20.17.0 · Player Save Integrity Final
-- Adds server-side save envelope hashing, snapshot history, destructive-write guards,
-- multi-device/revision diagnostics and a fail-closed production posture.

begin;
create extension if not exists pgcrypto;

create table if not exists public.save_integrity_config_v20170(
 id smallint primary key default 1 check(id=1),
 armed boolean not null default false,
 max_snapshot_age_hours int not null default 24 check(max_snapshot_age_hours between 1 and 168),
 max_open_medium int not null default 0 check(max_open_medium>=0),
 updated_at timestamptz not null default now(),
 updated_by text not null default ''
);
insert into public.save_integrity_config_v20170(id) values(1) on conflict(id) do nothing;

create table if not exists public.save_integrity_snapshots_v20170(
 user_id uuid not null,
 revision bigint not null,
 save_version int not null default 0,
 schema_version int not null default 0,
 app_version text not null default '',
 device_id text not null default '',
 save_sha256 text not null,
 main_sha256 text not null,
 world_sha256 text not null,
 pow_ids_sha256 text not null,
 lessons_sha256 text not null,
 pow_count int not null default 0,
 lessons_count int not null default 0,
 equipment_copy_count bigint not null default 0,
 artifact_instance_count int not null default 0,
 critical_shape boolean not null default false,
 summary jsonb not null default '{}'::jsonb,
 captured_at timestamptz not null default now(),
 primary key(user_id,revision)
);
create index if not exists save_integrity_snapshots_v20170_recent_idx on public.save_integrity_snapshots_v20170(captured_at desc);
create index if not exists save_integrity_snapshots_v20170_user_recent_idx on public.save_integrity_snapshots_v20170(user_id,captured_at desc);

create table if not exists public.save_integrity_incidents_v20170(
 id bigint generated by default as identity primary key,
 user_id uuid,
 revision bigint,
 severity text not null check(severity in ('medium','high','critical')),
 code text not null,
 details jsonb not null default '{}'::jsonb,
 resolved boolean not null default false,
 resolved_at timestamptz,
 resolved_by text,
 created_at timestamptz not null default now()
);
create index if not exists save_integrity_incidents_v20170_open_idx on public.save_integrity_incidents_v20170(resolved,severity,created_at desc);

create table if not exists public.save_integrity_scan_runs_v20170(
 id bigint generated by default as identity primary key,
 build_id text not null default 'powder-20.17.0-player-save-integrity-final',
 total_saves bigint not null default 0,
 malformed bigint not null default 0,
 missing_snapshot bigint not null default 0,
 revision_anomaly bigint not null default 0,
 open_critical bigint not null default 0,
 open_high bigint not null default 0,
 open_medium bigint not null default 0,
 ready boolean not null default false,
 details jsonb not null default '{}'::jsonb,
 checked_at timestamptz not null default now(),
 checked_by text not null default ''
);

alter table public.save_integrity_config_v20170 enable row level security;
alter table public.save_integrity_snapshots_v20170 enable row level security;
alter table public.save_integrity_incidents_v20170 enable row level security;
alter table public.save_integrity_scan_runs_v20170 enable row level security;
revoke all on public.save_integrity_config_v20170,public.save_integrity_snapshots_v20170,public.save_integrity_incidents_v20170,public.save_integrity_scan_runs_v20170 from public,anon,authenticated;
grant select,insert,update,delete on public.save_integrity_config_v20170,public.save_integrity_snapshots_v20170,public.save_integrity_incidents_v20170,public.save_integrity_scan_runs_v20170 to service_role;
grant usage,select on sequence public.save_integrity_incidents_v20170_id_seq,public.save_integrity_scan_runs_v20170_id_seq to service_role;

alter table public.player_saves add column if not exists integrity_version text;
alter table public.player_saves add column if not exists integrity_sha256 text;
alter table public.player_saves add column if not exists integrity_checked_at timestamptz;
alter table public.player_saves add column if not exists integrity_summary jsonb;

create or replace function public.powder_save_integrity_summary_v20170(p_save jsonb)
returns jsonb language plpgsql immutable as $$
declare
 main jsonb;world jsonb;owned jsonb;lessons jsonb;eq jsonb;arts jsonb;
 pow_count int:=0;lesson_count int:=0;eq_count bigint:=0;art_count int:=0;
 save_version int:=0;critical_shape boolean:=false;pow_ids text:='';lesson_ids text:='';
begin
 if jsonb_typeof(p_save)<>'object' then
  return jsonb_build_object('criticalShape',false,'error','SAVE_NOT_OBJECT','powCount',0,'lessonsCount',0,'equipmentCopies',0,'artifactInstances',0,'saveVersion',0);
 end if;
 main:=case when jsonb_typeof(p_save->'main')='object' then p_save->'main' else p_save end;
 world:=case when jsonb_typeof(p_save->'world')='object' then p_save->'world' else '{}'::jsonb end;
 owned:=case when jsonb_typeof(main->'owned')='object' then main->'owned' else '{}'::jsonb end;
 lessons:=case when jsonb_typeof(main->'lessonsDone')='array' then main->'lessonsDone' when jsonb_typeof(main->'lessonsDone')='object' then main->'lessonsDone' else '[]'::jsonb end;
 eq:=case when jsonb_typeof(world->'equipmentOwned')='object' then world->'equipmentOwned' else '{}'::jsonb end;
 arts:=case when jsonb_typeof(world->'artifactInstances')='object' then world->'artifactInstances' else '{}'::jsonb end;
 pow_count:=jsonb_object_length(owned);
 if jsonb_typeof(lessons)='array' then lesson_count:=jsonb_array_length(lessons); else lesson_count:=jsonb_object_length(lessons); end if;
 select coalesce(sum(case when value#>>'{}' ~ '^[0-9]+$' then (value#>>'{}')::bigint else 0 end),0) into eq_count from jsonb_each(eq);
 art_count:=jsonb_object_length(arts);
 save_version:=case when coalesce(main->>'saveVersion','')~'^[0-9]+$' then (main->>'saveVersion')::int else 0 end;
 select coalesce(string_agg(key,',' order by key),'') into pow_ids from jsonb_object_keys(owned) key;
 if jsonb_typeof(lessons)='array' then select coalesce(string_agg(value,',' order by value),'') into lesson_ids from jsonb_array_elements_text(lessons) value;
 else select coalesce(string_agg(key,',' order by key),'') into lesson_ids from jsonb_object_keys(lessons) key; end if;
 critical_shape:=jsonb_typeof(main)='object'
  and (not (main ? 'owned') or jsonb_typeof(main->'owned')='object')
  and (not (main ? 'learning') or jsonb_typeof(main->'learning')='object')
  and (jsonb_typeof(p_save->'world') is null or jsonb_typeof(p_save->'world')='object')
  and (not (world ? 'equipmentOwned') or jsonb_typeof(world->'equipmentOwned')='object')
  and (not (world ? 'artifactInstances') or jsonb_typeof(world->'artifactInstances')='object');
 return jsonb_build_object(
  'criticalShape',critical_shape,'saveVersion',save_version,'powCount',pow_count,'lessonsCount',lesson_count,
  'equipmentCopies',eq_count,'artifactInstances',art_count,
  'saveSha256',encode(digest(convert_to(p_save::text,'UTF8'),'sha256'),'hex'),
  'mainSha256',encode(digest(convert_to(main::text,'UTF8'),'sha256'),'hex'),
  'worldSha256',encode(digest(convert_to(world::text,'UTF8'),'sha256'),'hex'),
  'powIdsSha256',encode(digest(convert_to(pow_ids,'UTF8'),'sha256'),'hex'),
  'lessonsSha256',encode(digest(convert_to(lesson_ids,'UTF8'),'sha256'),'hex')
 );
end$$;

create or replace function public.powder_player_save_guard_v20170()
returns trigger language plpgsql security definer set search_path=public as $$
declare n jsonb;o jsonb:='{}'::jsonb;old_main jsonb;new_main jsonb;old_world jsonb;new_world jsonb;
begin
 if jsonb_typeof(new.save_data)<>'object' then raise exception 'SAVE20170_SAVE_NOT_OBJECT'; end if;
 n:=public.powder_save_integrity_summary_v20170(new.save_data);
 if coalesce((n->>'criticalShape')::boolean,false)=false then raise exception 'SAVE20170_CRITICAL_SHAPE_INVALID'; end if;
 if tg_op='UPDATE' then
  o:=public.powder_save_integrity_summary_v20170(old.save_data);
  if coalesce(new.revision,0)<coalesce(old.revision,0) then raise exception 'SAVE20170_REVISION_REGRESSION'; end if;
  if coalesce((n->>'saveVersion')::int,0)<coalesce((o->>'saveVersion')::int,0) then raise exception 'SAVE20170_SCHEMA_DOWNGRADE'; end if;
  if coalesce((o->>'powCount')::int,0)>0 and coalesce((n->>'powCount')::int,0)=0 then raise exception 'SAVE20170_POW_WIPE_BLOCKED'; end if;
  old_main:=case when jsonb_typeof(old.save_data->'main')='object' then old.save_data->'main' else old.save_data end;
  new_main:=case when jsonb_typeof(new.save_data->'main')='object' then new.save_data->'main' else new.save_data end;
  if jsonb_typeof(old_main->'learning')='object' and jsonb_object_length(old_main->'learning')>0 and jsonb_typeof(new_main->'learning')<>'object' then raise exception 'SAVE20170_LEARNING_BRANCH_LOSS'; end if;
  old_world:=case when jsonb_typeof(old.save_data->'world')='object' then old.save_data->'world' else '{}'::jsonb end;
  new_world:=case when jsonb_typeof(new.save_data->'world')='object' then new.save_data->'world' else '{}'::jsonb end;
  if coalesce((o->>'equipmentCopies')::bigint,0)>0 and (old_world ? 'equipmentOwned') and not(new_world ? 'equipmentOwned') then raise exception 'SAVE20170_EQUIPMENT_BRANCH_LOSS'; end if;
  if coalesce((o->>'artifactInstances')::int,0)>0 and (old_world ? 'artifactInstances') and not(new_world ? 'artifactInstances') then raise exception 'SAVE20170_ARTIFACT_BRANCH_LOSS'; end if;
 end if;
 new.integrity_version:='20.17.0';new.integrity_sha256:=n->>'saveSha256';new.integrity_checked_at:=now();new.integrity_summary:=n;
 return new;
end$$;

drop trigger if exists player_save_guard_v20170 on public.player_saves;
create trigger player_save_guard_v20170 before insert or update of save_data,revision,schema_version on public.player_saves for each row execute function public.powder_player_save_guard_v20170();

create or replace function public.powder_player_save_snapshot_v20170()
returns trigger language plpgsql security definer set search_path=public as $$
declare s jsonb:=coalesce(new.integrity_summary,public.powder_save_integrity_summary_v20170(new.save_data));prev public.save_integrity_snapshots_v20170;
begin
 select * into prev from public.save_integrity_snapshots_v20170 where user_id=new.user_id order by revision desc limit 1;
 insert into public.save_integrity_snapshots_v20170(user_id,revision,save_version,schema_version,app_version,device_id,save_sha256,main_sha256,world_sha256,pow_ids_sha256,lessons_sha256,pow_count,lessons_count,equipment_copy_count,artifact_instance_count,critical_shape,summary,captured_at)
 values(new.user_id,new.revision,coalesce((s->>'saveVersion')::int,0),coalesce(new.schema_version,0),coalesce(new.app_version,''),coalesce(new.device_id,''),s->>'saveSha256',s->>'mainSha256',s->>'worldSha256',s->>'powIdsSha256',s->>'lessonsSha256',coalesce((s->>'powCount')::int,0),coalesce((s->>'lessonsCount')::int,0),coalesce((s->>'equipmentCopies')::bigint,0),coalesce((s->>'artifactInstances')::int,0),coalesce((s->>'criticalShape')::boolean,false),s,now())
 on conflict(user_id,revision) do update set save_sha256=excluded.save_sha256,main_sha256=excluded.main_sha256,world_sha256=excluded.world_sha256,pow_ids_sha256=excluded.pow_ids_sha256,lessons_sha256=excluded.lessons_sha256,pow_count=excluded.pow_count,lessons_count=excluded.lessons_count,equipment_copy_count=excluded.equipment_copy_count,artifact_instance_count=excluded.artifact_instance_count,critical_shape=excluded.critical_shape,summary=excluded.summary,captured_at=excluded.captured_at;
 if prev.user_id is not null and new.revision=prev.revision and prev.save_sha256<>coalesce(s->>'saveSha256','') then
  insert into public.save_integrity_incidents_v20170(user_id,revision,severity,code,details) values(new.user_id,new.revision,'high','SAVE20170_SAME_REVISION_HASH_DRIFT',jsonb_build_object('previous',prev.save_sha256,'current',s->>'saveSha256','device',new.device_id));
 end if;
 if prev.user_id is not null and prev.device_id<>coalesce(new.device_id,'') and new.revision<=prev.revision then
  insert into public.save_integrity_incidents_v20170(user_id,revision,severity,code,details) values(new.user_id,new.revision,'high','SAVE20170_STALE_DEVICE_COMMIT',jsonb_build_object('previousRevision',prev.revision,'previousDevice',prev.device_id,'device',new.device_id));
 end if;
 return new;
end$$;

drop trigger if exists player_save_snapshot_v20170 on public.player_saves;
create trigger player_save_snapshot_v20170 after insert or update of save_data,revision,schema_version on public.player_saves for each row execute function public.powder_player_save_snapshot_v20170();

-- Backfill one trustworthy snapshot for every current save after the guard is installed.
insert into public.save_integrity_snapshots_v20170(user_id,revision,save_version,schema_version,app_version,device_id,save_sha256,main_sha256,world_sha256,pow_ids_sha256,lessons_sha256,pow_count,lessons_count,equipment_copy_count,artifact_instance_count,critical_shape,summary,captured_at)
select s.user_id,s.revision,coalesce((x.j->>'saveVersion')::int,0),coalesce(s.schema_version,0),coalesce(s.app_version,''),coalesce(s.device_id,''),x.j->>'saveSha256',x.j->>'mainSha256',x.j->>'worldSha256',x.j->>'powIdsSha256',x.j->>'lessonsSha256',coalesce((x.j->>'powCount')::int,0),coalesce((x.j->>'lessonsCount')::int,0),coalesce((x.j->>'equipmentCopies')::bigint,0),coalesce((x.j->>'artifactInstances')::int,0),coalesce((x.j->>'criticalShape')::boolean,false),x.j,now()
from public.player_saves s cross join lateral (select public.powder_save_integrity_summary_v20170(s.save_data) as j) x
on conflict(user_id,revision) do nothing;

create or replace function public.powder_save_integrity_scan_v20170(p_actor text default '')
returns jsonb language plpgsql security definer set search_path=public as $$
declare total bigint:=0;malformed bigint:=0;missing bigint:=0;revbad bigint:=0;oc bigint:=0;oh bigint:=0;om bigint:=0;cfg public.save_integrity_config_v20170;ready boolean:=false;rid bigint;
begin
 select * into cfg from public.save_integrity_config_v20170 where id=1;
 select count(*) into total from public.player_saves;
 select count(*) into malformed from public.player_saves where jsonb_typeof(save_data)<>'object' or coalesce((integrity_summary->>'criticalShape')::boolean,false)=false or coalesce(integrity_sha256,'')!~'^[0-9a-f]{64}$';
 select count(*) into missing from public.player_saves s where not exists(select 1 from public.save_integrity_snapshots_v20170 x where x.user_id=s.user_id and x.revision=s.revision and x.save_sha256=s.integrity_sha256);
 select count(*) into revbad from (select user_id,revision,lag(revision) over(partition by user_id order by captured_at,revision) p from public.save_integrity_snapshots_v20170) q where p is not null and revision<p;
 select count(*) filter(where severity='critical'),count(*) filter(where severity='high'),count(*) filter(where severity='medium') into oc,oh,om from public.save_integrity_incidents_v20170 where resolved=false;
 ready:=coalesce(cfg.armed,false) and malformed=0 and missing=0 and revbad=0 and oc=0 and oh=0 and om<=coalesce(cfg.max_open_medium,0);
 insert into public.save_integrity_scan_runs_v20170(total_saves,malformed,missing_snapshot,revision_anomaly,open_critical,open_high,open_medium,ready,details,checked_by)
 values(total,malformed,missing,revbad,oc,oh,om,ready,jsonb_build_object('armed',cfg.armed,'maxOpenMedium',cfg.max_open_medium),left(coalesce(p_actor,''),200)) returning id into rid;
 return jsonb_build_object('version','20.17.0','ready',ready,'scanId',rid,'checkedAt',now(),'counts',jsonb_build_object('totalSaves',total,'malformed',malformed,'missingSnapshot',missing,'revisionAnomaly',revbad,'critical',oc,'high',oh,'medium',om),'armed',cfg.armed);
end$$;

create or replace function public.powder_save_integrity_posture_v20170()
returns jsonb language plpgsql security definer set search_path=public as $$
declare cfg public.save_integrity_config_v20170;last public.save_integrity_scan_runs_v20170;stale boolean:=true;ready boolean:=false;
begin
 select * into cfg from public.save_integrity_config_v20170 where id=1;
 select * into last from public.save_integrity_scan_runs_v20170 order by checked_at desc limit 1;
 stale:=last.id is null or last.checked_at<now()-make_interval(hours=>coalesce(cfg.max_snapshot_age_hours,24));
 ready:=coalesce(cfg.armed,false) and coalesce(last.ready,false) and not stale and last.open_critical=0 and last.open_high=0 and last.malformed=0 and last.missing_snapshot=0 and last.revision_anomaly=0;
 return jsonb_build_object('version','20.17.0','ready',ready,'armed',coalesce(cfg.armed,false),'checkedAt',now(),'scanStale',stale,'lastScan',case when last.id is null then null else to_jsonb(last) end,
 'guards',jsonb_build_object('serverHashEnvelope',true,'revisionRegressionBlocked',true,'powWipeBlocked',true,'schemaDowngradeBlocked',true,'criticalBranchLossBlocked',true,'snapshotHistory',true,'multiDeviceDiagnostics',true));
end$$;

create or replace function public.powder_save_integrity_arm_v20170(p_armed boolean,p_actor text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 update public.save_integrity_config_v20170 set armed=coalesce(p_armed,false),updated_at=now(),updated_by=left(coalesce(p_actor,''),200) where id=1;
 return public.powder_save_integrity_posture_v20170();
end$$;

create or replace function public.powder_save_integrity_resolve_v20170(p_id bigint,p_actor text,p_note text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 if length(btrim(coalesce(p_note,'')))<8 then raise exception 'SAVE20170_RESOLUTION_NOTE_REQUIRED';end if;
 update public.save_integrity_incidents_v20170 set resolved=true,resolved_at=now(),resolved_by=left(coalesce(p_actor,''),200),details=details||jsonb_build_object('resolutionNote',left(p_note,1200),'resolvedAt',now()) where id=p_id and resolved=false;
 if not found then raise exception 'SAVE20170_INCIDENT_NOT_FOUND';end if;
 return jsonb_build_object('ok',true,'id',p_id,'resolvedAt',now());
end$$;

-- Make the new save controls critical under the existing 20.16 centralized Admin guard.
insert into public.security_critical_actions_v20160(function_name,action,require_owner,require_aal2,notes) values
 ('powder-admin-integrity','save_integrity_arm',true,true,'Arm/disarm Player Save Integrity production gate'),
 ('powder-admin-integrity','save_integrity_scan',false,true,'Run authoritative Player Save Integrity scan'),
 ('powder-admin-integrity','save_integrity_resolve',true,true,'Resolve Player Save Integrity incident')
on conflict(function_name,action) do update set require_owner=excluded.require_owner,require_aal2=excluded.require_aal2,notes=excluded.notes;

revoke all on function public.powder_save_integrity_summary_v20170(jsonb),public.powder_save_integrity_scan_v20170(text),public.powder_save_integrity_posture_v20170(),public.powder_save_integrity_arm_v20170(boolean,text),public.powder_save_integrity_resolve_v20170(bigint,text,text) from public,anon,authenticated;
grant execute on function public.powder_save_integrity_summary_v20170(jsonb),public.powder_save_integrity_scan_v20170(text),public.powder_save_integrity_posture_v20170(),public.powder_save_integrity_arm_v20170(boolean,text),public.powder_save_integrity_resolve_v20170(bigint,text,text) to service_role;

commit;
